Repository scalar-labs/scalardb, pull requests merged in 2021-07, with the labels that each got.

#227 Add Docker support for Scalar DB Server
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoDatabaseConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseConfig.java
  server/Dockerfile
  server/README.md
  server/build.gradle
  server/conf/log4j.properties
Labels: enhancement

#231 Rename some classes in the Server project
  server/src/main/java/com/scalar/db/server/ScalarDbServer.java
  server/src/main/java/com/scalar/db/server/config/ServerConfig.java
  server/src/main/java/com/scalar/db/server/service/ServerModule.java
  server/src/test/java/com/scalar/db/server/DistributedStorageAdminServiceTest.java
  server/src/test/java/com/scalar/db/server/DistributedStorageServiceTest.java
  server/src/test/java/com/scalar/db/server/DistributedTransactionServiceTest.java
Labels: improvement

#233 Fix the getting started project
  docs/getting-started/build.gradle
  docs/getting-started/settings.gradle
Labels: bugfix

#232 Add unit tests for ServerConfig
  server/src/main/java/com/scalar/db/server/config/ServerConfig.java
  server/src/test/java/com/scalar/db/server/config/ServerConfigTest.java
Labels: improvement

#230 Make DistributedStorageAdmin throw ExecutionException
  core/src/integration-test/java/com/scalar/db/storage/AdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
  core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/service/AdminService.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdminTest.java
  core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTest.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcAdminTest.java
  server/src/test/java/com/scalar/db/server/DistributedStorageAdminServiceTest.java
Labels: improvement

#228 Use bidirectional streaming RPCs in DistributedTransactionService
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransaction.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStream.java
  core/src/main/java/com/scalar/db/util/ThrowableRunnable.java
  core/src/main/java/com/scalar/db/util/ThrowableSupplier.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionManagerTest.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionGrpc.java
  rpc/src/main/java/com/scalar/db/rpc/AbortRequest.java
  rpc/src/main/java/com/scalar/db/rpc/AbortRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/CommitRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CommitRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/MutateRequest.java
  rpc/src/main/java/com/scalar/db/rpc/MutateRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java
  rpc/src/main/java/com/scalar/db/rpc/StartTransactionRequest.java
  rpc/src/main/java/com/scalar/db/rpc/StartTransactionRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionResponse.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionResponseOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionalGetRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionalGetRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionalMutateRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionalMutateRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionalScanRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionalScanRequestOrBuilder.java
  rpc/src/main/proto/scalardb.proto
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java
  server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java
  server/src/main/java/com/scalar/db/server/DistributedStorageService.java
  server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
  server/src/test/java/com/scalar/db/server/DistributedStorageServiceTest.java
  server/src/test/java/com/scalar/db/server/DistributedTransactionServiceTest.java
Labels: improvement

#236 Reorganize the protocol buffer messages for DistributedTransaction
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStream.java
  rpc/src/main/java/com/scalar/db/rpc/AbortRequest.java
  rpc/src/main/java/com/scalar/db/rpc/AbortRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/CommitRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CommitRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java
  rpc/src/main/java/com/scalar/db/rpc/StartTransactionRequest.java
  rpc/src/main/java/com/scalar/db/rpc/StartTransactionRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/StartTransactionResponse.java
  rpc/src/main/java/com/scalar/db/rpc/StartTransactionResponseOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionResponse.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionResponseOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionalGetRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionalGetRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionalGetResponse.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionalGetResponseOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionalMutateRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionalMutateRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionalScanRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionalScanRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionalScanResponse.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionalScanResponseOrBuilder.java
  rpc/src/main/proto/scalardb.proto
  server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
Labels: improvement

#237 Revise README.md of root folder
  README.md
Labels: documentation

#234 Adding beginner friendly precisions
  docs/getting-started-with-scalardb.md
Labels: documentation

#235 Use bidirectional streaming RPCs for scan operations in DistributedStorageService
  core/src/main/java/com/scalar/db/storage/rpc/GrpcScanOnBidirectionalStream.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
  core/src/main/java/com/scalar/db/storage/rpc/ScannerImpl.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcStorageTest.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageGrpc.java
  rpc/src/main/java/com/scalar/db/rpc/CloseScannerRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CloseScannerRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/OpenScannerRequest.java
  rpc/src/main/java/com/scalar/db/rpc/OpenScannerResponseOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java
  rpc/src/main/java/com/scalar/db/rpc/ScanNextRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/ScanNextResponse.java
  rpc/src/main/java/com/scalar/db/rpc/ScanRequest.java
  rpc/src/main/java/com/scalar/db/rpc/ScanRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/ScanResponse.java
  rpc/src/main/java/com/scalar/db/rpc/ScanResponseOrBuilder.java
  rpc/src/main/proto/scalardb.proto
  server/src/main/java/com/scalar/db/server/DistributedStorageService.java
  server/src/test/java/com/scalar/db/server/DistributedStorageServiceTest.java
Labels: improvement

#238 Make Scalar DB transactions be able to abort eagerly
  core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java
  core/src/main/java/com/scalar/db/service/TransactionService.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionManagerTest.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionGrpc.java
  rpc/src/main/java/com/scalar/db/rpc/AbortRequest.java
  rpc/src/main/java/com/scalar/db/rpc/AbortRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/AbortResponse.java
  rpc/src/main/java/com/scalar/db/rpc/AbortResponseOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java
  rpc/src/main/proto/scalardb.proto
  server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
  server/src/test/java/com/scalar/db/server/DistributedTransactionServiceTest.java
Labels: enhancement

#239 Add transaction manager config
  conf/database.properties
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/service/TransactionModule.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseConfig.java
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseConfigTest.java
  docs/getting-started-with-scalardb-on-jdbc.md
  docs/getting-started-with-scalardb.md
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithJdbcTransactionIntegrationTest.java
Labels: enhancement

#240 Add the admin interface to Scalar DB server
  core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcScanOnBidirectionalStream.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcTableMetadataManager.java
  core/src/main/java/com/scalar/db/storage/rpc/ScannerImpl.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStream.java
  core/src/main/java/com/scalar/db/util/retry/Retry.java
  core/src/main/java/com/scalar/db/util/retry/ServiceTemporaryUnavailableException.java
  server/build.gradle
  server/src/main/java/com/scalar/db/server/AdminService.java
  server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java
  server/src/main/java/com/scalar/db/server/DistributedStorageService.java
  server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
  server/src/main/java/com/scalar/db/server/Pauser.java
  server/src/main/java/com/scalar/db/server/ScalarDbServer.java
  server/src/main/java/com/scalar/db/server/service/ServerModule.java
  server/src/test/java/com/scalar/db/server/DistributedStorageServiceTest.java
  server/src/test/java/com/scalar/db/server/DistributedTransactionServiceTest.java
Labels: enhancement

#242 Use Uninterruptibles in Guava
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithDynamoIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcScanOnBidirectionalStream.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStream.java
  core/src/main/java/com/scalar/db/util/retry/Retry.java
  server/src/main/java/com/scalar/db/server/Pauser.java
Labels: improvement

#243 Some refactoring for the implementations of DistributedStorageAdmin
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraTableMetadataManager.java
  core/src/main/java/com/scalar/db/storage/cassandra/ClusterManager.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  core/src/test/java/com/scalar/db/storage/cassandra/ClusterManagerTest.java
Labels: improvement

#241 Revisit the code around onCompleted() in bidirectional streaming of gRPC
  core/src/main/java/com/scalar/db/storage/rpc/GrpcScanOnBidirectionalStream.java
  core/src/main/java/com/scalar/db/storage/rpc/ScannerImpl.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStream.java
  server/src/main/java/com/scalar/db/server/DistributedStorageService.java
Labels: improvement

#244 Support graceful shutdown
  server/src/main/java/com/scalar/db/server/ScalarDbServer.java
Labels: improvement

#245 Add metrics to Scalar DB Server
  server/build.gradle
  server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java
  server/src/main/java/com/scalar/db/server/DistributedStorageService.java
  server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
  server/src/main/java/com/scalar/db/server/Metrics.java
  server/src/main/java/com/scalar/db/server/service/ServerModule.java
  server/src/test/java/com/scalar/db/server/DistributedStorageAdminServiceTest.java
  server/src/test/java/com/scalar/db/server/DistributedStorageServiceTest.java
  server/src/test/java/com/scalar/db/server/DistributedTransactionServiceTest.java
Labels: enhancement

#246 Support Prometheus in Scalar DB Server
  server/build.gradle
  server/src/main/java/com/scalar/db/server/ScalarDbServer.java
  server/src/main/java/com/scalar/db/server/config/ServerConfig.java
  server/src/main/java/com/scalar/db/server/service/ServerModule.java
  server/src/test/java/com/scalar/db/server/config/ServerConfigTest.java
Labels: enhancement

#247 Refactoring the code around DatabaseConfig
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/test/TestEnv.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithDynamoIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithJdbcDatabaseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionIntegrationTest.java
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/service/StorageModule.java
  core/src/main/java/com/scalar/db/service/TransactionModule.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoConfigTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitWithDistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithJdbcTransactionIntegrationTest.java
Labels: improvement

#248 Support deadline in Scalar DB Server clients
  core/src/main/java/com/scalar/db/service/StorageModule.java
  core/src/main/java/com/scalar/db/service/TransactionModule.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcScanOnBidirectionalStream.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcTableMetadataManager.java
  core/src/main/java/com/scalar/db/storage/rpc/ScannerImpl.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStream.java
  core/src/main/java/com/scalar/db/util/Utility.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcAdminTest.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcStorageTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionManagerTest.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitWithDistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithJdbcTransactionIntegrationTest.java
Labels: improvement

#250 Use the Scalar DB server default port if not specified in the Scalar DB server client
  core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
Labels: improvement

#251 Expose the Prometheus HTTP endpoint port in the Scalar DB server Docker image
  server/Dockerfile
Labels: enhancement

#256 Some changes related to release
  archive.gradle
  build.gradle
Labels: improvement

#253 Add documentation of Scalar DB Server
  docs/getting-started-with-scalardb.md
  docs/scalardb-server.md
  server/README.md
Labels: documentation

#254 Add a backup guide for the Scalar DB server
  docs/backup-restore.md
Labels: documentation

#255 Add multi-storage documentation
  docs/getting-started-with-scalardb.md
  docs/multi-storage.md
Labels: documentation

#258 Some more release related changes
  .github/workflows/release.yaml
  build.gradle
  core/archive.gradle
  core/build.gradle
  rpc/archive.gradle
  rpc/build.gradle
  server/archive.gradle
  server/build.gradle
  tools/scalar-schema/project.clj
Labels: improvement

#261 Refactor build.gradle
  build.gradle
  core/build.gradle
  rpc/build.gradle
  server/build.gradle
Labels: improvement

#249 Add Scalar DB supported databases
  README.md
  docs/scalar-db-supported-databases.md
Labels: enhancement
