Repository scalar-labs/scalardb, pull requests merged in 2021-10, with the labels that each got.

#325 Create Coordinator namespace in ConsensusCommitAdmin
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTest.java
Labels: improvement

#321 Add Table metadata cache expiration configuration
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/storage/common/TableMetadataManager.java
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  core/src/test/java/com/scalar/db/storage/common/TableMetadataManagerTest.java
Labels: enhancement

#331 Make Coordinator backward compatible
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
Labels: improvement

#330 Add ifExists support to dropNamespace() and dropTable() in DistributedStorageAdmin
  core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java
Labels: enhancement

#329 Add methods to truncate and drop coordinator table to ConsensusCommitAdmin
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTest.java
Labels: enhancement

#332 Refactor integration tests
  .circleci/config.yml
  core/build.gradle
  core/src/integration-test/java/com/scalar/db/storage/AdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraEnv.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosEnv.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoEnv.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoWithReservedKeywordIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/test/TestEnv.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageEnv.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCosmosIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithDynamoIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithJdbcDatabaseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithMultiStorageIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosMutationTest.java
  server/build.gradle
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitWithDistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithJdbcTransactionIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/ServerEnv.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitWithExtraReadIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitWithExtraWriteIntegrationTest.java
  server/src/main/java/com/scalar/db/server/ScalarDbServer.java
Labels: improvement

#327 Correct comparator of item sorter in Dynamo DB adapter
  core/src/main/java/com/scalar/db/storage/dynamo/ItemSorter.java
  core/src/test/java/com/scalar/db/storage/dynamo/ItemSorterTest.java
Labels: bugfix

#333 Remove namespace prefix
  conf/database.properties
  core/src/main/java/com/scalar/db/api/Delete.java
  core/src/main/java/com/scalar/db/api/Get.java
  core/src/main/java/com/scalar/db/api/Mutation.java
  core/src/main/java/com/scalar/db/api/Operation.java
  core/src/main/java/com/scalar/db/api/Put.java
  core/src/main/java/com/scalar/db/api/Selection.java
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/service/TransactionFactory.java
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cassandra/DeleteStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cassandra/InsertStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cassandra/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cassandra/UpdateStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/BatchHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/StatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoOperation.java
  core/src/main/java/com/scalar/db/storage/jdbc/ConditionalMutator.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/util/Utility.java
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTest.java
  core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosConfigTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoConfigTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageConfigTest.java
  docs/multi-storage.md
Labels: improvement

#334 Add no_output_timeout option for Cosmos DB integration test
  .circleci/config.yml
Labels: improvement

#337 FloatValue should be mapped to double type in MySQL
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdminTest.java
  docs/schema.md
Labels: bugfix

#359 Fix cqlsh install failure
  .circleci/config.yml
Labels: bugfix
