Repository scalar-labs/scalardb, pull requests merged in 2021-03, with the labels that each got.

#167 Add the integration tests for the Cosmos DB adapter and the DynamoDB …
  .circleci/config.yml
  build.gradle
  src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/jdbc/test/TestEnv.java
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCosmosIntegrationTest.java
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithDynamoIntegrationTest.java
  src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
Labels: improvement

#168 Change metadata of partition key and clustering key from Set to Linke…
  src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCosmosIntegrationTest.java
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithDynamoIntegrationTest.java
  src/main/java/com/scalar/db/storage/ImmutableLinkedHashSet.java
  src/main/java/com/scalar/db/storage/TableMetadata.java
  src/main/java/com/scalar/db/storage/cassandra/CassandraTableMetadata.java
  src/main/java/com/scalar/db/storage/cosmos/CosmosTableMetadata.java
  src/main/java/com/scalar/db/storage/dynamo/DynamoTableMetadata.java
  src/main/java/com/scalar/db/storage/jdbc/metadata/JdbcTableMetadata.java
  src/test/java/com/scalar/db/storage/cassandra/ResultImplTest.java
  src/test/java/com/scalar/db/storage/cosmos/BatchHandlerTest.java
  src/test/java/com/scalar/db/storage/cosmos/CosmosMutationTest.java
  src/test/java/com/scalar/db/storage/cosmos/CosmosOperationTest.java
  src/test/java/com/scalar/db/storage/cosmos/DeleteStatementHandlerTest.java
  src/test/java/com/scalar/db/storage/cosmos/PutStatementHandlerTest.java
  src/test/java/com/scalar/db/storage/cosmos/ResultImplTest.java
  src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
  src/test/java/com/scalar/db/storage/dynamo/BatchHandlerTest.java
  src/test/java/com/scalar/db/storage/dynamo/DeleteStatementHandlerTest.java
  src/test/java/com/scalar/db/storage/dynamo/DynamoMutationTest.java
  src/test/java/com/scalar/db/storage/dynamo/DynamoOperationTest.java
  src/test/java/com/scalar/db/storage/dynamo/DynamoTableMetadataTest.java
  src/test/java/com/scalar/db/storage/dynamo/PutStatementHandlerTest.java
  src/test/java/com/scalar/db/storage/dynamo/ResultImplTest.java
  src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
  tools/scalar-schema/java/src/CosmosTableMetadata.java
  tools/scalar-schema/src/scalar_schema/core.clj
  tools/scalar-schema/src/scalar_schema/cosmos.clj
  tools/scalar-schema/src/scalar_schema/dynamo.clj
Labels: improvement

#170 Specify a driver class corresponding to the JDBC URL to the dataSource
  src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
Labels: improvement

#172 Unify the integration tests of Scalar DB on X
  build.gradle
  src/integration-test/java/com/scalar/db/storage/IntegrationTestBase.java
  src/integration-test/java/com/scalar/db/storage/MetadataIntegrationTestBase.java
  src/integration-test/java/com/scalar/db/storage/cassandra/CassandraIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/cassandra/CassandraMetadataIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMetadataIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/dynamo/DynamoMetadataIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/jdbc/JdbcMetadataIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/jdbc/test/TestEnv.java
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCosmosIntegrationTest.java
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithDynamoIntegrationTest.java
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithJdbcDatabaseIntegrationTest.java
  src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionIntegrationTest.java
Labels: improvement

#173 Wrong index name when a namespace prefix is not specified in the sche…
  tools/scalar-schema/src/scalar_schema/dynamo/common.clj
Labels: bugfix

#175 Fix the broken TLA+ link
  docs/index.md
Labels: bugfix

#174 Add a new storage implementation for multi-storage
  .circleci/config.yml
  build.gradle
  src/integration-test/java/com/scalar/db/storage/jdbc/test/TestEnv.java
  src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageIntegrationTest.java
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithMultiStorageIntegrationTest.java
  src/main/java/com/scalar/db/api/DistributedTransaction.java
  src/main/java/com/scalar/db/config/DatabaseConfig.java
  src/main/java/com/scalar/db/service/StorageModule.java
  src/main/java/com/scalar/db/service/TransactionModule.java
  src/main/java/com/scalar/db/storage/multistorage/MultiStorage.java
  src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java
  src/test/java/com/scalar/db/storage/multistorage/MultiStorageConfigTest.java
Labels: enhancement

#176 Extend the ConsensusCommit integration tests to cover multi-table transactions
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
Labels: bugfix, improvement

#177 Fix scan related tests in Scalar DB
  src/integration-test/java/com/scalar/db/storage/IntegrationTestBase.java
  src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/jdbc/JdbcMetadataIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/jdbc/test/TestEnv.java
  src/main/java/com/scalar/db/storage/jdbc/metadata/JdbcTableMetadata.java
  src/main/java/com/scalar/db/storage/jdbc/metadata/TableMetadataManager.java
  src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java
  src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
  src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
  src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
  tools/scalar-schema/src/scalar_schema/jdbc.clj
Labels: improvement
