Repository scalar-labs/scalardb, pull requests merged in 2021-01, with the labels that each got.

#138 Fix Snapshot to handle deleteSet properly when a delete operation is mixed with other operations.
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTest.java
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
  src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
Labels: bugfix

#144 Modify TableMetadata for secondary indexes
  src/main/java/com/scalar/db/storage/TableMetadata.java
  src/main/java/com/scalar/db/storage/cassandra/CassandraTableMetadata.java
  src/main/java/com/scalar/db/storage/cosmos/CosmosTableMetadata.java
  src/main/java/com/scalar/db/storage/dynamo/DynamoTableMetadata.java
Labels: enhancement

#145 Guard C* get and scan with a secondary index
  src/main/java/com/scalar/db/storage/Utility.java
  src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
Labels: improvement

#146 Support secondary indexes on Cosmos DB
  src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
  src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java
  src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
Labels: enhancement

#139 Add integration tests for Get and Scan with a Cassandra secondary index.
  src/integration-test/java/com/scalar/db/storage/cassandra/CassandraIntegrationTest.java
Labels: improvement

#140 [Scalar-Schema] Set Cassandra secondary index
  tools/scalar-schema/sample_schema/sample_schema.json
  tools/scalar-schema/src/scalar_schema/cassandra.clj
  tools/scalar-schema/src/scalar_schema/common.clj
Labels: enhancement

#141 [Scalar-Schema] Set Cosmos secondary index
  tools/scalar-schema/java/src/CosmosTableMetadata.java
  tools/scalar-schema/src/scalar_schema/cosmos.clj
Labels: enhancement

#142 [Scalar-Schema] Set DynamoDB secondary index
  tools/scalar-schema/src/scalar_schema/dynamo.clj
  tools/scalar-schema/src/scalar_schema/dynamo/auto_scaling.clj
  tools/scalar-schema/src/scalar_schema/dynamo/common.clj
Labels: enhancement

#147 Support secondary indexes on DynamoDB
  src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
  src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  src/main/java/com/scalar/db/storage/dynamo/DynamoOperation.java
  src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
Labels: enhancement

#149 Fix pip install failure in CI
  .circleci/config.yml
Labels: bugfix
