Repository scalar-labs/scalardb, pull requests merged in 2021-05, with the labels that each got.

#194 upgrade guice version to 5.0.1 for java 11 compatibility
  build.gradle
Labels: improvement

#196 Fix warnings of raw use of parameterized class for the Value class
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionIntegrationTest.java
  src/main/java/com/scalar/db/api/ConditionalExpression.java
  src/main/java/com/scalar/db/api/Put.java
  src/main/java/com/scalar/db/api/Result.java
  src/main/java/com/scalar/db/io/Key.java
  src/main/java/com/scalar/db/io/Value.java
  src/main/java/com/scalar/db/storage/cassandra/ResultImpl.java
  src/main/java/com/scalar/db/storage/cassandra/SelectStatementHandler.java
  src/main/java/com/scalar/db/storage/common/checker/ColumnChecker.java
  src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
  src/main/java/com/scalar/db/storage/common/util/Utility.java
  src/main/java/com/scalar/db/storage/cosmos/CosmosMutation.java
  src/main/java/com/scalar/db/storage/cosmos/CosmosOperation.java
  src/main/java/com/scalar/db/storage/cosmos/ResultImpl.java
  src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java
  src/main/java/com/scalar/db/storage/dynamo/DynamoMutation.java
  src/main/java/com/scalar/db/storage/dynamo/DynamoOperation.java
  src/main/java/com/scalar/db/storage/dynamo/ResultImpl.java
  src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  src/main/java/com/scalar/db/storage/jdbc/ResultImpl.java
  src/main/java/com/scalar/db/storage/jdbc/query/DeleteQuery.java
  src/main/java/com/scalar/db/storage/jdbc/query/InsertOnConflictDoUpdateQuery.java
  src/main/java/com/scalar/db/storage/jdbc/query/InsertOnDuplicateKeyUpdateQuery.java
  src/main/java/com/scalar/db/storage/jdbc/query/InsertQuery.java
  src/main/java/com/scalar/db/storage/jdbc/query/MergeIntoQuery.java
  src/main/java/com/scalar/db/storage/jdbc/query/MergeQuery.java
  src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java
  src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
  src/main/java/com/scalar/db/storage/jdbc/query/UpdateQuery.java
  src/main/java/com/scalar/db/storage/jdbc/query/UpsertQuery.java
  src/main/java/com/scalar/db/transaction/consensuscommit/Attribute.java
  src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java
  src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java
  src/main/java/com/scalar/db/transaction/consensuscommit/TransactionResult.java
  src/test/java/com/scalar/db/api/DeleteTest.java
  src/test/java/com/scalar/db/api/GetTest.java
  src/test/java/com/scalar/db/api/PutTest.java
  src/test/java/com/scalar/db/api/ScanTest.java
  src/test/java/com/scalar/db/io/KeyTest.java
  src/test/java/com/scalar/db/storage/cassandra/ResultImplTest.java
  src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
  src/test/java/com/scalar/db/storage/cosmos/ResultImplTest.java
  src/test/java/com/scalar/db/storage/dynamo/ResultImplTest.java
  src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
  src/test/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposerTest.java
  src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  src/test/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposerTest.java
  src/test/java/com/scalar/db/transaction/consensuscommit/RecoveryHandlerTest.java
  src/test/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposerTest.java
  src/test/java/com/scalar/db/transaction/consensuscommit/TransactionResultTest.java
Labels: improvement

#198 Add utility methods for Value/Put and a builder class for Key
  src/main/java/com/scalar/db/api/Put.java
  src/main/java/com/scalar/db/io/BigIntValue.java
  src/main/java/com/scalar/db/io/BlobValue.java
  src/main/java/com/scalar/db/io/BooleanValue.java
  src/main/java/com/scalar/db/io/DoubleValue.java
  src/main/java/com/scalar/db/io/FloatValue.java
  src/main/java/com/scalar/db/io/IntValue.java
  src/main/java/com/scalar/db/io/Key.java
  src/main/java/com/scalar/db/io/TextValue.java
  src/main/java/com/scalar/db/io/Value.java
  src/test/java/com/scalar/db/api/PutTest.java
  src/test/java/com/scalar/db/io/BigIntValueTest.java
  src/test/java/com/scalar/db/io/BlobValueTest.java
  src/test/java/com/scalar/db/io/BooleanValueTest.java
  src/test/java/com/scalar/db/io/DoubleValueTest.java
  src/test/java/com/scalar/db/io/FloatValueTest.java
  src/test/java/com/scalar/db/io/IntValueTest.java
  src/test/java/com/scalar/db/io/KeyTest.java
  src/test/java/com/scalar/db/io/TextValueTest.java
Labels: improvement

#200 Use com.google.inject.Inject instead of javax.inject.Inject
  src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  src/main/java/com/scalar/db/storage/multistorage/MultiStorage.java
  src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
Labels: bugfix

#197 Refactor exceptions in Scalar DB for easier retry handling
  src/main/java/com/scalar/db/exception/transaction/CrudConflictException.java
  src/main/java/com/scalar/db/exception/transaction/UncommittedRecordException.java
  src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
  src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
Labels: improvement

#201 Allow username and password to be null in DatabaseConfig
  src/main/java/com/scalar/db/config/DatabaseConfig.java
  src/main/java/com/scalar/db/storage/cassandra/ClusterManager.java
  src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
  src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseConfigTest.java
  src/test/java/com/scalar/db/storage/multistorage/MultiStorageConfigTest.java
Labels: improvement

#203 Refactor the code around Scanner
  src/integration-test/java/com/scalar/db/storage/IntegrationTestBase.java
  src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  src/main/java/com/scalar/db/storage/cassandra/ResultImpl.java
  src/main/java/com/scalar/db/storage/cassandra/ResultInterpreter.java
  src/main/java/com/scalar/db/storage/cassandra/ScannerImpl.java
  src/main/java/com/scalar/db/storage/cassandra/ScannerIterator.java
  src/main/java/com/scalar/db/storage/common/ResultImpl.java
  src/main/java/com/scalar/db/storage/common/ScannerIterator.java
  src/main/java/com/scalar/db/storage/common/util/Utility.java
  src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  src/main/java/com/scalar/db/storage/cosmos/ResultImpl.java
  src/main/java/com/scalar/db/storage/cosmos/ResultInterpreter.java
  src/main/java/com/scalar/db/storage/cosmos/ScannerImpl.java
  src/main/java/com/scalar/db/storage/cosmos/ScannerIterator.java
  src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  src/main/java/com/scalar/db/storage/dynamo/DynamoOperation.java
  src/main/java/com/scalar/db/storage/dynamo/ResultImpl.java
  src/main/java/com/scalar/db/storage/dynamo/ResultInterpreter.java
  src/main/java/com/scalar/db/storage/dynamo/ScannerImpl.java
  src/main/java/com/scalar/db/storage/dynamo/ScannerIterator.java
  src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  src/main/java/com/scalar/db/storage/jdbc/ResultImpl.java
  src/main/java/com/scalar/db/storage/jdbc/ResultInterpreter.java
  src/main/java/com/scalar/db/storage/jdbc/ScannerImpl.java
  src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java
  src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
  src/test/java/com/scalar/db/storage/cassandra/ResultImplTest.java
  src/test/java/com/scalar/db/storage/cassandra/ResultInterpreterTest.java
  src/test/java/com/scalar/db/storage/common/ResultImplTest.java
  src/test/java/com/scalar/db/storage/cosmos/ResultImplTest.java
  src/test/java/com/scalar/db/storage/cosmos/ResultInterpreterTest.java
  src/test/java/com/scalar/db/storage/dynamo/ResultImplTest.java
  src/test/java/com/scalar/db/storage/dynamo/ResultInterpreterTest.java
  src/test/java/com/scalar/db/storage/dynamo/ScannerImplTest.java
  src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java
  src/test/java/com/scalar/db/storage/jdbc/ResultInterpreterTest.java
  src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
Labels: improvement

#204 Introduce DistributedStorageAdmin that is an administrative interface…
  src/integration-test/java/com/scalar/db/storage/AdminIntegrationTestBase.java
  src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
  src/main/java/com/scalar/db/api/DistributedStorageAdmin.java
  src/main/java/com/scalar/db/config/DatabaseConfig.java
  src/main/java/com/scalar/db/service/AdminService.java
  src/main/java/com/scalar/db/service/StorageModule.java
  src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  src/main/java/com/scalar/db/storage/cassandra/CassandraTableMetadataManager.java
  src/main/java/com/scalar/db/storage/common/TableMetadataManager.java
  src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  src/main/java/com/scalar/db/storage/cosmos/CosmosTableMetadataManager.java
  src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  src/main/java/com/scalar/db/storage/dynamo/DynamoTableMetadataManager.java
  src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
  src/main/java/com/scalar/db/storage/jdbc/JdbcTableMetadataManager.java
  src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTest.java
  src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
  src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
  src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdminTest.java
  src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseConfigTest.java
Labels: enhancement

#205 Remove MultiPartitionException
  src/integration-test/java/com/scalar/db/storage/IntegrationTestBase.java
  src/main/java/com/scalar/db/exception/storage/MultiPartitionException.java
  src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
  src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
Labels: improvement

#206 Add some more useful methods to Key.Builder
  src/main/java/com/scalar/db/io/Key.java
  src/test/java/com/scalar/db/api/PutTest.java
  src/test/java/com/scalar/db/io/KeyTest.java
Labels: improvement

#209 Support the endpoint override feature for Dynamo
  src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithDynamoIntegrationTest.java
  src/main/java/com/scalar/db/service/StorageModule.java
  src/main/java/com/scalar/db/service/TransactionModule.java
  src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  src/main/java/com/scalar/db/storage/dynamo/DynamoDatabaseConfig.java
  src/test/java/com/scalar/db/storage/dynamo/DynamoDatabaseConfigTest.java
Labels: improvement

#208 Should close PreparedStatement and ResultSet in scan operations of Jd…
  src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
  src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java
  src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
Labels: bug

#207 Support namespace mappings in MultiStorage
  src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageIntegrationTest.java
  src/main/java/com/scalar/db/storage/multistorage/MultiStorage.java
  src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java
  src/test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTest.java
  src/test/java/com/scalar/db/storage/multistorage/MultiStorageConfigTest.java
  src/test/java/com/scalar/db/storage/multistorage/MultiStorageTest.java
Labels: improvement
