Repository scalar-labs/scalardb, pull requests merged in 2021-04, with the labels that each got.

#179 Refactor some configuration names
  conf/database.properties
  docs/getting-started-with-scalardb-on-jdbc.md
  docs/getting-started-with-scalardb.md
  src/main/java/com/scalar/db/config/DatabaseConfig.java
  src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseConfig.java
Labels: enhancement (backward-incompatible)

#178 Unify the behavior between the adapters when a specified table in a o…
  src/integration-test/java/com/scalar/db/storage/IntegrationTestBase.java
  src/integration-test/java/com/scalar/db/storage/cassandra/CassandraMetadataIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMetadataIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/dynamo/DynamoMetadataIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/jdbc/JdbcMetadataIntegrationTest.java
  src/integration-test/java/com/scalar/db/storage/jdbc/test/TestEnv.java
  src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  src/main/java/com/scalar/db/storage/cassandra/CassandraTableMetadataManager.java
  src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
  src/main/java/com/scalar/db/storage/common/metadata/TableMetadataManager.java
  src/main/java/com/scalar/db/storage/cosmos/BatchHandler.java
  src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  src/main/java/com/scalar/db/storage/cosmos/CosmosMutation.java
  src/main/java/com/scalar/db/storage/cosmos/CosmosOperation.java
  src/main/java/com/scalar/db/storage/cosmos/CosmosTableMetadataManager.java
  src/main/java/com/scalar/db/storage/cosmos/DeleteStatementHandler.java
  src/main/java/com/scalar/db/storage/cosmos/MutateStatementHandler.java
  src/main/java/com/scalar/db/storage/cosmos/PutStatementHandler.java
  src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java
  src/main/java/com/scalar/db/storage/cosmos/StatementHandler.java
  src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java
  src/main/java/com/scalar/db/storage/dynamo/DeleteStatementHandler.java
  src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  src/main/java/com/scalar/db/storage/dynamo/DynamoMutation.java
  src/main/java/com/scalar/db/storage/dynamo/DynamoOperation.java
  src/main/java/com/scalar/db/storage/dynamo/DynamoTableMetadataManager.java
  src/main/java/com/scalar/db/storage/dynamo/PutStatementHandler.java
  src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  src/main/java/com/scalar/db/storage/dynamo/StatementHandler.java
  src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  src/main/java/com/scalar/db/storage/jdbc/metadata/JdbcTableMetadataManager.java
  src/main/java/com/scalar/db/storage/jdbc/query/QueryBuilder.java
  src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java
  src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
  src/test/java/com/scalar/db/storage/cosmos/BatchHandlerTest.java
  src/test/java/com/scalar/db/storage/cosmos/CosmosMutationTest.java
  src/test/java/com/scalar/db/storage/cosmos/CosmosOperationTest.java
  src/test/java/com/scalar/db/storage/cosmos/CosmosTableMetadataManagerTest.java
  src/test/java/com/scalar/db/storage/cosmos/DeleteStatementHandlerTest.java
  src/test/java/com/scalar/db/storage/cosmos/PutStatementHandlerTest.java
  src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
  src/test/java/com/scalar/db/storage/cosmos/StatementHandlerTest.java
  src/test/java/com/scalar/db/storage/dynamo/BatchHandlerTest.java
  src/test/java/com/scalar/db/storage/dynamo/DeleteStatementHandlerTest.java
  src/test/java/com/scalar/db/storage/dynamo/DynamoMutationTest.java
  src/test/java/com/scalar/db/storage/dynamo/DynamoOperationTest.java
  src/test/java/com/scalar/db/storage/dynamo/DynamoTableMetadataManagerTest.java
  src/test/java/com/scalar/db/storage/dynamo/PutStatementHandlerTest.java
  src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
  src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
Labels: improvement

#180 Fix the bug where the error occurs when executing a Put operation wit…
  src/integration-test/java/com/scalar/db/storage/IntegrationTestBase.java
  src/main/java/com/scalar/db/storage/jdbc/query/InsertOnConflictDoUpdateQuery.java
  src/main/java/com/scalar/db/storage/jdbc/query/InsertOnDuplicateKeyUpdateQuery.java
  src/main/java/com/scalar/db/storage/jdbc/query/MergeIntoQuery.java
  src/main/java/com/scalar/db/storage/jdbc/query/MergeQuery.java
  src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
Labels: bugfix

#181 Update data type mapping
  docs/schema.md
  tools/scalar-schema/README.md
Labels: documentation

#182 Change the text data type from varchar to varchar2 in the JDBC adapte…
  docs/schema.md
  src/integration-test/java/com/scalar/db/storage/jdbc/test/TestEnv.java
  tools/scalar-schema/README.md
  tools/scalar-schema/src/scalar_schema/jdbc.clj
Labels: improvement

#183 Add support for endpoint_override in Schema Tool for DynamoDB
  tools/scalar-schema/src/scalar_schema/core.clj
  tools/scalar-schema/src/scalar_schema/dynamo.clj
  tools/scalar-schema/src/scalar_schema/dynamo/auto_scaling.clj
Labels: improvement

#184 Unify the behavior with -D (deleting all tables) in Schema Tool
  tools/scalar-schema/src/scalar_schema/jdbc.clj
  tools/scalar-schema/src/scalar_schema/operations.clj
Labels: improvement

#188 Refactor Scalar Schema tool for more consistency
  tools/scalar-schema/src/scalar_schema/cassandra.clj
  tools/scalar-schema/src/scalar_schema/jdbc.clj
Labels: improvement

#191 Use "FETCH FIRST n ROWS ONLY" instead of ROWNUM for LIMIT for Oracle
  src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java
  src/main/java/com/scalar/db/storage/jdbc/query/SelectWithFetchFirstNRowsOnly.java
  src/main/java/com/scalar/db/storage/jdbc/query/SelectWithRowNumQuery.java
  src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
Labels: improvement

#189 make attributes for secondary indexes
  tools/scalar-schema/src/scalar_schema/dynamo.clj
Labels: bugfix

#192 Add a validation that checks not to use BOOLEAN type for a clustering…
  tools/scalar-schema/src/scalar_schema/dynamo.clj
Labels: improvement

#190 Add integration test for Oracle to CI
  .circleci/config.yml
Labels: improvement
