Repository scalar-labs/scalardb, pull requests merged in 2021-08, with the labels that each got.

#260 Disable Prometheus HTTP endpoint when the port is specified to zero in Scalar DB server
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitWithDistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithJdbcTransactionIntegrationTest.java
  server/src/main/java/com/scalar/db/server/service/ServerModule.java
Labels: improvement

#262 Introduce Spotbugs plugin
  .circleci/config.yml
  build.gradle
  core/build.gradle
  core/src/integration-test/java/com/scalar/db/storage/jdbc/test/TestEnv.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithMultiStorageIntegrationTest.java
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cassandra/ClusterManager.java
  core/src/main/java/com/scalar/db/storage/cosmos/ConcatenationVisitor.java
  core/src/main/java/com/scalar/db/storage/cosmos/Record.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/PartitionedMutations.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/SerializableStrategy.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/util/ImmutableLinkedHashSet.java
  core/src/test/java/com/scalar/db/api/GetTest.java
  core/src/test/java/com/scalar/db/api/PutTest.java
  core/src/test/java/com/scalar/db/io/BigIntValueTest.java
  core/src/test/java/com/scalar/db/io/BlobValueTest.java
  core/src/test/java/com/scalar/db/io/BooleanValueTest.java
  core/src/test/java/com/scalar/db/io/DoubleValueTest.java
  core/src/test/java/com/scalar/db/io/FloatValueTest.java
  core/src/test/java/com/scalar/db/io/IntValueTest.java
  core/src/test/java/com/scalar/db/io/KeyTest.java
  core/src/test/java/com/scalar/db/io/TextValueTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/BatchComposerTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/ClusterManagerTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/ResultInterpreterTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/ValueBinderTest.java
  core/src/test/java/com/scalar/db/storage/common/ResultImplTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/ConcatenationVisitorTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/MapVisitorTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/ResultInterpreterTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DeleteStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/ItemSorterTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/MapVisitorTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/PutStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/ResultInterpreterTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/ResultInterpreterTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  server/build.gradle
  server/src/main/java/com/scalar/db/server/ScalarDbServer.java
  server/src/main/java/com/scalar/db/server/config/ServerConfig.java
Labels: improvement

#259 Implement addition and deletion of metadata table for jdbc metadata manager
  core/src/main/java/com/scalar/db/api/TableMetadata.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraTableMetadataManager.java
  core/src/main/java/com/scalar/db/storage/common/TableMetadataManager.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosTableMetadataManager.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoTableMetadataManager.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcTableMetadataManager.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcTableMetadataManager.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcTableMetadataManagerTest.java
Labels: enhancement

#264 Use column name alias for projection expressions in the DynamoDB adapter
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoWithReservedKeywordIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
Labels: bugfix

#265 Add useful constructors to Key with a single value
  core/src/main/java/com/scalar/db/api/Put.java
  core/src/main/java/com/scalar/db/io/BlobValue.java
  core/src/main/java/com/scalar/db/io/Key.java
  core/src/main/java/com/scalar/db/io/TextValue.java
  core/src/main/java/com/scalar/db/io/Value.java
  core/src/test/java/com/scalar/db/io/KeyTest.java
Labels: enhancement

#266 add scalar-schema dockerfile
  tools/scalar-schema/Dockerfile
Labels: enhancement

#269 Add integration test for JDBC SqlServer to the CI configuration
  .circleci/config.yml
Labels: enhancement

#272 Rename the integrationTest source set to integrationTestAll
  core/build.gradle
  server/build.gradle
Labels: improvement

#273 Add publishToMavenLocal for archiving and uploading to maven central
  core/build.gradle
  rpc/build.gradle
  server/build.gradle
Labels: improvement

#275 Reduce the Cassandra heap size for the multi-storage integration test
  .circleci/config.yml
Labels: improvement

#274 Refactor Prometheus exporter
  docs/scalardb-server.md
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitWithDistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithJdbcTransactionIntegrationTest.java
  server/src/main/java/com/scalar/db/server/config/ServerConfig.java
  server/src/main/java/com/scalar/db/server/service/ServerModule.java
  server/src/test/java/com/scalar/db/server/config/ServerConfigTest.java
Labels: improvement

#270 Add create, truncate and delete table implementation to JDBCAdmin
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/test/TestEnv.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithJdbcDatabaseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithMultiStorageIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionIntegrationTest.java
  core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraTableMetadataManager.java
  core/src/main/java/com/scalar/db/storage/common/TableMetadataManager.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosTableMetadataManager.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoTableMetadataManager.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcTableMetadataManager.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcTableMetadataManager.java
  core/src/main/java/com/scalar/db/util/Utility.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdminTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcTableMetadataManagerTest.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitWithDistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithJdbcTransactionIntegrationTest.java
Labels: enhancement

#276 Introduce factory classes to instantiate storage and transaction
  core/src/main/java/com/scalar/db/api/DistributedStorage.java
  core/src/main/java/com/scalar/db/service/StorageFactory.java
  core/src/main/java/com/scalar/db/service/TransactionFactory.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorage.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  server/src/main/java/com/scalar/db/server/service/ServerModule.java
Labels: enhancement

#277 Rename metrics names of Scalar DB server
  server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java
  server/src/main/java/com/scalar/db/server/DistributedStorageService.java
  server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
  server/src/main/java/com/scalar/db/server/Metrics.java
  server/src/main/java/com/scalar/db/server/service/ServerModule.java
Labels: improvement

#279 Fix optimization warnings
  rpc/build.gradle
Labels: improvement

#281 Add a new createTable() method without any options to DistributedStorageAdmin
  core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java
Labels: improvement

#278 Add create, truncate and delete table implementation to Cassandra Admin
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraTableMetadataManager.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTest.java
Labels: enhancement

#292 Use Cassandra Admin in MultiStorage integration test
  .circleci/config.yml
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithMultiStorageIntegrationTest.java
Labels: improvement

#290 Finalize Cosmos DB Admin implementation
  core/src/integration-test/java/com/scalar/db/storage/IntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCosmosIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosTableMetadata.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosTableMetadataManager.java
  core/src/main/resources/cosmosdb_stored_procedure/mutate.js
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosTableMetadataManagerTest.java
Labels: improvement

#293 Rename CassandraAdmin network-strategy to replication-strategy
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTest.java
Labels: improvement

#291 Introduce GateKeeper that manages the front gate of the server that processes requests
  server/src/main/java/com/scalar/db/server/AdminService.java
  server/src/main/java/com/scalar/db/server/DistributedStorageService.java
  server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
  server/src/main/java/com/scalar/db/server/GateKeeper.java
  server/src/main/java/com/scalar/db/server/LockFreeGateKeeper.java
  server/src/main/java/com/scalar/db/server/Pauser.java
  server/src/main/java/com/scalar/db/server/SynchronizedGateKeeper.java
  server/src/main/java/com/scalar/db/server/config/ServerConfig.java
  server/src/main/java/com/scalar/db/server/service/ServerModule.java
  server/src/test/java/com/scalar/db/server/DistributedStorageServiceTest.java
  server/src/test/java/com/scalar/db/server/DistributedTransactionServiceTest.java
  server/src/test/java/com/scalar/db/server/config/ServerConfigTest.java
Labels: improvement
