Repository scalar-labs/scalardb, pull requests merged in 2021-02, with the labels that each got.

#151 Fix snapshot scan bug
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTest.java
  src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
  src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
Labels: bugfix

#154 Fix to set RU for DynamoDB
  tools/scalar-schema/src/scalar_schema/dynamo/auto_scaling.clj
Labels: bugfix

#156 Add a guide on the requirements in the underlining databases of Scalar DB
  docs/getting-started-with-scalardb.md
  docs/requirements.md
Labels: documentation

#155 Add documentation for the JDBC adapter
  docs/getting-started-with-scalardb-on-cassandra.md
  docs/getting-started-with-scalardb-on-cosmosdb.md
  docs/getting-started-with-scalardb-on-dynamodb.md
  docs/getting-started-with-scalardb-on-jdbc.md
  docs/getting-started-with-scalardb.md
  docs/getting-started.md
  docs/getting-started/scalardb.properties
  docs/getting-started/src/main/java/sample/ElectronicMoney.java
  docs/getting-started/src/main/java/sample/ElectronicMoneyWithTransaction.java
Labels: enhancement

#157 Add the backup documentation for JDBC databases
  docs/backup-restore.md
Labels: documentation

#159 Enable dynamo backup
  tools/scalar-schema/src/scalar_schema/core.clj
  tools/scalar-schema/src/scalar_schema/dynamo.clj
  tools/scalar-schema/src/scalar_schema/dynamo/continuous_backup.clj
Labels: enhancement

#158 Add documentation of requirements in the underlining databases of Sca…
  docs/getting-started-with-scalardb-on-jdbc.md
  docs/requirements.md
Labels: documentation

#160 Label correction for Cosmos DB credential
  docs/getting-started-with-scalardb-on-cosmosdb.md
  docs/getting-started-with-scalardb.md
  tools/scalar-schema/README.md
Labels: improvement

#163 Schema deletion commands modified in getting started doc
  docs/getting-started-with-scalardb.md
Labels: bugfix

#164 Minor word correction in getting started with cassandra doc
  docs/getting-started-with-scalardb-on-cassandra.md
Labels: bugfix

#165 Fix not to return unexpected results
  src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
Labels: bugfix

#161 Remove prefix from indexes of DynamoDB
  src/main/java/com/scalar/db/api/Operation.java
  src/main/java/com/scalar/db/storage/dynamo/DynamoOperation.java
  tools/scalar-schema/src/scalar_schema/common.clj
  tools/scalar-schema/src/scalar_schema/core.clj
  tools/scalar-schema/src/scalar_schema/dynamo/common.clj
Labels: bugfix

#162 Add more documentation including limitations in the Scalar DB docs
  src/main/java/com/scalar/db/api/DistributedStorage.java
  src/main/java/com/scalar/db/api/DistributedTransaction.java
  src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  src/main/java/com/scalar/db/transaction/consensuscommit/SerializableStrategy.java
Labels: documentation

#152 Support table creation of Scalar DB on JDBC in schema-tool
  tools/scalar-schema/README.md
  tools/scalar-schema/project.clj
  tools/scalar-schema/src/scalar_schema/core.clj
  tools/scalar-schema/src/scalar_schema/jdbc.clj
  tools/scalar-schema/src/scalar_schema/operations.clj
Labels: enhancement
