Repository scalar-labs/scalardb, pull requests merged in 2021-12, with the labels that each got.

#391 Introduce prometheus simpleclient_hotspot
  build.gradle
  server/build.gradle
  server/src/main/java/com/scalar/db/server/Metrics.java
Labels: improvement

#366 Add supporting schema creation/deletion can be called from program
  schema-loader/README.md
  schema-loader/archive.gradle
  schema-loader/build.gradle
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoaderException.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/CassandraCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/CosmosCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/DynamoCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/JdbcCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/StorageSpecificCommandBase.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/core/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/core/SchemaOperatorFactory.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/schema/SchemaParser.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/util/either/Either.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/util/either/Left.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/util/either/Right.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaLoaderTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/CassandraCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/CommandTestBase.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/CosmosCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/DynamoCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/JdbcCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/SchemaLoaderCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/core/SchemaOperatorTest.java
Labels: enhancement

#395 Modify Dockerfile to run as non-root
  server/Dockerfile
Labels: improvement

#397 Reduce integration test concurrency
  core/build.gradle
  core/src/integration-test/java/com/scalar/db/storage/StorageMultipleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageMultiplePartitionKeyIntegrationTestBase.java
Labels: improvement

#394 Add some more admin integration tests
  core/src/integration-test/java/com/scalar/db/storage/AdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
Labels: improvement

#399 Adjust integration test concurrency
  core/build.gradle
  core/src/integration-test/java/com/scalar/db/storage/StorageMultipleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageMultiplePartitionKeyIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcMultiplePartitionKeyIntegrationTest.java
Labels: improvement

#400 Reduce Intellij warnings
  build.gradle
  core/src/test/java/com/scalar/db/storage/cosmos/ConcatenationVisitorTest.java
Labels: improvement

#401 Should add a suffix to the metadata table name in DynamoWithReservedKeywordIntegrationTest
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoWithReservedKeywordIntegrationTest.java
Labels: bugfix

#402 Small fix for release.yaml
  .github/workflows/release.yaml
Labels: improvement

#403 Update the Scalar DB version in README
  README.md
  docs/index.md
Labels: documentation

#406 Add mergeServiceFiles for shadowJar in Schema Loader
  schema-loader/build.gradle
Labels: bugfix

#405 Refactor DistributedStorageAdmin
  core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
Labels: improvement

#411 Move ReadRepairableExecutionException to the Cassandra package
  core/src/main/java/com/scalar/db/storage/cassandra/MutateStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cassandra/ReadRepairableExecutionException.java
  core/src/test/java/com/scalar/db/storage/cassandra/InsertStatementHandlerTest.java
Labels: improvement

#407 Throw RetriableExecutionException when TransactionConflict happens in the Dynamo adapter
  core/src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/DeleteStatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/PutStatementHandler.java
  core/src/test/java/com/scalar/db/storage/dynamo/BatchHandlerTest.java
Labels: improvement

#408 Throw RetriableExecutionException in mutate operations when conflicts happen in the JDBC adapter
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
Labels: improvement

#409 Handle RetriableExecutionException in ConsensusCommit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
Labels: improvement

#404 Move Isolation to the consensuscommit package
  conf/database.properties
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
  core/src/main/java/com/scalar/db/api/Isolation.java
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Isolation.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
  server/conf/database.properties.tmpl
  server/src/integration-test/java/com/scalar/db/server/ServerEnv.java
Labels: improvement

#410 Result.getClusteringKey() should return empty when there is no clustering key
  core/src/main/java/com/scalar/db/storage/common/ResultImpl.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
Labels: improvement

#415 Fix get tables in Dynamo adapter when actual number of tables exceed the maximum in a response.
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
Labels: bugfix

#413 Update schema-loader javadoc to fix warning
  README.md
  docs/index.md
  schema-loader/build.gradle
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/core/SchemaOperatorFactory.java
Labels: documentation

#417 Restore JdbcUtils.initDataSource(JdbcConfig config)
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
Labels: bugfix

#420 Use the internal JRE Docker image to avoid CVE fixing commands
  schema-loader/Dockerfile
  server/Dockerfile
Labels: improvement

#419 Revisit logging in Consensus Commit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
Labels: improvement

#418 Remove synchronized from ConsensusCommitManager
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
Labels: improvement

#416 Upgrade supported storage database version in the CI
  .circleci/config.yml
Labels: improvement

#421 Log in GitHub Container Registry first
  .github/workflows/release.yaml
Labels: bugfix

#423 Refactor OperationChecker
  core/src/main/java/com/scalar/db/storage/common/checker/ColumnChecker.java
  core/src/main/java/com/scalar/db/storage/common/checker/ConditionChecker.java
  core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
Labels: improvement

#426 Add `SCALAR_DB_SERVER_PORT` to database.properties.tmpl
  server/conf/database.properties.tmpl
Labels: improvement

#425 Rename utility classes for consistency
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorage.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcScanOnBidirectionalStream.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransaction.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStream.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionOnBidirectionalStream.java
  core/src/main/java/com/scalar/db/util/ProtoUtils.java
  core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
  core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
  server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java
  server/src/main/java/com/scalar/db/server/DistributedStorageService.java
  server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
  server/src/main/java/com/scalar/db/server/TwoPhaseCommitTransactionService.java
  server/src/test/java/com/scalar/db/server/DistributedStorageAdminServiceTest.java
  server/src/test/java/com/scalar/db/server/DistributedStorageServiceTest.java
Labels: improvement

#429 Upgrade log4j version
  build.gradle
Labels: improvement

#433 Update the Scalar DB version of the dependency in README
  README.md
  docs/index.md
Labels: documentation

#428 Filter transactional columns and support projection for get/scan in Consensus Commit
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/main/java/com/scalar/db/storage/common/ResultImpl.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/FilteredResult.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtilsTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/FilteredResultTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
Labels: improvement

#431 Use different datasource for table metadata in JDBC adapter
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcUtilsTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
  docs/getting-started-with-scalardb-on-jdbc.md
Labels: improvement

#432 Improve Getting Started with Scalar DB on X
  docs/getting-started-with-scalardb-on-cassandra.md
  docs/getting-started-with-scalardb-on-cosmosdb.md
  docs/getting-started-with-scalardb-on-dynamodb.md
Labels: documentation

#430 Remove TransactionRuntimeException
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
  core/src/main/java/com/scalar/db/exception/transaction/CrudRuntimeException.java
  core/src/main/java/com/scalar/db/exception/transaction/RequiredValueMissingException.java
  core/src/main/java/com/scalar/db/exception/transaction/TransactionRuntimeException.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitIntegrationTest.java
Labels: improvement

#434 Move CoordinatorException to the consensuscommit package
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CoordinatorException.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/RecoveryHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
Labels: improvement

#436 Upgrade log4j to 2.17.0
  build.gradle
Labels: improvement

#437 Add gRPC deadline duration configuration to the Scalar DB Server documentation
  docs/scalardb-server.md
Labels: documentation

#440 Add -u option for Cosmos DB in schema loader for backward compatibility
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/CosmosCommand.java
Labels: bugfix

#438 Support parallel preparation/commit/rollback in Consensus Commit
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/RecoveryHandlerTest.java
Labels: enhancement

#349 Add end-to-end test for schema loader to CI
  .circleci/config.yml
  build.gradle
  schema-loader/build.gradle
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/cassandra/CassandraSchemaLoaderIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/cassandra/CassandraSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/cosmos/CosmosSchemaLoaderIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/cosmos/CosmosSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/dynamo/DynamoSchemaLoaderIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/dynamo/DynamoSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/jdbc/JdbcSchemaLoaderIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/jdbc/JdbcSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/multistorage/MultiStorageSchemaLoaderIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/server/SchemaLoaderWithScalarDbServer.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/CosmosCommand.java
  server/build.gradle
Labels: improvement

#442 Refactor integration tests
  core/src/integration-test/java/com/scalar/db/storage/AdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageColumnValueIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageMultipleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageMultiplePartitionKeyIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageSecondaryIndexIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageSingleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageSinglePartitionKeyIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosColumnValueIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSecondaryIndexIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSinglePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCosmosIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithMultiStorageIntegrationTest.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/CosmosCommand.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/ServerEnv.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitWithExtraReadIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitWithExtraWriteIntegrationTest.java
Labels: improvement

#446 Update the Getting Started doc and code
  docs/getting-started-with-scalardb.md
  docs/getting-started/src/main/java/sample/ElectronicMoneyWithTransaction.java
Labels: documentation
