Repository scalar-labs/scalardb, pull requests merged in 2021-09, with the labels that each got.

#294 Separate consensus commit related config from DatabaseConfig
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCosmosIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithDynamoIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithJdbcDatabaseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithMultiStorageIntegrationTest.java
  core/src/main/java/com/scalar/db/api/SerializableStrategy.java
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/service/TransactionModule.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitWithDistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java
Labels: improvement

#295 Add tests for getState() and abort() in DistributedTransactionManager to the ConsensusCommit integration test
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
Labels: improvement

#296 Update MultiStorageAdmin with new interface
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTest.java
Labels: improvement

#298 Fix CVE-2021-3711
  server/Dockerfile
Labels: improvement

#299 Add Two-phase Consensus Commit
  .circleci/config.yml
  core/build.gradle
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/exception/transaction/PreparationConflictException.java
  core/src/main/java/com/scalar/db/exception/transaction/PreparationException.java
  core/src/main/java/com/scalar/db/exception/transaction/RollbackException.java
  core/src/main/java/com/scalar/db/exception/transaction/ValidationConflictException.java
  core/src/main/java/com/scalar/db/exception/transaction/ValidationException.java
  core/src/main/java/com/scalar/db/service/TransactionFactory.java
  core/src/main/java/com/scalar/db/service/TransactionModule.java
  core/src/main/java/com/scalar/db/service/TwoPhaseCommitTransactionService.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/util/ActiveExpiringMap.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
Labels: enhancement

#300 Update Scalar DB Server Sample URL
  docs/scalardb-server.md
Labels: documentation

#305 Remove unchecked warnings
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
Labels: improvement

#306 Fix typos
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java
Labels: improvement

#307 Fix Javadoc related things
  build.gradle
  core/build.gradle
  rpc/build.gradle
  server/build.gradle
Labels: improvement

#308 Upgrade the Error Prone plugin
  build.gradle
Labels: improvement

#309 Add Javadoc for DistributedStorageAdmin
  core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java
Labels: improvement

#310 Change service name of TwoPhaseCommitTransactionService
  server/src/main/java/com/scalar/db/server/TwoPhaseCommitTransactionService.java
Labels: improvement

#301 Implementation of Dynamo Admin module
  core/build.gradle
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoTableMetadataManager.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoTableMetadataManagerTest.java
Labels: enhancement

#303 Add documentation for Two-phase Commit Transactions
  README.md
  conf/database.properties
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java
  docs/getting-started-with-scalardb.md
  docs/two-phase-commit-transactions.md
Labels: documentation

#311 Refactor CassandraAdmin and CosmosAdmin
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCosmosIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosTableMetadataManager.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
Labels: improvement

#313 Fixed broken link.
  docs/two-phase-commit-transactions.md
Labels: bugfix

#314 Add ConsensusCommitAdmin that manages transactional tables and coordinator table
  core/src/main/java/com/scalar/db/api/TableMetadata.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTest.java
Labels: enhancement

#315 Remove metadata from Coordinator
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Attribute.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
Labels: improvement

#318 Refactoring dynamo integration tests
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoWithReservedKeywordIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithDynamoIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoTableMetadataManager.java
Labels: improvement

#320 Make Coordinator namespace name configurable
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCassandraIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCosmosIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithDynamoIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithJdbcDatabaseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithMultiStorageIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorTest.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitWithDistributedStorageServiceIntegrationTest.java
Labels: enhancement

#322 Make table metadata database name configurable in Cosmos DB adapter
  .circleci/config.yml
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithCosmosIntegrationTest.java
  core/src/main/java/com/scalar/db/service/StorageModule.java
  core/src/main/java/com/scalar/db/service/TransactionModule.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosConfigTest.java
Labels: enhancement

#323 Make table metadata namespace name configurable in DynamoDB adapter
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoConfigTest.java
Labels: enhancement

#324 Make table metadata schema name configurable in JDBC adapter
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdminTest.java
Labels: enhancement
