Repository scalar-labs/scalardb, pull requests merged in 2021-11, with the labels that each got.

#362 Change libssl and openssl versions in Dockerfile in scalar-schema
  tools/scalar-schema/Dockerfile
Labels: improvement

#350 Add dockerizing for the schema-loader
  schema-loader/Dockerfile
  schema-loader/README.md
  schema-loader/build.gradle
Labels: improvement

#361 Change the default values of JDBC connection pool configurations
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
Labels: improvement

#363 Add Schema loader things to the release action
  .github/workflows/release.yaml
Labels: enhancement

#364 Refactor documentation
  README.md
  docs/getting-started-with-scalardb.md
  docs/index.md
  docs/multi-storage-transactions.md
  docs/scalardb-server.md
  docs/scalardb-supported-databases.md
  mkdocs.yml
Labels: documentation

#352 Update documents that are related to schema loader
  docs/getting-started-with-scalardb.md
  docs/schema.md
Labels: documentation

#365 Improve Multi-storage documentation
  docs/multi-storage-transactions.md
Labels: documentation

#368 Improve Schema loader document
  schema-loader/README.md
Labels: documentation

#367 Add ConsensusCommitUtils
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtilsTest.java
Labels: enhancement

#372 Refactor XXXConfig classes
  core/src/main/java/com/scalar/db/config/ConfigUtils.java
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/util/Utility.java
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
  server/src/main/java/com/scalar/db/server/config/ServerConfig.java
  server/src/test/java/com/scalar/db/server/config/ServerConfigTest.java
Labels: improvement

#370 Add null or empty check for partition key and clustering key
  core/src/main/java/com/scalar/db/storage/common/checker/ColumnChecker.java
  core/src/main/java/com/scalar/db/storage/common/checker/ConditionChecker.java
  core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
  core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
Labels: improvement

#373 Remove UnsupportedTypeException
  core/src/main/java/com/scalar/db/exception/storage/UnsupportedTypeException.java
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cassandra/ResultInterpreter.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/ItemSorter.java
  core/src/main/java/com/scalar/db/storage/dynamo/ResultInterpreter.java
  core/src/test/java/com/scalar/db/storage/cassandra/ResultInterpreterTest.java
Labels: improvement

#369 Add KeyBytesEncoder that converts a key to bytes while preserving the sort order
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/BigIntBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/BlobBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/BooleanBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/BytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/BytesEncoders.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/BytesUtils.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/DoubleBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/FloatBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/IntBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/KeyBytesEncodedLengthCalculator.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/KeyBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/TextBytesEncoder.java
  core/src/test/java/com/scalar/db/storage/dynamo/bytes/KeyBytesEncoderTest.java
Labels: enhancement

#374 Allow empty value for partition key and clustering key
  core/src/main/java/com/scalar/db/storage/common/checker/ColumnChecker.java
  core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
Labels: improvement

#377 Fix hashCode() in XXXValue and Key classes
  core/src/main/java/com/scalar/db/io/BigIntValue.java
  core/src/main/java/com/scalar/db/io/BlobValue.java
  core/src/main/java/com/scalar/db/io/BooleanValue.java
  core/src/main/java/com/scalar/db/io/DoubleValue.java
  core/src/main/java/com/scalar/db/io/FloatValue.java
  core/src/main/java/com/scalar/db/io/IntValue.java
  core/src/main/java/com/scalar/db/io/Key.java
  core/src/main/java/com/scalar/db/io/TextValue.java
Labels: bugfix

#376 Add dockerize to Dockerfile for grpc-server
  server/Dockerfile
  server/README.md
  server/build.gradle
  server/conf/database.properties.tmpl
Labels: improvement

#380 Add more tests to the multiple clustering key integration test
  core/src/integration-test/java/com/scalar/db/storage/StorageMultipleClusteringKeysIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeysIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoMultipleClusteringKeysIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcMultipleClusteringKeysIntegrationTest.java
  core/src/main/java/com/scalar/db/io/BlobValue.java
  core/src/main/java/com/scalar/db/storage/jdbc/ResultInterpreter.java
  core/src/test/java/com/scalar/db/storage/jdbc/ResultInterpreterTest.java
Labels: improvement

#378 Add clustering order support to JDBC adapter
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdmin.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseAdminTest.java
Labels: enhancement

#382 Refactor CosmosAdmin
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeysIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
Labels: improvement

#381 Disallow empty values for Partition key and Clustering key
  core/src/main/java/com/scalar/db/storage/common/checker/ColumnChecker.java
  core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
Labels: improvement

#375 DynamoDB sort key optimization
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoMultipleClusteringKeysIntegrationTest.java
  core/src/main/java/com/scalar/db/api/TableMetadata.java
  core/src/main/java/com/scalar/db/storage/cosmos/ConcatenationVisitor.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoOperation.java
  core/src/main/java/com/scalar/db/storage/dynamo/ItemSorter.java
  core/src/main/java/com/scalar/db/storage/dynamo/MapVisitor.java
  core/src/main/java/com/scalar/db/storage/dynamo/PutStatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/ValueBinder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/BytesUtils.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoOperationTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/ItemSorterTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/bytes/BytesUtilsTest.java
Labels: improvement

#386 Add single clustering key scan integration test
  core/src/integration-test/java/com/scalar/db/storage/StorageMultipleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageSingleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/TestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraMultipleClusteringKeysIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcTestUtils.java
Labels: improvement

#387 Add column value integration test
  core/src/integration-test/java/com/scalar/db/storage/StorageColumnValueIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraColumnValueIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosColumnValueIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoColumnValueIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcColumnValueIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/cosmos/ResultInterpreter.java
Labels: improvement

#389 Add secondary index integration test
  core/src/integration-test/java/com/scalar/db/storage/StorageSecondaryIndexIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSecondaryIndexIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSecondaryIndexIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSecondaryIndexIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSecondaryIndexIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
  core/src/main/java/com/scalar/db/storage/cosmos/ValueBinder.java
Labels: improvement

#388 Add partition key integration tests
  .circleci/config.yml
  core/src/integration-test/java/com/scalar/db/storage/StorageMultiplePartitionKeyIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageSinglePartitionKeyIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSinglePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSinglePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSinglePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSinglePartitionKeyIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/cosmos/ConcatenationVisitor.java
  core/src/test/java/com/scalar/db/storage/cosmos/ConcatenationVisitorTest.java
Labels: improvement

#384 Add syntax highlighting for the dependency in README.md
  README.md
Labels: improvement

#390 Run integration tests concurrently
  .circleci/config.yml
  core/build.gradle
  core/src/integration-test/java/com/scalar/db/storage/AdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageColumnValueIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageMultipleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageMultiplePartitionKeyIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageSecondaryIndexIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageSingleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageSinglePartitionKeyIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/TestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoWithReservedKeywordIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionIntegrationTest.java
Labels: improvement

#385 Add clustering order support to Dynamo adapter
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
Labels: enhancement

#344 GraphQL schema generation from database tables
  build.gradle
  graphql/build.gradle
  graphql/src/main/java/com/scalar/db/graphql/GraphQlFactory.java
  graphql/src/main/java/com/scalar/db/graphql/schema/CommonSchema.java
  graphql/src/main/java/com/scalar/db/graphql/schema/Constants.java
  graphql/src/main/java/com/scalar/db/graphql/schema/DeleteConditionType.java
  graphql/src/main/java/com/scalar/db/graphql/schema/PutConditionType.java
  graphql/src/main/java/com/scalar/db/graphql/schema/SchemaUtils.java
  graphql/src/main/java/com/scalar/db/graphql/schema/TableGraphQlModel.java
  graphql/src/test/java/com/scalar/db/graphql/GraphQlFactoryTest.java
  graphql/src/test/java/com/scalar/db/graphql/schema/SchemaUtilsTest.java
  graphql/src/test/java/com/scalar/db/graphql/schema/TableGraphQlModelTest.java
  settings.gradle
Labels: enhancement

#392 Add -XX:MaxRAMPercentage parameter to SCALARDB_SERVER_OPTS
  server/Dockerfile
  server/build.gradle
  server/docker-entrypoint.sh
Labels: improvement
