Repository scalar-labs/scalardb, pull requests merged in 2022-09, with the labels that each got.

#674 Add method to retrieve the namespace names for the Jdbc Admin
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/util/JdbcAdminTestUtils.java
  core/src/main/java/com/scalar/db/api/Admin.java
  core/src/main/java/com/scalar/db/service/AdminService.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdmin.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionAdmin.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminWithMetadataSchemaConfigTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java
  core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTest.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcAdminTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionAdminTest.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageAdminGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionAdminGrpc.java
  rpc/src/main/java/com/scalar/db/rpc/GetNamespaceNamesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/GetNamespaceNamesRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/GetNamespaceNamesResponse.java
  rpc/src/main/java/com/scalar/db/rpc/GetNamespaceNamesResponseOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java
  rpc/src/main/proto/scalardb.proto
  server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java
  server/src/main/java/com/scalar/db/server/DistributedTransactionAdminService.java
Labels: enhancement

#682 Delete setDriver() for BasicDataSource in JDBC
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcUtilsTest.java
Labels: improvement

#684 Use DistributedTransactionAdmin for transaction tables in SchemaOperator
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
Labels: improvement

#685 Fix Javadoc warnings
  core/src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
Labels: documentation

#686 Delete licenses
  core/src/main/resources/META-INF/COPYING
  core/src/main/resources/META-INF/NOTICE
  licenses/APL-2.0.txt
  licenses/EPL-1.0-junit4.txt
  licenses/MIT-mockito.txt
  licenses/MIT-participle.txt
  licenses/MIT-slf4j.txt
  licenses/README.md
Labels: improvement

#683 Suppress exception thrown when deleting scalable target and scaling policy when using DynamoDB local.
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
Labels: improvement

#688 Update Scalar DB version dependency
  README.md
  docs/getting-started/build.gradle
  docs/index.md
Labels: documentation

#690 Should support `--config=` and `-c=` styles for configuration file option in Schema Loader
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
Labels: bugfix

#691 Update bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: improvement

#678 Add method to retrieve the namespace names for Cosmos Admin
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/util/CosmosAdminTestUtils.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosNamespace.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminWithMetadataDatabaseConfigTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosConfigTest.java
Labels: enhancement (backward-incompatible)

#679 Add method to retrieve the namespace names for the Dynamo Admin
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/util/DynamoAdminTestUtils.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminWithDefaultConfigTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminWithNamespacePrefixAndMetadataNamespaceConfigTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminWithNamespacePrefixConfigTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoConfigTest.java
Labels: enhancement (backward-incompatible)

#687 Add method to retrieve the namespace names for Cassandra Admin
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraConfig.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminWithDefaultConfigTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminWithMetadataKeyspaceConfigTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraConfigTest.java
Labels: enhancement (backward-incompatible)

#694 Upgrade Spotless Gradle Plugin
  build.gradle
Labels: improvement

#693 Update JdbcAdmin.namespaceExists()
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
Labels: enhancement (backward-incompatible)

#695 Fix typo in admin integration test classes
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
Labels: improvement

#699 Update release workflow to push container to ECR of Marketplace
  .github/workflows/release.yaml
Labels: enhancement

#700 Fix CVE-2021-3999, CVE-2022-1586 and CVE-2022-1587
  schema-loader/Dockerfile
  server/Dockerfile
Labels: bugfix

#680 Commit/rollback records should always be done for all records even on error
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ParallelExecutorTest.java
Labels: bugfix

#702 Make the ConsensusCommitAdmin only return transaction table
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTest.java
Labels: improvement

#701 Add external Scalar DB property file support to getting-started application
  docs/getting-started/src/main/java/sample/ElectronicMoney.java
  docs/getting-started/src/main/java/sample/ElectronicMoneyMain.java
Labels: improvement

#703 Update the Scalar DB supported database matrix with Scalar DB 3.7
  docs/scalardb-supported-databases.md
Labels: documentation

#696 Add upgrade method to jdbc admin
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminIntegrationTest.java
  core/src/main/java/com/scalar/db/api/Admin.java
  core/src/main/java/com/scalar/db/service/AdminService.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdmin.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionAdmin.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTest.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcAdminTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionAdminTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/util/AdminTestUtils.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageAdminGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionAdminGrpc.java
  rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java
  rpc/src/main/java/com/scalar/db/rpc/UpgradeRequest.java
  rpc/src/main/java/com/scalar/db/rpc/UpgradeRequestOrBuilder.java
  rpc/src/main/proto/scalardb.proto
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithDistributedTransactionAdminService.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/ServerAdminTestUtils.java
  server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java
  server/src/main/java/com/scalar/db/server/DistributedTransactionAdminService.java
  server/src/test/java/com/scalar/db/server/DistributedStorageAdminServiceTest.java
  server/src/test/java/com/scalar/db/server/DistributedTransactionAdminServiceTest.java
Labels: enhancement (backward-incompatible)

#704 Refactor ConsensusCommitAdmin unit test
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminWithCoordinatorNamespaceConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminWithDefaultConfigTest.java
Labels: improvement

#681 Should use partition key and clustering key from result in recovery
  core/src/main/java/com/scalar/db/transaction/consensuscommit/AbstractMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/MutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/RecoveryHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposerTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Labels: bugfix

#705 In the Cosmos DB job of the CI, add a step to clean up gradle daemon logs file
  .github/workflows/ci.yaml
Labels: improvement

#707 Add upgrade() method to the Cosmos Admin
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminTestUtils.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
Labels: enhancement (backward-incompatible)

#708 Add upgrade() method to the Dynamo Admin
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminTestUtils.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
Labels: enhancement (backward-incompatible)

#710 Refactor XXXConfig classes
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
Labels: improvement

#709 Add upgrade() method to the Cassandra Admin
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTestUtils.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTestBase.java
Labels: enhancement (backward-incompatible)

#711 Disable include metadata tests if external server used in server integration tests
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithDistributedTransactionAdminService.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithDistributedTransactionService.java
  server/src/integration-test/java/com/scalar/db/server/ServerEnv.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithTwoPhaseCommitTransactionService.java
Labels: improvement

#712 Refactor two-phase commit transaction integration tests
  core/src/integration-test/java/com/scalar/db/storage/cassandra/TwoPhaseConsensusCommitIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/TwoPhaseConsensusCommitIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/TwoPhaseConsensusCommitIntegrationTestWithJdbcDatabase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTestBase.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithTwoPhaseCommitTransactionService.java
Labels: improvement

#713 Refactor consensus commit specific integration tests
  core/src/integration-test/java/com/scalar/db/storage/cassandra/TwoPhaseConsensusCommitSpecificIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitSpecificIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/TwoPhaseConsensusCommitSpecificIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/TwoPhaseConsensusCommitSpecificIntegrationTestWithJdbcDatabase.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
Labels: improvement

#714 Fix typos in exception messages
  core/src/main/java/com/scalar/db/api/TableMetadata.java
Labels: improvement

#716 Fix CVE-2022-27664
  server/Dockerfile
Labels: bugfix
