Repository scalar-labs/scalardb, pull requests merged in 2022-07, with the labels that each got.

#619 Add Scanner paging support for scan operations to the Cosmos adapter
  core/src/main/java/com/scalar/db/storage/common/EmptyScanner.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/cosmos/DeleteStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/MutateStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/PutStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/ScannerImpl.java
  core/src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/SingleRecordScanner.java
  core/src/main/java/com/scalar/db/storage/cosmos/StatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  core/src/test/java/com/scalar/db/storage/cosmos/ScannerImplTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/SingleRecordScannerTest.java
Labels: improvement

#621 Add documentation for Consensus Commit configurations
  README.md
  conf/database.properties
  docs/configurations-for-consensus-commit.md
  docs/design.md
  docs/getting-started-with-scalardb-on-dynamodb.md
  docs/getting-started-with-scalardb-on-jdbc.md
  docs/index.md
  docs/multi-storage-transactions.md
  docs/scalardb-server.md
  docs/two-phase-commit-transactions.md
  server/conf/database.properties.tmpl
Labels: documentation

#623 Fix CVE-2022-2068
  schema-loader/Dockerfile
  server/Dockerfile
Labels: improvement

#624 Remove non useful operation in ScannerImpl from the Cosmos DB adapter
  core/src/main/java/com/scalar/db/storage/cosmos/ScannerImpl.java
Labels: improvement

#628 Add myself in the released pom file "developers" information
  core/archive.gradle
  rpc/archive.gradle
  schema-loader/archive.gradle
  server/archive.gradle
Labels: documentation

#625 Add documentation for Storage abstraction
  README.md
  docs/api-guide.md
  docs/getting-started-with-scalardb.md
  docs/index.md
  docs/storage-abstraction.md
Labels: documentation

#629 Rename getCreateOptions() to getCreationOptions() in integration tests
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageAdminRepairTableIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageColumnValueIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageConditionalMutationIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageMultipleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageMultiplePartitionKeyIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageSecondaryIndexIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageSingleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageSinglePartitionKeyIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageWithReservedKeywordIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionAdminRepairTableIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminRepairTableIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminRepairTableIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminRepairTableIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitSpecificIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminRepairTableIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosColumnValueIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosConditionalMutationIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosEnv.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSecondaryIndexIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSinglePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosWithReservedKeywordIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitSpecificIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminRepairTableIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitSpecificIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminRepairTableIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoColumnValueIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoConditionalMutationIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoEnv.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSecondaryIndexIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSinglePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoWithReservedKeywordIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/TwoPhaseConsensusCommitIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/TwoPhaseConsensusCommitSpecificIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
  docs/getting-started/src/main/java/sample/ElectronicMoneyMain.java
Labels: improvement

#627 Refactor Scalar DB Server documentation
  conf/database.properties
  docs/scalardb-server.md
  server/README.md
Labels: documentation

#626 Add GraphQL and SQL to License section in README
  README.md
  docs/index.md
Labels: documentation

#622 Add repair table command to the Schema Loader Tool
  core/src/integration-test/java/com/scalar/db/util/AdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/util/CassandraAdminTestUtils.java
  schema-loader/README.md
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageSchemaLoaderIntegrationTest.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/CassandraCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/CosmosCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/DynamoCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/JdbcCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/StorageSpecificCommand.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaLoaderTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/CassandraCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/CosmosCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/DynamoCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/JdbcCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/SchemaLoaderCommandTest.java
Labels: enhancement

#630 Fix typo
  core/src/main/java/com/scalar/db/api/Consistency.java
  core/src/main/java/com/scalar/db/api/DistributedStorage.java
  core/src/main/java/com/scalar/db/api/DistributedTransaction.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  docs/design.md
  docs/getting-started-with-scalardb-on-jdbc.md
  docs/getting-started-with-scalardb.md
  docs/requirements.md
  docs/storage-abstraction.md
Labels: documentation

#632 Rename `transactional` to `transaction`
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionAdminRepairTableIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  core/src/main/java/com/scalar/db/api/TransactionCrudOperable.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/FilteredResult.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionTableMetadata.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionTableMetadataManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtilsTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/FilteredResultTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/MergedResultTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/RecoveryHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TransactionResultTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TransactionTableMetadataManagerTest.java
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/StorageSpecificCommand.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaParserTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/CassandraCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/CosmosCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/DynamoCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/JdbcCommandTest.java
Labels: improvement

#633 Reduce Intellij warnings
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageAdminRepairTableIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageWithReservedKeywordIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionAdminRepairTableIntegrationTestBase.java
  core/src/main/java/com/scalar/db/common/TableMetadataManager.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionTableMetadataManager.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/ScannerImplTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoOperationCheckerTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminTest.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/CassandraCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/CosmosCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/DynamoCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/JdbcCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceRepairTableIntegrationTest.java
Labels: improvement

#634 Small modifications for documentation
  docs/api-guide.md
  docs/design.md
  docs/getting-started-with-scalardb.md
  docs/multi-storage-transactions.md
  docs/scalardb-server.md
  docs/storage-abstraction.md
  docs/two-phase-commit-transactions.md
Labels: documentation

#636 Update the Scalar DB version of the dependency in README
  README.md
  docs/index.md
Labels: documentation

#637 Modify descriptions in archive.gradle
  README.md
  core/archive.gradle
  docs/index.md
  schema-loader/archive.gradle
  server/archive.gradle
Labels: improvement

#639 Several fixes for documents
  docs/api-guide.md
  docs/storage-abstraction.md
Labels: documentation

#640 Update Scalar DB dependency in Getting Started
  docs/getting-started-with-scalardb.md
  docs/getting-started/build.gradle
Labels: improvement

#635 Add database compatibility of Scalar DB 3.6
  docs/scalardb-supported-databases.md
Labels: documentation

#638 Add capability to add a new column to an existing table in the Administration interface
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
  core/src/main/java/com/scalar/db/api/Admin.java
  core/src/main/java/com/scalar/db/service/AdminService.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdmin.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionAdmin.java
  core/src/main/java/com/scalar/db/util/ProtoUtils.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
  core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTest.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcAdminTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtilsTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionAdminTest.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageAdminGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionAdminGrpc.java
  rpc/src/main/java/com/scalar/db/rpc/AddNewColumnToTableRequest.java
  rpc/src/main/java/com/scalar/db/rpc/AddNewColumnToTableRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java
  rpc/src/main/proto/scalardb.proto
  server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java
  server/src/main/java/com/scalar/db/server/DistributedTransactionAdminService.java
  server/src/test/java/com/scalar/db/server/DistributedStorageAdminServiceTest.java
  server/src/test/java/com/scalar/db/server/DistributedTransactionAdminServiceTest.java
Labels: enhancement

#641 Deprecate table mapping in Multi-storage
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorage.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  docs/multi-storage-transactions.md
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
Labels: improvement

#642 Change default value of is-transaction-table in Schema Loader
  schema-loader/README.md
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/TableSchemaTest.java
Labels: improvement

#643 Add documentation for admin.addNewColumnToTable()
  core/src/main/java/com/scalar/db/api/Admin.java
  docs/api-guide.md
  docs/storage-abstraction.md
Labels: documentation
