Repository scalar-labs/scalardb, pull requests merged in 2022-11, with the labels that each got.

#731 Fix two unit tests of OperationChecker
  core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
Labels: improvement

#734 Make JDK11+ use the same google java format version as JDK8 uses
  build.gradle
  core/build.gradle
  integration-test/build.gradle
  schema-loader/build.gradle
  server/build.gradle
Labels: improvement

#732 Make ConsensusCommitAdmin.getNamespaceNames() to not return the coordinator namespace name
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminIntegrationTest.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminIntegrationTestBase.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithDistributedTransactionAdminService.java
Labels: improvement

#735 Fix dependency errors for Maven projects
  core/build.gradle
Labels: bugfix

#736 Add upgrade command to schema loader
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSchemaLoaderIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageSchemaLoaderIntegrationTest.java
  docs/schema-loader.md
  integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaLoaderTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/SchemaLoaderCommandTest.java
Labels: enhancement

#737 Move vuln check to a separate daily workflow
  .github/workflows/ci.yaml
  .github/workflows/vuln-check.yaml
Labels: improvement

#738 Update protobuf and grpc to fix CVE-2022-3171
  build.gradle
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageAdminGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionAdminGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/TwoPhaseCommitTransactionGrpc.java
  rpc/src/main/java/com/scalar/db/rpc/AbortRequest.java
  rpc/src/main/java/com/scalar/db/rpc/AbortResponse.java
  rpc/src/main/java/com/scalar/db/rpc/AddNewColumnToTableRequest.java
  rpc/src/main/java/com/scalar/db/rpc/Column.java
  rpc/src/main/java/com/scalar/db/rpc/ConditionalExpression.java
  rpc/src/main/java/com/scalar/db/rpc/CoordinatorTablesExistRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CoordinatorTablesExistResponse.java
  rpc/src/main/java/com/scalar/db/rpc/CreateCoordinatorTablesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CreateIndexRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CreateNamespaceRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CreateTableRequest.java
  rpc/src/main/java/com/scalar/db/rpc/DropCoordinatorTablesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/DropIndexRequest.java
  rpc/src/main/java/com/scalar/db/rpc/DropNamespaceRequest.java
  rpc/src/main/java/com/scalar/db/rpc/DropTableRequest.java
  rpc/src/main/java/com/scalar/db/rpc/Get.java
  rpc/src/main/java/com/scalar/db/rpc/GetNamespaceTableNamesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/GetNamespaceTableNamesResponse.java
  rpc/src/main/java/com/scalar/db/rpc/GetRequest.java
  rpc/src/main/java/com/scalar/db/rpc/GetResponse.java
  rpc/src/main/java/com/scalar/db/rpc/GetTableMetadataRequest.java
  rpc/src/main/java/com/scalar/db/rpc/GetTableMetadataResponse.java
  rpc/src/main/java/com/scalar/db/rpc/GetTransactionStateRequest.java
  rpc/src/main/java/com/scalar/db/rpc/GetTransactionStateResponse.java
  rpc/src/main/java/com/scalar/db/rpc/Key.java
  rpc/src/main/java/com/scalar/db/rpc/MutateCondition.java
  rpc/src/main/java/com/scalar/db/rpc/MutateRequest.java
  rpc/src/main/java/com/scalar/db/rpc/Mutation.java
  rpc/src/main/java/com/scalar/db/rpc/NamespaceExistsRequest.java
  rpc/src/main/java/com/scalar/db/rpc/NamespaceExistsResponse.java
  rpc/src/main/java/com/scalar/db/rpc/Ordering.java
  rpc/src/main/java/com/scalar/db/rpc/RepairCoordinatorTablesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/RepairTableRequest.java
  rpc/src/main/java/com/scalar/db/rpc/Result.java
  rpc/src/main/java/com/scalar/db/rpc/RollbackRequest.java
  rpc/src/main/java/com/scalar/db/rpc/RollbackResponse.java
  rpc/src/main/java/com/scalar/db/rpc/Scan.java
  rpc/src/main/java/com/scalar/db/rpc/ScanRequest.java
  rpc/src/main/java/com/scalar/db/rpc/ScanResponse.java
  rpc/src/main/java/com/scalar/db/rpc/TableMetadata.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionResponse.java
  rpc/src/main/java/com/scalar/db/rpc/TruncateCoordinatorTablesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TruncateTableRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TwoPhaseCommitTransactionRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TwoPhaseCommitTransactionResponse.java
  rpc/src/main/java/com/scalar/db/rpc/Value.java
Labels: bugfix

#739 Update the Scalar DB dependency version to 3.7.1
  README.md
  docs/getting-started/build.gradle
  docs/index.md
Labels: documentation

#741 Conduct daily vulnerability checks on releases not only on `main` branch
  .github/workflows/vuln-check.yaml
Labels: improvement

#740 Should drop namespace only when no tables are in the namespace in Schema Loader
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
Labels: improvement

#742 Remove unnecessary key definition from API guide
  docs/api-guide.md
Labels: documentation

#743 Fix CVE-2022-40151 and CVE-2022-40152
  build.gradle
Labels: bugfix

#744 Move common classes
  core/src/main/java/com/scalar/db/common/AbstractDistributedStorage.java
  core/src/main/java/com/scalar/db/common/AbstractDistributedTransaction.java
  core/src/main/java/com/scalar/db/common/AbstractDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/AbstractTwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/common/AbstractTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/common/EmptyScanner.java
  core/src/main/java/com/scalar/db/common/ScannerIterator.java
  core/src/main/java/com/scalar/db/common/WrappedDistributedTransaction.java
  core/src/main/java/com/scalar/db/common/WrappedTwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/common/checker/ColumnChecker.java
  core/src/main/java/com/scalar/db/common/checker/ConditionChecker.java
  core/src/main/java/com/scalar/db/common/checker/OperationChecker.java
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/cassandra/ScannerImpl.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosOperationChecker.java
  core/src/main/java/com/scalar/db/storage/cosmos/ScannerImpl.java
  core/src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoOperationChecker.java
  core/src/main/java/com/scalar/db/storage/dynamo/GetItemScanner.java
  core/src/main/java/com/scalar/db/storage/dynamo/QueryScanner.java
  core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  core/src/main/java/com/scalar/db/storage/jdbc/ScannerImpl.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorage.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
  core/src/main/java/com/scalar/db/storage/rpc/ScannerImpl.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransaction.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
  core/src/test/java/com/scalar/db/common/AbstractDistributedTransactionManagerTest.java
  core/src/test/java/com/scalar/db/common/AbstractTwoPhaseCommitTransactionManagerTest.java
  core/src/test/java/com/scalar/db/common/checker/OperationCheckerTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
Labels: improvement
