Repository scalar-labs/scalardb, pull requests merged in 2022-02, with the labels that each got.

#486 Update Scalar DB backup and restoration guide
  docs/backup-restore.md
Labels: documentation

#482 Use only id and version to check if a read record is not changed in the validation in EXTRA_READ
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
Labels: improvement

#490 Should not publish a fat jar for Schema Loader to the maven repository
  schema-loader/build.gradle
Labels: bugfix

#491 Add annotations
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosTableMetadata.java
  core/src/main/java/com/scalar/db/storage/cosmos/Record.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/BigIntBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/BlobBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/BooleanBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/DoubleBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/FloatBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/IntBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/TextBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/DeleteQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/InsertOnConflictDoUpdateQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/InsertOnDuplicateKeyUpdateQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/InsertQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/MergeIntoQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/MergeQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/PreparedStatementBinder.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithFetchFirstNRowsOnly.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithLimitQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithOffsetFetchQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/UpdateQuery.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/FilteredResult.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionalTableMetadataManager.java
  core/src/main/java/com/scalar/db/util/ActiveExpiringMap.java
  core/src/main/java/com/scalar/db/util/ImmutableLinkedHashSet.java
  core/src/main/java/com/scalar/db/util/TableMetadataManager.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java
  server/src/main/java/com/scalar/db/server/LockFreeGateKeeper.java
  server/src/main/java/com/scalar/db/server/ServerConfig.java
Labels: improvement

#492 Move ResultImpl to the util package
  core/src/main/java/com/scalar/db/storage/cassandra/ResultInterpreter.java
  core/src/main/java/com/scalar/db/storage/cosmos/ResultInterpreter.java
  core/src/main/java/com/scalar/db/storage/dynamo/ResultInterpreter.java
  core/src/main/java/com/scalar/db/storage/jdbc/ResultInterpreter.java
  core/src/main/java/com/scalar/db/util/ProtoUtils.java
  core/src/main/java/com/scalar/db/util/ResultImpl.java
  core/src/test/java/com/scalar/db/storage/common/ResultImplTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/FilteredResultTest.java
Labels: improvement

#488 Unnecessary columns are not read any more in Consensus Commit
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
  core/src/main/java/com/scalar/db/service/TransactionModule.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/UncommittedRecordException.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/RecoveryHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
Labels: improvement

#493 Update PostgreSQL driver version for vulnerability fix
  build.gradle
Labels: bugfix

#496 Add constructors to ConditionalExpression
  core/src/main/java/com/scalar/db/api/ConditionalExpression.java
Labels: improvement

#497 Add ByteBuffer support for Blob type
  core/src/integration-test/java/com/scalar/db/storage/TestUtils.java
  core/src/main/java/com/scalar/db/api/ConditionalExpression.java
  core/src/main/java/com/scalar/db/api/Put.java
  core/src/main/java/com/scalar/db/io/BlobValue.java
  core/src/main/java/com/scalar/db/io/Key.java
  core/src/main/java/com/scalar/db/io/TextValue.java
  core/src/main/java/com/scalar/db/storage/cassandra/ResultInterpreter.java
  core/src/main/java/com/scalar/db/util/ProtoUtils.java
  core/src/test/java/com/scalar/db/api/PutTest.java
  core/src/test/java/com/scalar/db/io/BlobValueTest.java
  core/src/test/java/com/scalar/db/io/KeyTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/ValueBinderTest.java
Labels: improvement

#494 Use before image column names from TransactionalTableMetadata in RollbackMutationComposer
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/MutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/RecoveryHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
Labels: improvement

#499 Support SQL Server and Amazon Aurora officially
  docs/getting-started-with-scalardb-on-jdbc.md
Labels: documentation

#498 Should not change states of operation instances passed as arguments
  core/src/main/java/com/scalar/db/api/Delete.java
  core/src/main/java/com/scalar/db/api/Get.java
  core/src/main/java/com/scalar/db/api/Mutation.java
  core/src/main/java/com/scalar/db/api/Operation.java
  core/src/main/java/com/scalar/db/api/Put.java
  core/src/main/java/com/scalar/db/api/Scan.java
  core/src/main/java/com/scalar/db/api/Selection.java
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/common/AbstractDistributedStorage.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorage.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
  core/src/main/java/com/scalar/db/transaction/common/AbstractDistributedTransaction.java
  core/src/main/java/com/scalar/db/transaction/common/AbstractDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransaction.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
  core/src/test/java/com/scalar/db/api/DeleteTest.java
  core/src/test/java/com/scalar/db/api/GetTest.java
  core/src/test/java/com/scalar/db/api/PutTest.java
  core/src/test/java/com/scalar/db/api/ScanTest.java
  core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
  core/src/test/java/com/scalar/db/util/ScalarDbUtilsTest.java
Labels: improvement

#506 Classes/Methods deprecated in 3.x should be removed in 5.0.0
  core/src/main/java/com/scalar/db/api/Isolation.java
  core/src/main/java/com/scalar/db/api/SerializableStrategy.java
  core/src/main/java/com/scalar/db/io/TextValue.java
  core/src/main/java/com/scalar/db/service/AdminService.java
  core/src/main/java/com/scalar/db/service/StorageService.java
  core/src/main/java/com/scalar/db/service/TransactionService.java
  core/src/main/java/com/scalar/db/service/TwoPhaseCommitTransactionService.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
Labels: improvement

#503 Reduce Intellij warnings
  core/src/integration-test/java/com/scalar/db/storage/StorageWithReservedKeywordIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/FilteredResultTest.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/util/either/Left.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/util/either/Right.java
Labels: improvement

#504 Change Key builder
  core/src/main/java/com/scalar/db/io/Key.java
  core/src/test/java/com/scalar/db/io/KeyTest.java
  core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
Labels: improvement

#500 Move the rollbackRecords method from RecoveryHandler to CommitHandler
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/RecoveryHandlerTest.java
Labels: improvement

#502 Revisit logging
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/cassandra/StatementHandler.java
  core/src/main/java/com/scalar/db/storage/cassandra/ValueBinder.java
  core/src/main/java/com/scalar/db/storage/cosmos/BatchHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/StatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/StorageSpecificCommand.java
  server/src/main/java/com/scalar/db/server/ScalarDbServer.java
Labels: improvement

#507 Rename `keyspace` to `namespace` in unit tests
  core/src/test/java/com/scalar/db/storage/cassandra/BatchHandlerTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/DeleteStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/InsertStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/SelectStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/UpdateStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/BatchHandlerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosMutationTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosOperationTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/DeleteStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/PutStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/BatchHandlerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DeleteStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoMutationTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoOperationTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/PutStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/PartitionedMutationsKeyTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/PartitionedMutationsTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotKeyTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
Labels: improvement

#508 Add ByteBuffer support to Value
  core/src/main/java/com/scalar/db/io/BlobValue.java
  core/src/main/java/com/scalar/db/io/TextValue.java
  core/src/main/java/com/scalar/db/io/Value.java
  core/src/test/java/com/scalar/db/io/BigIntValueTest.java
  core/src/test/java/com/scalar/db/io/BlobValueTest.java
  core/src/test/java/com/scalar/db/io/BooleanValueTest.java
  core/src/test/java/com/scalar/db/io/DoubleValueTest.java
  core/src/test/java/com/scalar/db/io/FloatValueTest.java
  core/src/test/java/com/scalar/db/io/IntValueTest.java
  core/src/test/java/com/scalar/db/io/TextValueTest.java
Labels: enhancement

#509 Update the Scalar DB version of the dependency in README
  README.md
  docs/index.md
Labels: documentation

#511 Update the Scalar DB version of the dependency in README
  README.md
  docs/index.md
Labels: documentation

#510 Update ScalarDB compatibility test matrix
  docs/scalardb-supported-databases.md
Labels: documentation

#513 Refactor ImmutableLinkedHashSet
  core/src/main/java/com/scalar/db/util/ImmutableLinkedHashSet.java
Labels: improvement

#514 Fix typo in the javadoc
  core/src/main/java/com/scalar/db/api/Operation.java
Labels: bugfix
