Repository scalar-labs/scalardb, pull requests merged in 2022-06, with the labels that each got.

#593 For Dynamo storage, throw an exception when a Put set a secondary index column value to null
  core/src/main/java/com/scalar/db/storage/common/checker/ColumnChecker.java
  core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoOperationChecker.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoOperationCheckerTest.java
Labels: improvement

#594 Add check for empty key
  core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
  core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
Labels: improvement

#596 Merge protocVersion and protobufVersion
  build.gradle
  rpc/build.gradle
Labels: improvement

#599 Add toString() to condition related classes
  core/src/main/java/com/scalar/db/api/ConditionalExpression.java
  core/src/main/java/com/scalar/db/api/DeleteIf.java
  core/src/main/java/com/scalar/db/api/DeleteIfExists.java
  core/src/main/java/com/scalar/db/api/PutIf.java
  core/src/main/java/com/scalar/db/api/PutIfExists.java
  core/src/main/java/com/scalar/db/api/PutIfNotExists.java
Labels: improvement

#598 Add a way to disable metadata cache
  core/src/main/java/com/scalar/db/common/TableMetadataManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionalTableMetadataManager.java
Labels: improvement

#600 Refactor ConsensusCommitUtils
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtilsTest.java
Labels: improvement

#602 Remove copyDependencies task
  core/build.gradle
Labels: improvement

#603 Update the docs
  docs/getting-started-with-scalardb-on-cassandra.md
  docs/getting-started-with-scalardb-on-cosmosdb.md
  docs/getting-started-with-scalardb-on-dynamodb.md
  docs/getting-started-with-scalardb-on-jdbc.md
Labels: bugfix

#604 Fix CVE-2022-1664
  schema-loader/Dockerfile
  server/Dockerfile
Labels: improvement

#601 Add builder for Put, Delete, Scan and Get operations
  core/src/main/java/com/scalar/db/api/Delete.java
  core/src/main/java/com/scalar/db/api/DeleteBuilder.java
  core/src/main/java/com/scalar/db/api/Get.java
  core/src/main/java/com/scalar/db/api/GetBuilder.java
  core/src/main/java/com/scalar/db/api/Mutation.java
  core/src/main/java/com/scalar/db/api/Operation.java
  core/src/main/java/com/scalar/db/api/OperationBuilder.java
  core/src/main/java/com/scalar/db/api/Put.java
  core/src/main/java/com/scalar/db/api/PutBuilder.java
  core/src/main/java/com/scalar/db/api/Scan.java
  core/src/main/java/com/scalar/db/api/ScanAll.java
  core/src/main/java/com/scalar/db/api/ScanBuilder.java
  core/src/main/java/com/scalar/db/api/Selection.java
  core/src/test/java/com/scalar/db/api/DeleteBuilderTest.java
  core/src/test/java/com/scalar/db/api/GetBuilderTest.java
  core/src/test/java/com/scalar/db/api/PutBuilderTest.java
  core/src/test/java/com/scalar/db/api/ScanBuilderTest.java
Labels: enhancement

#605 Fix incompatible change
  core/src/main/java/com/scalar/db/api/Put.java
  core/src/test/java/com/scalar/db/api/PutTest.java
Labels: bugfix

#606 Refactor Gradle Plugin things
  build.gradle
  ci/dockerfile_lint.sh
  core/build.gradle
  rpc/build.gradle
  schema-loader/build.gradle
  server/build.gradle
Labels: improvement

#597 Upgrade SpotBugs
  build.gradle
  core/build.gradle
  core/src/main/java/com/scalar/db/api/TableMetadata.java
  core/src/main/java/com/scalar/db/common/ResultImpl.java
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/MapVisitor.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/FilteredResult.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionalTableMetadata.java
  core/src/test/java/com/scalar/db/api/GetTest.java
  core/src/test/java/com/scalar/db/common/TableMetadataManagerTest.java
  core/src/test/java/com/scalar/db/io/BigIntValueTest.java
  core/src/test/java/com/scalar/db/io/BlobValueTest.java
  core/src/test/java/com/scalar/db/io/BooleanValueTest.java
  core/src/test/java/com/scalar/db/io/DoubleValueTest.java
  core/src/test/java/com/scalar/db/io/FloatValueTest.java
  core/src/test/java/com/scalar/db/io/IntValueTest.java
  core/src/test/java/com/scalar/db/io/TextValueTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/BatchComposerTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ParallelExecutorTest.java
  gradle/spotbugs-exclude.xml
  schema-loader/build.gradle
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaParser.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java
  server/build.gradle
  server/src/main/java/com/scalar/db/server/ServerConfig.java
Labels: improvement

#609 Refactor Scalar DB Server
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStream.java
  rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionResponse.java
  rpc/src/main/proto/scalardb.proto
  schema-loader/src/integration-test/java/com/scalar/db/server/SchemaLoaderWithScalarDbServer.java
  server/build.gradle
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithDistributedStorageService.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitSpecificIntegrationTestWithDistributedStorageService.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceColumnValueIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceConditionalMutationIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceMultipleClusteringKeyScanIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceMultiplePartitionKeyIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSecondaryIndexIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSingleClusteringKeyScanIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSinglePartitionKeyIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionAdminServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithDistributedStorageService.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitSpecificIntegrationTestWithDistributedStorageService.java
  server/src/main/java/com/scalar/db/server/AdminService.java
  server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java
  server/src/main/java/com/scalar/db/server/DistributedStorageService.java
  server/src/main/java/com/scalar/db/server/DistributedTransactionAdminService.java
  server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
  server/src/main/java/com/scalar/db/server/LockFreeGateKeeper.java
  server/src/main/java/com/scalar/db/server/ScalarDbServer.java
  server/src/main/java/com/scalar/db/server/ServerConfig.java
  server/src/main/java/com/scalar/db/server/ServerModule.java
  server/src/main/java/com/scalar/db/server/TwoPhaseCommitTransactionService.java
  server/src/test/java/com/scalar/db/server/ServerConfigTest.java
Labels: improvement

#610 Add @deprecated javadoc to overriding methods
  core/src/main/java/com/scalar/db/common/AbstractResult.java
  core/src/main/java/com/scalar/db/service/StorageService.java
  core/src/main/java/com/scalar/db/service/TransactionService.java
  core/src/main/java/com/scalar/db/service/TwoPhaseCommitTransactionService.java
  core/src/main/java/com/scalar/db/storage/common/AbstractDistributedStorage.java
  core/src/main/java/com/scalar/db/transaction/common/AbstractDistributedTransaction.java
  core/src/main/java/com/scalar/db/transaction/common/AbstractDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/util/ProtoUtils.java
Labels: improvement

#611 Fix non constant names
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageColumnValueIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageConditionalMutationIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageMultipleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageMultiplePartitionKeyIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageSecondaryIndexIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageSingleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageSinglePartitionKeyIntegrationTestBase.java
  core/src/main/java/com/scalar/db/api/Operation.java
  core/src/main/java/com/scalar/db/common/ResultImpl.java
  core/src/main/java/com/scalar/db/storage/cassandra/BatchHandler.java
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/cassandra/ClusterManager.java
  core/src/main/java/com/scalar/db/storage/cassandra/MutateStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cassandra/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cassandra/StatementHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/BatchHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/cosmos/MutateStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/StatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/ScannerImpl.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/FilteredResult.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionAdmin.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/util/retry/Retry.java
  core/src/test/java/com/scalar/db/storage/dynamo/bytes/KeyBytesEncoderTest.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/StorageSpecificCommand.java
  server/src/main/java/com/scalar/db/server/AdminService.java
  server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java
  server/src/main/java/com/scalar/db/server/DistributedStorageService.java
  server/src/main/java/com/scalar/db/server/DistributedTransactionAdminService.java
  server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
  server/src/main/java/com/scalar/db/server/Metrics.java
  server/src/main/java/com/scalar/db/server/ScalarDbServer.java
  server/src/main/java/com/scalar/db/server/TwoPhaseCommitTransactionService.java
Labels: improvement

#608 Refactor Guice modules
  core/src/main/java/com/scalar/db/service/StorageModule.java
  core/src/main/java/com/scalar/db/service/TransactionModule.java
Labels: improvement

#615 Update Javadoc
  core/src/main/java/com/scalar/db/api/Delete.java
  core/src/main/java/com/scalar/db/api/DistributedStorage.java
  core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/api/DistributedTransaction.java
  core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java
  core/src/main/java/com/scalar/db/api/Get.java
  core/src/main/java/com/scalar/db/api/Mutation.java
  core/src/main/java/com/scalar/db/api/OperationBuilder.java
  core/src/main/java/com/scalar/db/api/Put.java
  core/src/main/java/com/scalar/db/api/Scan.java
  core/src/main/java/com/scalar/db/api/ScanAll.java
  core/src/main/java/com/scalar/db/api/Selection.java
  core/src/main/java/com/scalar/db/api/TransactionCrudOperable.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/io/BigIntColumn.java
  core/src/main/java/com/scalar/db/io/BlobColumn.java
  core/src/main/java/com/scalar/db/io/BooleanColumn.java
  core/src/main/java/com/scalar/db/io/DoubleColumn.java
  core/src/main/java/com/scalar/db/io/FloatColumn.java
  core/src/main/java/com/scalar/db/io/IntColumn.java
  core/src/main/java/com/scalar/db/io/TextColumn.java
  core/src/main/java/com/scalar/db/service/StorageFactory.java
  core/src/main/java/com/scalar/db/service/TransactionFactory.java
Labels: documentation

#614 Add some useful methods
  core/src/main/java/com/scalar/db/api/GetBuilder.java
  core/src/main/java/com/scalar/db/api/OperationBuilder.java
  core/src/main/java/com/scalar/db/api/ScanBuilder.java
  core/src/main/java/com/scalar/db/service/StorageFactory.java
  core/src/main/java/com/scalar/db/service/TransactionFactory.java
  core/src/test/java/com/scalar/db/api/GetBuilderTest.java
  core/src/test/java/com/scalar/db/api/ScanBuilderTest.java
  gradle/spotbugs-exclude.xml
  schema-loader/Dockerfile
Labels: enhancement

#617 Update Getting Started
  docs/getting-started-with-scalardb-on-cassandra.md
  docs/getting-started-with-scalardb-on-cosmosdb.md
  docs/getting-started-with-scalardb-on-dynamodb.md
  docs/getting-started-with-scalardb-on-jdbc.md
  docs/getting-started-with-scalardb.md
  docs/getting-started/gradle/wrapper/gradle-wrapper.jar
  docs/getting-started/gradle/wrapper/gradle-wrapper.properties
  docs/getting-started/gradlew
  docs/getting-started/gradlew.bat
  docs/getting-started/src/main/java/sample/ElectronicMoney.java
  docs/getting-started/src/main/java/sample/ElectronicMoneyMain.java
  docs/getting-started/src/main/java/sample/ElectronicMoneyWithStorage.java
  docs/getting-started/src/main/java/sample/ElectronicMoneyWithTransaction.java
Labels: documentation

#613 Add methods to repair table and coordinator table to the Admin interfaces
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageAdminRepairTableIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionAdminRepairTableIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminRepairTableIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminRepairTableIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminRepairTableIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminRepairTableIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminRepairTableIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminRepairTableIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminRepairTableIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminRepairTableIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminRepairTableIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminRepairTableIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/util/AdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/util/CosmosAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/util/DynamoAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/util/JdbcAdminTestUtils.java
  core/src/main/java/com/scalar/db/api/Admin.java
  core/src/main/java/com/scalar/db/api/DistributedTransactionAdmin.java
  core/src/main/java/com/scalar/db/service/AdminService.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdmin.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionAdmin.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
  core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTest.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcAdminTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionAdminTest.java
  gradle/spotbugs-exclude.xml
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageAdminGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionAdminGrpc.java
  rpc/src/main/java/com/scalar/db/rpc/RepairCoordinatorTablesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/RepairCoordinatorTablesRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/RepairTableRequest.java
  rpc/src/main/java/com/scalar/db/rpc/RepairTableRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java
  rpc/src/main/proto/scalardb.proto
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceRepairTableIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionAdminServiceRepairTableIntegrationTest.java
  server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java
  server/src/main/java/com/scalar/db/server/DistributedTransactionAdminService.java
Labels: enhancement
