Repository scalar-labs/scalardb, pull requests merged in 2022-05, with the labels that each got.

#573 Update the Scalar DB version of the dependency in README
  README.md
  docs/index.md
Labels: documentation

#574 Refactor DistributedTransactionAdmin
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageColumnValueIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageConditionalMutationIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageMultipleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageMultiplePartitionKeyIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageSecondaryIndexIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageSingleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageSinglePartitionKeyIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageWithReservedKeywordIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/sql/SqlStatementWithTransactionSessionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/sql/SqlStatementWithTwoPhaseCommitTransactionSessionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
  core/src/main/java/com/scalar/db/api/DistributedTransactionAdmin.java
  core/src/main/java/com/scalar/db/sql/DdlStatementExecutor.java
  core/src/main/java/com/scalar/db/sql/StatementValidator.java
  core/src/main/java/com/scalar/db/sql/builder/CreateCoordinatorTablesStatementBuilder.java
  core/src/main/java/com/scalar/db/sql/builder/DropCoordinatorTableStatementBuilder.java
  core/src/main/java/com/scalar/db/sql/builder/DropCoordinatorTablesStatementBuilder.java
  core/src/main/java/com/scalar/db/sql/builder/StatementBuilder.java
  core/src/main/java/com/scalar/db/sql/builder/TruncateCoordinatorTableStatementBuilder.java
  core/src/main/java/com/scalar/db/sql/builder/TruncateCoordinatorTablesStatementBuilder.java
  core/src/main/java/com/scalar/db/sql/statement/CreateCoordinatorTablesStatement.java
  core/src/main/java/com/scalar/db/sql/statement/DdlStatementVisitor.java
  core/src/main/java/com/scalar/db/sql/statement/DropCoordinatorTablesStatement.java
  core/src/main/java/com/scalar/db/sql/statement/TruncateCoordinatorTablesStatement.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdmin.java
  core/src/test/java/com/scalar/db/sql/DdlStatementExecutorTest.java
  core/src/test/java/com/scalar/db/sql/builder/StatementBuilderTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminTest.java
  docs/backup-restore.md
  schema-loader/README.md
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/StorageSpecificCommand.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaLoaderTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/CassandraCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/CosmosCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/DynamoCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/JdbcCommandTest.java
Labels: improvement

#570 Add scanAll for cassandra storage
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/util/TestUtils.java
  core/src/main/java/com/scalar/db/api/DistributedStorage.java
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/cassandra/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
  core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
  core/src/test/java/com/scalar/db/storage/cassandra/SelectStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
Labels: enhancement

#575 Add DistributedTransactionAdminService to Scalar DB Server
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionAdmin.java
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionAdminTest.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionAdminGrpc.java
  rpc/src/main/java/com/scalar/db/rpc/CoordinatorTablesExistRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CoordinatorTablesExistRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/CoordinatorTablesExistResponse.java
  rpc/src/main/java/com/scalar/db/rpc/CoordinatorTablesExistResponseOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/CreateCoordinatorTablesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CreateCoordinatorTablesRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/DropCoordinatorTablesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/DropCoordinatorTablesRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java
  rpc/src/main/java/com/scalar/db/rpc/TruncateCoordinatorTablesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TruncateCoordinatorTablesRequestOrBuilder.java
  rpc/src/main/proto/scalardb.proto
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionAdminServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/ServerEnv.java
  server/src/main/java/com/scalar/db/server/DistributedTransactionAdminService.java
  server/src/main/java/com/scalar/db/server/ScalarDbServer.java
  server/src/main/java/com/scalar/db/server/ServerModule.java
  server/src/test/java/com/scalar/db/server/DistributedTransactionAdminServiceTest.java
Labels: enhancement

#571 Update backup creation and restoration procedures
  docs/backup-restore.md
Labels: documentation

#578 Add ScanAll for Cosmos DB storage
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java
  core/src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
Labels: enhancement

#580 Add new steps in the release.yaml to push container to Azure Container Registry
  .github/workflows/release.yaml
Labels: enhancement

#577 Add ScanAll for DynamoDB storage
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/dynamo/QueryScanner.java
  core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/request/PaginatedRequest.java
  core/src/main/java/com/scalar/db/storage/dynamo/request/PaginatedRequestResponse.java
  core/src/main/java/com/scalar/db/storage/dynamo/request/QueryRequest.java
  core/src/main/java/com/scalar/db/storage/dynamo/request/ScanRequest.java
  core/src/test/java/com/scalar/db/storage/dynamo/QueryScannerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
Labels: enhancement

#581 Enable PITR for metadata table in Dynamo DB adapter
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
Labels: improvement

#582 Add ScanAll for JDBC storage
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithOffsetFetchQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithTop.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
Labels: enhancement

#587 Update jre8 base image to 1.1.2
  schema-loader/Dockerfile
  server/Dockerfile
Labels: improvement

#583 Implement the checkPaused service according to scalar-admin 1.2.0
  build.gradle
  server/src/main/java/com/scalar/db/server/AdminService.java
  server/src/main/java/com/scalar/db/server/GateKeeper.java
  server/src/main/java/com/scalar/db/server/LockFreeGateKeeper.java
  server/src/main/java/com/scalar/db/server/SynchronizedGateKeeper.java
Labels: enhancement

#584 Add ScanAll to GRPC storage
  core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
  core/src/main/java/com/scalar/db/util/ProtoUtils.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
Labels: enhancement

#585 Use `max_pause_wait_time` in AdminService
  server/src/main/java/com/scalar/db/server/AdminService.java
Labels: enhancement

#588 Add suspend method to TwoPhaseCommitTransactionManager
  core/src/integration-test/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/service/TwoPhaseCommitTransactionService.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/util/ActiveExpiringMap.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManagerTest.java
  docs/two-phase-commit-transactions.md
  server/src/main/java/com/scalar/db/server/ServerModule.java
Labels: enhancement (backward-incompatible)

#589 Update dependencies to fix CVE-2022-25647
  build.gradle
  core/src/main/java/com/scalar/db/api/Operation.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageAdminGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionAdminGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/TwoPhaseCommitTransactionGrpc.java
  rpc/src/main/java/com/scalar/db/rpc/AbortRequest.java
  rpc/src/main/java/com/scalar/db/rpc/AbortResponse.java
  rpc/src/main/java/com/scalar/db/rpc/ConditionalExpression.java
  rpc/src/main/java/com/scalar/db/rpc/CoordinatorTablesExistRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CoordinatorTablesExistResponse.java
  rpc/src/main/java/com/scalar/db/rpc/CreateCoordinatorTablesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CreateCoordinatorTablesRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/CreateIndexRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CreateIndexRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/CreateNamespaceRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CreateNamespaceRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/CreateTableRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CreateTableRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/DropCoordinatorTablesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/DropIndexRequest.java
  rpc/src/main/java/com/scalar/db/rpc/DropNamespaceRequest.java
  rpc/src/main/java/com/scalar/db/rpc/DropTableRequest.java
  rpc/src/main/java/com/scalar/db/rpc/Get.java
  rpc/src/main/java/com/scalar/db/rpc/GetNamespaceTableNamesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/GetNamespaceTableNamesResponse.java
  rpc/src/main/java/com/scalar/db/rpc/GetRequest.java
  rpc/src/main/java/com/scalar/db/rpc/GetResponse.java
  rpc/src/main/java/com/scalar/db/rpc/GetTableMetadataRequest.java
  rpc/src/main/java/com/scalar/db/rpc/GetTableMetadataResponse.java
  rpc/src/main/java/com/scalar/db/rpc/GetTransactionStateRequest.java
  rpc/src/main/java/com/scalar/db/rpc/GetTransactionStateResponse.java
  rpc/src/main/java/com/scalar/db/rpc/Key.java
  rpc/src/main/java/com/scalar/db/rpc/MutateCondition.java
  rpc/src/main/java/com/scalar/db/rpc/MutateRequest.java
  rpc/src/main/java/com/scalar/db/rpc/Mutation.java
  rpc/src/main/java/com/scalar/db/rpc/NamespaceExistsRequest.java
  rpc/src/main/java/com/scalar/db/rpc/NamespaceExistsResponse.java
  rpc/src/main/java/com/scalar/db/rpc/Ordering.java
  rpc/src/main/java/com/scalar/db/rpc/Result.java
  rpc/src/main/java/com/scalar/db/rpc/Scan.java
  rpc/src/main/java/com/scalar/db/rpc/ScanRequest.java
  rpc/src/main/java/com/scalar/db/rpc/ScanResponse.java
  rpc/src/main/java/com/scalar/db/rpc/TableMetadata.java
  rpc/src/main/java/com/scalar/db/rpc/TableMetadataOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionResponse.java
  rpc/src/main/java/com/scalar/db/rpc/TruncateCoordinatorTablesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TruncateTableRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TwoPhaseCommitTransactionRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TwoPhaseCommitTransactionResponse.java
  rpc/src/main/java/com/scalar/db/rpc/Value.java
Labels: improvement

#586 Implement ScanAll for Consensus Commit
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/AbstractMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
Labels: enhancement

#590 Use dockerize command by default in the Dockerfile
  server/Dockerfile
  server/README.md
  server/build.gradle
  server/conf/database.properties.tmpl
  server/conf/log4j2.properties.tmpl
  server/docker-entrypoint.sh
Labels: improvement

#591 Handle projections in query for Cosmos DB
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
  core/src/main/java/com/scalar/db/storage/cosmos/ResultInterpreter.java
  core/src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java
  core/src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
Labels: improvement
