Repository scalar-labs/scalardb, pull requests merged in 2022-12, with the labels that each got.

#746 Throw TransactionNotFoundException when resuming a transaction but it's not found
  core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/exception/transaction/TransactionNotFoundException.java
  core/src/main/java/com/scalar/db/service/TransactionService.java
  core/src/main/java/com/scalar/db/service/TwoPhaseCommitTransactionService.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionManagerTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManagerTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
Labels: improvement

#749 Update Scheduled Vulnerability Check workflow
  .github/workflows/scheduled-vuln-check.yaml
Labels: improvement

#748 Update the Scalar DB dependency version to 3.7.2
  README.md
  docs/getting-started/build.gradle
  docs/index.md
Labels: documentation

#747 Add note for Put/Delete operation in the API guide
  docs/api-guide.md
Labels: documentation

#750 Deprecate getPartitionKey() and getClusteringKey() of Result
  core/src/main/java/com/scalar/db/api/Result.java
  core/src/main/java/com/scalar/db/common/ResultImpl.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/FilteredResult.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/MergedResult.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionResult.java
Labels: improvement

#751 Remove usages of getPartitionKey() and getClusteringKey() of Result from integration tests
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/util/TestUtils.java
Labels: improvement

#752 Validate contact points size in XxxxConfig to avoid "java.lang.ArrayIndexOutOfBoundsException: 0"
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosConfigTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoConfigTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcConfigTest.java
Labels: improvement

#753 Add ScalarDB Server's license description in the README
  README.md
Labels: documentation

#754 Make integration test bases for transaction extendable
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminRepairTableIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
Labels: improvement

#755 Refactor server integration tests
  integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
  server/build.gradle
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithDistributedTransactionAdminService.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminRepairTableIntegrationTestWithDistributedTransactionAdminService.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithDistributedTransactionService.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceRepairTableIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceColumnValueIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceConditionalMutationIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceMultipleClusteringKeyScanIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceMultiplePartitionKeyIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSecondaryIndexIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSingleClusteringKeyScanIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSinglePartitionKeyIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/SchemaLoaderIntegrationTestWithScalarDbServer.java
  server/src/integration-test/java/com/scalar/db/server/ServerEnv.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithTwoPhaseCommitTransactionService.java
Labels: improvement

#756 Small modifications for Javadoc and comments
  core/src/main/java/com/scalar/db/api/Admin.java
  core/src/main/java/com/scalar/db/api/DistributedStorage.java
  core/src/main/java/com/scalar/db/api/DistributedTransactionAdmin.java
  core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java
  core/src/main/java/com/scalar/db/api/Scanner.java
  core/src/main/java/com/scalar/db/api/TransactionCrudOperable.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/common/TableMetadataManager.java
  core/src/main/java/com/scalar/db/storage/cassandra/BatchHandler.java
  core/src/main/java/com/scalar/db/storage/cassandra/MutateStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cassandra/StatementHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/BatchHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/MutateStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionTableMetadataManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
Labels: improvement

#767 Should close admin in afterEach() in the repair integration tests
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminRepairTableIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminRepairTableIntegrationTestBase.java
Labels: improvement

#760 build(fix): bump-up protobufVersion to 3.21.12 (latest)
  build.gradle
  rpc/src/main/java/com/scalar/db/rpc/AbortRequest.java
  rpc/src/main/java/com/scalar/db/rpc/AbortResponse.java
  rpc/src/main/java/com/scalar/db/rpc/AddNewColumnToTableRequest.java
  rpc/src/main/java/com/scalar/db/rpc/Column.java
  rpc/src/main/java/com/scalar/db/rpc/ConditionalExpression.java
  rpc/src/main/java/com/scalar/db/rpc/CoordinatorTablesExistResponse.java
  rpc/src/main/java/com/scalar/db/rpc/CreateCoordinatorTablesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CreateCoordinatorTablesRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/CreateIndexRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CreateIndexRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/CreateNamespaceRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CreateNamespaceRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/CreateTableRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CreateTableRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/DropCoordinatorTablesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/DropIndexRequest.java
  rpc/src/main/java/com/scalar/db/rpc/DropNamespaceRequest.java
  rpc/src/main/java/com/scalar/db/rpc/DropTableRequest.java
  rpc/src/main/java/com/scalar/db/rpc/Get.java
  rpc/src/main/java/com/scalar/db/rpc/GetNamespaceTableNamesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/GetNamespaceTableNamesResponse.java
  rpc/src/main/java/com/scalar/db/rpc/GetRequest.java
  rpc/src/main/java/com/scalar/db/rpc/GetResponse.java
  rpc/src/main/java/com/scalar/db/rpc/GetTableMetadataRequest.java
  rpc/src/main/java/com/scalar/db/rpc/GetTableMetadataResponse.java
  rpc/src/main/java/com/scalar/db/rpc/GetTransactionStateRequest.java
  rpc/src/main/java/com/scalar/db/rpc/GetTransactionStateResponse.java
  rpc/src/main/java/com/scalar/db/rpc/Key.java
  rpc/src/main/java/com/scalar/db/rpc/MutateCondition.java
  rpc/src/main/java/com/scalar/db/rpc/MutateRequest.java
  rpc/src/main/java/com/scalar/db/rpc/Mutation.java
  rpc/src/main/java/com/scalar/db/rpc/NamespaceExistsRequest.java
  rpc/src/main/java/com/scalar/db/rpc/NamespaceExistsResponse.java
  rpc/src/main/java/com/scalar/db/rpc/Ordering.java
  rpc/src/main/java/com/scalar/db/rpc/RepairCoordinatorTablesRequest.java
  rpc/src/main/java/com/scalar/db/rpc/RepairCoordinatorTablesRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/RepairTableRequest.java
  rpc/src/main/java/com/scalar/db/rpc/RepairTableRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/Result.java
  rpc/src/main/java/com/scalar/db/rpc/RollbackRequest.java
  rpc/src/main/java/com/scalar/db/rpc/RollbackResponse.java
  rpc/src/main/java/com/scalar/db/rpc/Scan.java
  rpc/src/main/java/com/scalar/db/rpc/ScanRequest.java
  rpc/src/main/java/com/scalar/db/rpc/ScanResponse.java
  rpc/src/main/java/com/scalar/db/rpc/TableMetadata.java
  rpc/src/main/java/com/scalar/db/rpc/TableMetadataOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionResponse.java
  rpc/src/main/java/com/scalar/db/rpc/TruncateTableRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TwoPhaseCommitTransactionRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TwoPhaseCommitTransactionResponse.java
  rpc/src/main/java/com/scalar/db/rpc/Value.java
Labels: improvement

#770 Allow to use placeholders in configuration values
  build.gradle
  core/build.gradle
  core/src/main/java/com/scalar/db/config/ConfigUtils.java
  core/src/test/java/com/scalar/db/config/ConfigUtilsTest.java
Labels: enhancement

#771 Refactor prepare logic
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Labels: improvement

#773 Fix CVE-2022-21363 and CVE-2021-2471
  build.gradle
Labels: bugfix

#774 Fix CVE-2022-41946
  build.gradle
Labels: bugfix

#776 Add configurations for gRPC
  core/src/main/java/com/scalar/db/config/ConfigUtils.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcUtils.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionAdmin.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
  core/src/test/java/com/scalar/db/config/ConfigUtilsTest.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcConfigTest.java
  docs/scalardb-server.md
  server/src/main/java/com/scalar/db/server/ScalarDbServer.java
  server/src/main/java/com/scalar/db/server/ServerConfig.java
  server/src/test/java/com/scalar/db/server/ServerConfigTest.java
Labels: enhancement

#775 Refactor validation logic
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ParallelExecutorTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
Labels: improvement

#777 Update the Scalar DB dependency version to 3.7.3
  README.md
  docs/getting-started/build.gradle
  docs/index.md
Labels: documentation

#778 Update Scheduled Vulnerability Check workflow
  .github/workflows/scheduled-vuln-check.yaml
Labels: improvement
