Repository scalar-labs/scalardb, pull requests merged in 2022-01, with the labels that each got.

#445 Support async commit/rollback in Consensus Commit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ParallelExecutorTest.java
Labels: enhancement

#447 Revisit Key construction
  core/src/integration-test/java/com/scalar/db/storage/AdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageIntegrationTestBase.java
  core/src/main/java/com/scalar/db/io/Key.java
  core/src/test/java/com/scalar/db/io/KeyTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/SelectStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosOperationTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcStorageTest.java
  server/src/test/java/com/scalar/db/server/DistributedStorageServiceTest.java
Labels: improvement

#448 Refactor Schema Loader
  schema-loader/README.md
  schema-loader/build.gradle
  schema-loader/sample/schema_sample.json
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/cassandra/CassandraSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/cosmos/CosmosSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/dynamo/DynamoSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/jdbc/JdbcSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoaderException.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaParser.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/CassandraCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/CosmosCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/DynamoCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/JdbcCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/StorageSpecificCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/StorageSpecificCommandBase.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/core/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/core/SchemaOperatorException.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/core/SchemaOperatorFactory.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/schema/SchemaException.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/schema/SchemaParser.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaLoaderTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaParserTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/TableSchemaTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/CassandraCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/CommandTestBase.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/CosmosCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/DynamoCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/JdbcCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/SchemaLoaderCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/StorageSpecificCommandTestBase.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/core/SchemaOperatorTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/schema/TableTest.java
Labels: improvement

#451 Should close FileInputStream in XXXConfig
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  server/src/main/java/com/scalar/db/server/config/ServerConfig.java
Labels: bugfix

#452 Should rollback a transaction when expiring it in Two-phase commit transactions
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
Labels: bugfix

#450 Add A Guide on How to Handle Exceptions
  core/src/main/java/com/scalar/db/api/DistributedTransaction.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
  docs/getting-started-with-scalardb.md
  docs/how-to-handle-exceptions.md
Labels: documentation

#453 Refactor Scalar DB Server code
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/server/SchemaLoaderWithScalarDbServer.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitWithDistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithJdbcTransactionIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/ServerEnv.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitWithExtraReadIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitWithExtraWriteIntegrationTest.java
  server/src/main/java/com/scalar/db/server/Metrics.java
  server/src/main/java/com/scalar/db/server/ScalarDbServer.java
  server/src/main/java/com/scalar/db/server/ServerConfig.java
  server/src/main/java/com/scalar/db/server/ServerModule.java
  server/src/test/java/com/scalar/db/server/ServerConfigTest.java
Labels: documentation

#456 Rename JdbcDatabaseAdmin to JdbcAdmin
  core/src/integration-test/java/com/scalar/db/storage/TestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminIntegrationTest.java
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java
Labels: improvement

#455 Deprecate XXXService classes
  core/src/main/java/com/scalar/db/service/AdminService.java
  core/src/main/java/com/scalar/db/service/StorageFactory.java
  core/src/main/java/com/scalar/db/service/StorageService.java
  core/src/main/java/com/scalar/db/service/TransactionFactory.java
  core/src/main/java/com/scalar/db/service/TransactionService.java
  core/src/main/java/com/scalar/db/service/TwoPhaseCommitTransactionService.java
Labels: improvement

#454 Refactor TableMetadataManager
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
  core/src/main/java/com/scalar/db/storage/cosmos/BatchHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/cosmos/DeleteStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/MutateStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/PutStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/StatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/DeleteStatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/dynamo/PutStatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/StatementHandler.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStream.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionOnBidirectionalStream.java
  core/src/main/java/com/scalar/db/util/TableMetadataManager.java
  core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/BatchHandlerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/DeleteStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/PutStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/StatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/BatchHandlerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DeleteStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/PutStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcStorageTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionManagerTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManagerTest.java
  core/src/test/java/com/scalar/db/util/TableMetadataManagerTest.java
Labels: improvement

#457 Transactions that have multiple scans are always rejected in EXTRA_READ
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
Labels: bugfix

#458 Add connection pool configurations for JdbcAdmin
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcUtilsTest.java
  docs/getting-started-with-scalardb-on-jdbc.md
Labels: enhancement

#459 Support parallel validation for EXTRA_READ in Consensus Commit
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ParallelExecutorTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
Labels: enhancement

#441 Handling namespaces/tables/columns with reserved keywords in Cassandra and JDBC adapters
  core/src/integration-test/java/com/scalar/db/storage/StorageWithReservedKeywordIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraWithReservedKeywordIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseWithReservedKeywordIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cassandra/ClusterManager.java
  core/src/main/java/com/scalar/db/storage/cassandra/ConditionSetter.java
  core/src/main/java/com/scalar/db/storage/cassandra/DeleteStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cassandra/InsertStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cassandra/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cassandra/UpdateStatementHandler.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/ClusterManagerTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/DeleteStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/InsertStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/SelectStatementHandlerTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/UpdateStatementHandlerTest.java
Labels: bugfix

#465 Add TransactionalTableMetadataManager
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionalTableMetadata.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionalTableMetadataManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtilsTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TransactionalTableMetadataManagerTest.java
Labels: enhancement

#462 Handling namespaces/tables/columns with reserved keywords in DynamoDB adapter
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoWithReservedKeywordIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/ConditionExpressionBuilder.java
  core/src/main/java/com/scalar/db/storage/dynamo/DeleteStatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoMutation.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoOperation.java
  core/src/main/java/com/scalar/db/storage/dynamo/PutStatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  core/src/test/java/com/scalar/db/storage/dynamo/ConditionExpressionBuilderTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoMutationTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
Labels: bugfix

#468 Refactor JDBC adapter
  core/src/main/java/com/scalar/db/storage/jdbc/ConditionalMutator.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/AbstractQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/DeleteQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/InsertOnConflictDoUpdateQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/InsertOnDuplicateKeyUpdateQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/InsertQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/MergeIntoQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/MergeQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/Query.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithFetchFirstNRowsOnly.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithLimitQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SelectWithOffsetFetchQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/UpdateQuery.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
Labels: improvement

#461 Handling namespaces/tables/columns with reserved keywords in Cosmos DB adapter
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosWithReservedKeywordIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/cosmos/ConditionalQueryBuilder.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosMutation.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosUtils.java
  core/src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java
  core/src/test/java/com/scalar/db/storage/cosmos/ConditionalQueryBuilderTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosMutationTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
Labels: bugfix

#473 Sort order for Scan without orderings should follow clustering order in Cosmos adapter
  core/src/main/java/com/scalar/db/storage/cosmos/SelectStatementHandler.java
  core/src/test/java/com/scalar/db/storage/cosmos/SelectStatementHandlerTest.java
Labels: improvement

#474 Allow getting already written data in Consensus Commit
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitIntegrationTest.java
Labels: improvement

#475 Rename JDBC integration tests
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseColumnValueIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSecondaryIndexIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSinglePartitionKeyIntegrationTest.java
Labels: improvement

#476 Fix OperationChecker for mutation operations
  core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
  core/src/test/java/com/scalar/db/storage/common/checker/OperationCheckerTest.java
Labels: bugfix

#478 Handle SQL Server conflict error
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
Labels: improvement

#477 Add more integration tests for Scan
  core/src/integration-test/java/com/scalar/db/storage/StorageIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageMultipleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageSingleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/StorageWithReservedKeywordIntegrationTestBase.java
Labels: improvement

#479 Fix Scan logic in CrudHandler in Consensus Commit
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTest.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
Labels: bugfix

#483 Increase no_output_timeout for Cosmos DB adapter CI
  .circleci/config.yml
Labels: improvement
