Repository scalar-labs/scalardb, pull requests merged in 2022-04, with the labels that each got.

#538 Refactor SQL API
  core/src/main/java/com/scalar/db/sql/SqlSession.java
  core/src/main/java/com/scalar/db/sql/SqlStatementSession.java
  core/src/main/java/com/scalar/db/sql/SqlStatementSessionFactory.java
  core/src/main/java/com/scalar/db/sql/StatementValidator.java
  core/src/main/java/com/scalar/db/sql/TransactionSession.java
  core/src/main/java/com/scalar/db/sql/TwoPhaseCommitTransactionSession.java
  core/src/main/java/com/scalar/db/sql/statement/StatementVisitor.java
  core/src/test/java/com/scalar/db/sql/TransactionSessionTest.java
  core/src/test/java/com/scalar/db/sql/TwoPhaseCommitTransactionSessionTest.java
Labels: improvement

#540 Add more methods to SQL builders
  core/src/main/java/com/scalar/db/sql/builder/CreateCoordinatorTableStatementBuilder.java
  core/src/main/java/com/scalar/db/sql/builder/CreateIndexStatementBuilder.java
  core/src/main/java/com/scalar/db/sql/builder/CreateNamespaceStatementBuilder.java
  core/src/main/java/com/scalar/db/sql/builder/CreateTableStatementBuilder.java
  core/src/main/java/com/scalar/db/sql/builder/DropCoordinatorTableStatementBuilder.java
  core/src/main/java/com/scalar/db/sql/builder/DropIndexStatementBuilder.java
  core/src/main/java/com/scalar/db/sql/builder/DropNamespaceStatementBuilder.java
  core/src/main/java/com/scalar/db/sql/builder/DropTableStatementBuilder.java
  core/src/test/java/com/scalar/db/sql/builder/StatementBuilderTest.java
Labels: improvement

#539 Rename metadata cache expiration time configuration name
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/sql/SqlStatementSessionFactory.java
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
  server/src/main/java/com/scalar/db/server/ServerModule.java
Labels: improvement

#542 Support alias in SQL API
  core/src/main/java/com/scalar/db/sql/DmlStatementExecutor.java
  core/src/main/java/com/scalar/db/sql/Projection.java
  core/src/main/java/com/scalar/db/sql/ResultIteratorResultSet.java
  core/src/main/java/com/scalar/db/sql/ResultRecord.java
  core/src/main/java/com/scalar/db/sql/StatementValidator.java
  core/src/main/java/com/scalar/db/sql/builder/SelectStatementBuilder.java
  core/src/main/java/com/scalar/db/sql/builder/StatementBuilder.java
  core/src/main/java/com/scalar/db/sql/statement/SelectStatement.java
  core/src/test/java/com/scalar/db/sql/DmlStatementExecutorTest.java
  core/src/test/java/com/scalar/db/sql/ProjectionTest.java
  core/src/test/java/com/scalar/db/sql/ResultIteratorResultSetTest.java
  core/src/test/java/com/scalar/db/sql/ResultRecordTest.java
  core/src/test/java/com/scalar/db/sql/StatementValidatorTest.java
  core/src/test/java/com/scalar/db/sql/builder/StatementBuilderTest.java
Labels: improvement

#544 Fix `Query condition missed key schema element` error in DynamoDB
  core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTest.java
Labels: bugfix

#543 Cache metadata in SQL API
  core/src/main/java/com/scalar/db/sql/DdlStatementExecutor.java
  core/src/main/java/com/scalar/db/sql/DmlStatementExecutor.java
  core/src/main/java/com/scalar/db/sql/Metadata.java
  core/src/main/java/com/scalar/db/sql/NamespaceMetadata.java
  core/src/main/java/com/scalar/db/sql/SqlStatementSession.java
  core/src/main/java/com/scalar/db/sql/SqlStatementSessionFactory.java
  core/src/main/java/com/scalar/db/sql/SqlUtils.java
  core/src/main/java/com/scalar/db/sql/StatementValidator.java
  core/src/main/java/com/scalar/db/sql/TableMetadata.java
  core/src/main/java/com/scalar/db/sql/TransactionSession.java
  core/src/main/java/com/scalar/db/sql/TwoPhaseCommitTransactionSession.java
  core/src/main/java/com/scalar/db/sql/metadata/ColumnMetadata.java
  core/src/main/java/com/scalar/db/sql/metadata/IndexMetadata.java
  core/src/main/java/com/scalar/db/sql/metadata/Metadata.java
  core/src/main/java/com/scalar/db/sql/metadata/NamespaceMetadata.java
  core/src/main/java/com/scalar/db/sql/metadata/TableMetadata.java
  core/src/test/java/com/scalar/db/sql/DmlStatementExecutorTest.java
  core/src/test/java/com/scalar/db/sql/StatementValidatorTest.java
  core/src/test/java/com/scalar/db/sql/TransactionSessionTest.java
  core/src/test/java/com/scalar/db/sql/TwoPhaseCommitTransactionSessionTest.java
  core/src/test/java/com/scalar/db/sql/metadata/MetadataTest.java
Labels: improvement

#546 Fix typo in the integrationTestTwoPhaseConsensusCommit gradle task name
  .circleci/config.yml
  core/build.gradle
Labels: improvement

#545 Use collectors in Guava
  core/src/main/java/com/scalar/db/sql/ResultRecord.java
  core/src/main/java/com/scalar/db/sql/metadata/TableMetadata.java
Labels: improvement

#547 Support parameterized statement in SQL API
  core/src/main/java/com/scalar/db/sql/Assignment.java
  core/src/main/java/com/scalar/db/sql/BindMarker.java
  core/src/main/java/com/scalar/db/sql/DmlStatementExecutor.java
  core/src/main/java/com/scalar/db/sql/NamedBindMarker.java
  core/src/main/java/com/scalar/db/sql/PositionalBindMarker.java
  core/src/main/java/com/scalar/db/sql/Predicate.java
  core/src/main/java/com/scalar/db/sql/SqlStatementSession.java
  core/src/main/java/com/scalar/db/sql/SqlUtils.java
  core/src/main/java/com/scalar/db/sql/StatementValidator.java
  core/src/main/java/com/scalar/db/sql/Term.java
  core/src/main/java/com/scalar/db/sql/Value.java
  core/src/main/java/com/scalar/db/sql/builder/SelectStatementBuilder.java
  core/src/main/java/com/scalar/db/sql/statement/BindableStatement.java
  core/src/main/java/com/scalar/db/sql/statement/DeleteStatement.java
  core/src/main/java/com/scalar/db/sql/statement/InsertStatement.java
  core/src/main/java/com/scalar/db/sql/statement/SelectStatement.java
  core/src/main/java/com/scalar/db/sql/statement/TruncateCoordinatorTableStatement.java
  core/src/main/java/com/scalar/db/sql/statement/UpdateStatement.java
  core/src/test/java/com/scalar/db/sql/AssignmentTest.java
  core/src/test/java/com/scalar/db/sql/DmlStatementExecutorTest.java
  core/src/test/java/com/scalar/db/sql/PredicateTest.java
  core/src/test/java/com/scalar/db/sql/ResultIteratorResultSetTest.java
  core/src/test/java/com/scalar/db/sql/ResultRecordTest.java
  core/src/test/java/com/scalar/db/sql/StatementValidatorTest.java
  core/src/test/java/com/scalar/db/sql/TransactionSessionTest.java
  core/src/test/java/com/scalar/db/sql/builder/StatementBuilderTest.java
  core/src/test/java/com/scalar/db/sql/statement/DeleteStatementTest.java
  core/src/test/java/com/scalar/db/sql/statement/InsertStatementTest.java
  core/src/test/java/com/scalar/db/sql/statement/SelectStatementTest.java
  core/src/test/java/com/scalar/db/sql/statement/UpdateStatementTest.java
Labels: enhancement

#551 Update the base image jre8 to 1.1.0
  schema-loader/Dockerfile
  server/Dockerfile
Labels: improvement

#548 Introduce ScanAll operation
  core/src/main/java/com/scalar/db/api/Scan.java
  core/src/main/java/com/scalar/db/api/ScanAll.java
  core/src/main/java/com/scalar/db/io/Key.java
Labels: enhancement

#550 Fix SQL syntax error that happens when scanning a table without clustering key in JDBC adapter
  core/src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
Labels: bugfix

#549 Invalidate metadata cache when schema change happens in SQL API
  core/src/main/java/com/scalar/db/sql/DdlStatementExecutor.java
  core/src/main/java/com/scalar/db/sql/SqlStatementSessionFactory.java
  core/src/main/java/com/scalar/db/sql/TransactionSession.java
  core/src/main/java/com/scalar/db/sql/TwoPhaseCommitTransactionSession.java
  core/src/main/java/com/scalar/db/sql/metadata/CachedMetadata.java
  core/src/main/java/com/scalar/db/sql/metadata/CachedNamespaceMetadata.java
  core/src/main/java/com/scalar/db/sql/metadata/ColumnMetadata.java
  core/src/main/java/com/scalar/db/sql/metadata/ColumnMetadataImpl.java
  core/src/main/java/com/scalar/db/sql/metadata/IndexMetadata.java
  core/src/main/java/com/scalar/db/sql/metadata/IndexMetadataImpl.java
  core/src/main/java/com/scalar/db/sql/metadata/Metadata.java
  core/src/main/java/com/scalar/db/sql/metadata/NamespaceMetadata.java
  core/src/main/java/com/scalar/db/sql/metadata/TableMetadata.java
  core/src/main/java/com/scalar/db/sql/metadata/TableMetadataImpl.java
  core/src/test/java/com/scalar/db/sql/DdlStatementExecutorTest.java
  core/src/test/java/com/scalar/db/sql/DmlStatementExecutorTest.java
  core/src/test/java/com/scalar/db/sql/StatementValidatorTest.java
  core/src/test/java/com/scalar/db/sql/metadata/CachedMetadataTest.java
Labels: improvement

#554 Change Gradle dependencies format
  README.md
  core/build.gradle
  docs/getting-started-with-scalardb.md
  docs/index.md
  rpc/build.gradle
  schema-loader/README.md
  schema-loader/build.gradle
  server/build.gradle
Labels: improvement

#552 Add validations for create table statements in SQL API
  core/src/main/java/com/scalar/db/sql/StatementValidator.java
  core/src/test/java/com/scalar/db/sql/StatementValidatorTest.java
Labels: improvement

#541 Migrate CI to GitHub actions
  .circleci/config.yml
  .github/workflows/ci.yaml
  README.md
Labels: improvement

#556 Update CI status badge in index.md
  docs/index.md
Labels: documentation

#557 Trigger CI for "push" event on the master branch
  .github/workflows/ci.yaml
Labels: improvement

#560 Update the base image jre8 to 1.1.1
  schema-loader/Dockerfile
  server/Dockerfile
Labels: improvement

#559 Add transaction integration tests
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitSpecificIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/TwoPhaseConsensusCommitIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/TwoPhaseConsensusCommitSpecificIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitSpecificIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitSpecificIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitSpecificIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/TwoPhaseConsensusCommitIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/TwoPhaseConsensusCommitSpecificIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitSpecificIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/TwoPhaseConsensusCommitIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/TwoPhaseConsensusCommitSpecificIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/ConsensusCommitSpecificIntegrationTestWithMultiStorage.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitSpecificIntegrationTestWithDistributedStorageService.java
Labels: improvement

#561 Release SNAPSHOT versions
  .github/workflows/release-snapshot.yaml
  .github/workflows/release.yaml
Labels: enhancement

#562 Upgrade grpc_health_probe
  server/Dockerfile
Labels: bugfix

#563 Upgrade PostgreSQL driver
  build.gradle
Labels: bugfix

#564 Upgrade Cosmos DB client
  build.gradle
Labels: bugfix

#565 Rearrange schema loader integration tests
  schema-loader/build.gradle
  schema-loader/src/integration-test/java/com/scalar/db/server/SchemaLoaderWithScalarDbServer.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSchemaLoaderIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSchemaLoaderIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageSchemaLoaderIntegrationTest.java
Labels: improvement

#566 Rearrange server integration tests
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageColumnValueIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageConditionalMutationIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageMultipleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageMultiplePartitionKeyIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageSecondaryIndexIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageSingleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageSinglePartitionKeyIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
  core/src/main/java/com/scalar/db/util/ProtoUtils.java
  server/build.gradle
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithDistributedStorageService.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceColumnValueIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceConditionalMutationIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceMultipleClusteringKeyScanIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceMultiplePartitionKeyIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSecondaryIndexIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSingleClusteringKeyScanIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSinglePartitionKeyIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraReadIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithConsensusCommitWithExtraWriteIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionServiceWithJdbcTransactionIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitWithExtraReadIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceWithTwoPhaseConsensusCommitWithExtraWriteIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithDistributedStorageService.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitSpecificIntegrationTestWithDistributedStorageService.java
Labels: improvement

#567 Add integration tests for SQL API
  build.gradle
  core/build.gradle
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageWithReservedKeywordIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/sql/SqlStatementWithTransactionSessionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/sql/SqlStatementWithTwoPhaseCommitTransactionSessionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/SqlStatementWithTransactionSessionIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/SqlStatementWithTwoPhaseCommitTransactionSessionIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/SqlStatementWithTransactionSessionIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/SqlStatementWithTwoPhaseCommitTransactionSessionIntegrationTestCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/SqlStatementWithTransactionSessionIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/SqlStatementWithTwoPhaseCommitTransactionSessionIntegrationTestDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/SqlStatementWithTransactionSessionIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/SqlStatementWithTwoPhaseCommitTransactionSessionIntegrationTestWithJdbcDatabase.java
  core/src/main/java/com/scalar/db/sql/ResultRecord.java
  core/src/main/java/com/scalar/db/sql/SqlStatementSessionFactory.java
  core/src/main/java/com/scalar/db/sql/builder/SelectStatementBuilder.java
  core/src/main/java/com/scalar/db/sql/builder/StatementBuilder.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/test/java/com/scalar/db/sql/builder/StatementBuilderTest.java
Labels: improvement

#568 Add docker check to CI
  .github/workflows/ci.yaml
  ci/scripts/dockerfile_lint.sh
  schema-loader/Dockerfile
  schema-loader/build.gradle
  server/build.gradle
Labels: improvement

#569 Add ifNotExists and ifExists flags to RPC
  core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcAdminTest.java
  rpc/src/main/java/com/scalar/db/rpc/CreateIndexRequest.java
  rpc/src/main/java/com/scalar/db/rpc/CreateIndexRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/DropIndexRequest.java
  rpc/src/main/java/com/scalar/db/rpc/DropIndexRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/DropNamespaceRequest.java
  rpc/src/main/java/com/scalar/db/rpc/DropNamespaceRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/DropTableRequest.java
  rpc/src/main/java/com/scalar/db/rpc/DropTableRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java
  rpc/src/main/proto/scalardb.proto
  server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java
  server/src/test/java/com/scalar/db/server/DistributedStorageAdminServiceTest.java
Labels: improvement

#572 Add CI triggers for "push" events on support and release branches
  .github/workflows/ci.yaml
Labels: improvement
