Repository scalar-labs/scalardb, pull requests merged in 2022-08, with the labels that each got.

#645 In the Admin create and drop index methods, alter column type if necessary
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
  schema-loader/README.md
Labels: bugfix

#646 Refactor documents
  README.md
  docs/api-guide.md
  docs/backup-restore.md
  docs/getting-started-with-scalardb.md
  docs/index.md
  docs/scalardb-server.md
  docs/storage-abstraction.md
  docs/two-phase-commit-transactions.md
  rpc/src/main/proto/scalardb.proto
  server/build.gradle
  server/src/main/java/com/scalar/db/server/ScalarDbServer.java
Labels: documentation

#644 Update Two-phase Commit Transactions document
  docs/design.md
  docs/images/data_model.png
  docs/images/two_phase_commit_load_balancing.png
  docs/images/two_phase_commit_sequence_diagram.png
  docs/two-phase-commit-transactions.md
Labels: documentation

#650 Fix CVE-2022-31197 affecting PostgreSQL driver
  build.gradle
Labels: bugfix

#653 Fix CVE-2021-46828 by bumping the jre8 dependency version
  schema-loader/Dockerfile
  server/Dockerfile
Labels: bugfix

#654 Fix CVE-2022-2509
  schema-loader/Dockerfile
  server/Dockerfile
Labels: bugfix

#652 Admin "repairTable()" handle metadata corruption
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageAdminRepairTableIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionAdminRepairTableIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminRepairTableIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminRepairTableIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/util/AdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/util/CassandraAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/util/CosmosAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/util/DynamoAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/util/JdbcAdminTestUtils.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
Labels: improvement

#651 Refactor TableMetadataManager
  core/src/main/java/com/scalar/db/common/TableMetadataManager.java
  core/src/main/java/com/scalar/db/util/ThrowableFunction.java
  core/src/test/java/com/scalar/db/common/TableMetadataManagerTest.java
Labels: improvement

#648 Add alter table command to Schema Loader tool
  schema-loader/README.md
  schema-loader/sample/altered_schema_sample.json
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/alteration/TableMetadataAlteration.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/alteration/TableMetadataAlterationProcessor.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/CassandraCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/CosmosCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/DynamoCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/JdbcCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/StorageSpecificCommand.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaLoaderTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/alteration/TableMetadataAlterationProcessorTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/CassandraCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/CosmosCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/DynamoCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/JdbcCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/SchemaLoaderCommandTest.java
Labels: enhancement

#656 Add begin() and rollback() methods to Distributed Transaction API
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionIntegrationTest.java
  core/src/main/java/com/scalar/db/api/DistributedTransaction.java
  core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java
  core/src/main/java/com/scalar/db/service/TransactionService.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransaction.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStream.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionManagerTest.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionGrpc.java
  rpc/src/main/java/com/scalar/db/rpc/RollbackRequest.java
  rpc/src/main/java/com/scalar/db/rpc/RollbackRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/RollbackResponse.java
  rpc/src/main/java/com/scalar/db/rpc/RollbackResponseOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionResponse.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionResponseOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/Value.java
  rpc/src/main/proto/scalardb.proto
  server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
  server/src/test/java/com/scalar/db/server/DistributedTransactionServiceTest.java
Labels: enhancement

#657 Add begin() and abort() to Two-phase Commit Transaction API
  core/src/integration-test/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/service/TwoPhaseCommitTransactionService.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionOnBidirectionalStream.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManagerTest.java
  rpc/src/main/grpc/com/scalar/db/rpc/TwoPhaseCommitTransactionGrpc.java
  rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java
  rpc/src/main/java/com/scalar/db/rpc/TwoPhaseCommitTransactionRequest.java
  rpc/src/main/java/com/scalar/db/rpc/TwoPhaseCommitTransactionRequestOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/TwoPhaseCommitTransactionResponse.java
  rpc/src/main/java/com/scalar/db/rpc/TwoPhaseCommitTransactionResponseOrBuilder.java
  rpc/src/main/proto/scalardb.proto
  server/src/main/java/com/scalar/db/server/TwoPhaseCommitTransactionService.java
  server/src/test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceTest.java
Labels: enhancement

#659 Add @Nullable to Admin.getTableMetadata()
  core/src/main/java/com/scalar/db/api/Admin.java
Labels: improvement

#658 Add namespace prefix support for Dynamo
  core/src/integration-test/java/com/scalar/db/util/DynamoAdminTestUtils.java
  core/src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/DeleteStatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java
  core/src/main/java/com/scalar/db/storage/dynamo/Namespace.java
  core/src/main/java/com/scalar/db/storage/dynamo/PutStatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  core/src/test/java/com/scalar/db/storage/dynamo/BatchHandleWithNamespacePrefixTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/BatchHandleWithoutNamespacePrefixTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/BatchHandlerTestBase.java
  core/src/test/java/com/scalar/db/storage/dynamo/DeleteStatementHandlerTestBase.java
  core/src/test/java/com/scalar/db/storage/dynamo/DeleteStatementHandlerWithPrefixTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DeleteStatementHandlerWithoutPrefixTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminWithDefaultConfigTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminWithNamespacePrefixAndTableMetadataNamespaceConfigTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminWithNamespacePrefixConfigTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoConfigTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/PutStatementHandlerTestBase.java
  core/src/test/java/com/scalar/db/storage/dynamo/PutStatementHandlerWithPrefixTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/PutStatementHandlerWithoutPrefixTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerTestBase.java
  core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerWithPrefixTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/SelectStatementHandlerWithoutPrefixTest.java
  docs/getting-started-with-scalardb-on-dynamodb.md
Labels: enhancement

#664 Remove readthedocs
  .readthedocs.yml
  mkdocs.yml
Labels: documentation

#663 Refactor server integration tests
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageAdminRepairTableIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageColumnValueIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageConditionalMutationIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageMultipleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageMultiplePartitionKeyIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageSecondaryIndexIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageSingleClusteringKeyScanIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedStorageSinglePartitionKeyIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionAdminRepairTableIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminRepairTableIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTestBase.java
  schema-loader/src/integration-test/java/com/scalar/db/server/SchemaLoaderWithScalarDbServer.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithDistributedStorageService.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithDistributedTransactionAdminService.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminRepairTableIntegrationTestWithDistributedTransactionAdminService.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithDistributedStorageService.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithDistributedTransactionService.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitSpecificIntegrationTestWithDistributedStorageService.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceRepairTableIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceColumnValueIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceConditionalMutationIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceMultipleClusteringKeyScanIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceMultiplePartitionKeyIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSecondaryIndexIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSingleClusteringKeyScanIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSinglePartitionKeyIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedTransactionAdminServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/ServerEnv.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithDistributedStorageService.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithTwoPhaseCommitTransactionService.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitSpecificIntegrationTestWithDistributedStorageService.java
  server/src/main/java/com/scalar/db/server/ScalarDbServer.java
Labels: improvement

#665 Move Schema Loader document to docs directory
  README.md
  docs/api-guide.md
  docs/getting-started-with-scalardb.md
  docs/index.md
  docs/schema-loader.md
  docs/storage-abstraction.md
Labels: documentation

#666 Use toUpperCase() for valueOf() of enum type
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
Labels: improvement

#661 Use ServiceLoader to load storage and transaction modules
  core/src/main/java/com/scalar/db/api/DistributedStorageFactory.java
  core/src/main/java/com/scalar/db/api/DistributedTransactionFactory.java
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/service/FactoryManager.java
  core/src/main/java/com/scalar/db/service/StorageFactory.java
  core/src/main/java/com/scalar/db/service/StorageModule.java
  core/src/main/java/com/scalar/db/service/TransactionFactory.java
  core/src/main/java/com/scalar/db/service/TransactionModule.java
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraFactory.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosFactory.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoFactory.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcFactory.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageFactory.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcFactory.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitFactory.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionFactory.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionFactory.java
  core/src/main/resources/META-INF/services/com.scalar.db.api.DistributedStorageFactory
  core/src/main/resources/META-INF/services/com.scalar.db.api.DistributedTransactionFactory
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTest.java
  core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageConfigTest.java
Labels: improvement

#667 Improve error messages in OperationChecker
  core/src/main/java/com/scalar/db/storage/common/checker/OperationChecker.java
Labels: improvement

#669 Add logging for UnknownTransactionStatusException in Scalar DB Server
  server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
  server/src/main/java/com/scalar/db/server/TwoPhaseCommitTransactionService.java
Labels: improvement

#670 Refactor JdbcAdminTest
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminWithDefaultConfigTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminWithTableMetadataSchemaConfigTest.java
Labels: improvement

#671 Refactor CosmosAdminTest
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTableMetadataDatabaseConfigTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminWithDefaultConfigTest.java
Labels: improvement

#672 Rename endpoint override config in Dynamo
  core/build.gradle
  core/src/integration-test/java/com/scalar/db/storage/multistorage/ConsensusCommitSpecificIntegrationTestWithMultiStorage.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoConfigTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageSchemaLoaderIntegrationTest.java
Labels: improvement

#677 Fix CVE-2022-37434
  schema-loader/Dockerfile
  server/Dockerfile
Labels: bugfix

#676 Enable parallel/async commit by default
  core/src/integration-test/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminRepairTableIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTestBase.java
  core/src/integration-test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
  docs/configurations-for-consensus-commit.md
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithDistributedTransactionAdminService.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminRepairTableIntegrationTestWithDistributedTransactionAdminService.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithDistributedTransactionService.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithTwoPhaseCommitTransactionService.java
Labels: improvement

#673 Refactor schema loader integration tests
  .github/workflows/ci.yaml
  schema-loader/build.gradle
  schema-loader/src/integration-test/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderWithStorageSpecificArgsIntegrationTest.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/StorageSpecificCommand.java
  server/build.gradle
  server/src/integration-test/java/com/scalar/db/server/SchemaLoaderIntegrationTestWithScalarDbServer.java
Labels: improvement
