Repository scalar-labs/scalardb, pull requests merged in 2022-10, with the labels that each got.

#715 Remove suspend() from TwoPhaseCommitTransactionManager
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/service/TwoPhaseCommitTransactionService.java
  core/src/main/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/util/ActiveExpiringMap.java
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManagerTest.java
  docs/two-phase-commit-transactions.md
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithDistributedTransactionAdminService.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminRepairTableIntegrationTestWithDistributedTransactionAdminService.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithDistributedTransactionService.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceRepairTableIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceColumnValueIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceConditionalMutationIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceMultipleClusteringKeyScanIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceMultiplePartitionKeyIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSecondaryIndexIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSingleClusteringKeyScanIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSinglePartitionKeyIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/SchemaLoaderIntegrationTestWithScalarDbServer.java
  server/src/integration-test/java/com/scalar/db/server/ServerEnv.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithTwoPhaseCommitTransactionService.java
Labels: enhancement (backward-incompatible)

#717 Add resume() to DistributedTransactionManager
  core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java
  core/src/main/java/com/scalar/db/service/TransactionService.java
  core/src/main/java/com/scalar/db/transaction/common/AbstractDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionManagerTest.java
  docs/api-guide.md
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Labels: enhancement

#720 Should check the value range of BigIntColumn
  core/src/main/java/com/scalar/db/io/BigIntColumn.java
  core/src/test/java/com/scalar/db/api/PutBuilderTest.java
  core/src/test/java/com/scalar/db/io/BigIntColumnTest.java
Labels: bugfix

#719 Add transaction state management
  core/src/main/java/com/scalar/db/transaction/common/AbstractDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/common/WrappedDistributedTransaction.java
  core/src/main/java/com/scalar/db/transaction/common/WrappedTwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
  core/src/test/java/com/scalar/db/transaction/common/AbstractDistributedTransactionManagerTest.java
  core/src/test/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransactionManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
Labels: improvement

#718 Should throw IllegalStateException when transaction is not found and already exists
  core/src/main/java/com/scalar/db/transaction/common/AbstractDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionManagerTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManagerTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
Labels: improvement

#721 Add description of limitations of data types
  docs/schema-loader.md
Labels: documentation

#722 Add several methods to ActiveExpiringMap
  core/src/main/java/com/scalar/db/util/ActiveExpiringMap.java
  core/src/test/java/com/scalar/db/util/ActiveExpiringMapTest.java
Labels: enhancement

#724 Small integration test modifications for the resume feature
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
Labels: improvement

#723 Separate active transaction management from AbstractDistributedTransactionManager and AbstractTwoPhaseCommitTransactionManager
  core/src/main/java/com/scalar/db/transaction/common/AbstractDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/common/AbstractTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/common/ActiveTransactionManagedTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
Labels: improvement

#725 Fix the broken link in the backup document
  docs/backup-restore.md
Labels: documentation

#727 Fix CVE-2022-32149
  server/Dockerfile
Labels: bugfix

#726 Fix CVE-2022-42003 and CVE-2022-42004
  build.gradle
  core/build.gradle
Labels: bugfix
