Repository scalar-labs/scalardb, pull requests merged in 2023-04, with the labels that each got.

#836 Add `@Nullable` in ConfigUtils
  core/src/main/java/com/scalar/db/config/ConfigUtils.java
Labels: improvement

#835 Add SLF4J Simple Binding to sample application
  docs/getting-started/build.gradle
Labels: improvement

#819 feat: SQLite support implementations and tests
  .github/workflows/ci.yaml
  build.gradle
  core/build.gradle
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineFactory.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/RdbEngine.java
  core/src/test/java/com/scalar/db/storage/jdbc/RdbEngineSqliteTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
Labels: enhancement

#839 Push SNAPSHOT version container images
  .github/workflows/release-snapshot.yaml
Labels: improvement

#762 feat: SQLite support via JDBC
  .github/workflows/ci.yaml
  build.gradle
  core/build.gradle
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineFactory.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/RdbEngine.java
  core/src/test/java/com/scalar/db/storage/jdbc/RdbEngineSqliteTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
  docs/backup-restore.md
  docs/getting-started-with-scalardb-on-jdbc.md
  docs/scalardb-supported-databases.md
  docs/schema-loader.md
Labels: enhancement

#840 Update supported Java version in getting started
  docs/getting-started-with-scalardb-on-cassandra.md
  docs/getting-started-with-scalardb-on-cosmosdb.md
  docs/getting-started-with-scalardb-on-dynamodb.md
  docs/getting-started-with-scalardb-on-jdbc.md
  docs/getting-started/gradle/wrapper/gradle-wrapper.properties
Labels: improvement

#843 Enable dependabot
  .github/dependabot.yml
Labels: improvement

#844 Allow to create `before_` prefixed columns in Consensus Commit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionTableMetadata.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TransactionTableMetadataManagerTest.java
Labels: bugfix

#845 Fix Error Prone warnings
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminIntegrationTest.java
Labels: improvement

#851 Add decommissioning state to ScalarDB Server
  docs/scalardb-server.md
  server/src/main/java/com/scalar/db/server/HealthService.java
  server/src/main/java/com/scalar/db/server/ScalarDbServer.java
  server/src/main/java/com/scalar/db/server/ServerConfig.java
  server/src/test/java/com/scalar/db/server/ServerConfigTest.java
Labels: improvement

#852 Add computeIfXXX methods to ActiveExpiringMap
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/util/ActiveExpiringMap.java
  core/src/test/java/com/scalar/db/util/ActiveExpiringMapTest.java
Labels: improvement

#854 Apply workaround on CI for Dependabot
  .github/workflows/ci.yaml
Labels: improvement

#853 Clarify instructions in docs
  docs/add-scalardb-to-your-build.md
  docs/getting-started-with-scalardb.md
  docs/index.md
Labels: documentation

#862 Update dependencies
  build.gradle
Labels: improvement

#856 Unify admin behavior
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminIntegrationTest.java
  core/src/main/java/com/scalar/db/api/Admin.java
  core/src/main/java/com/scalar/db/api/DistributedTransactionAdmin.java
  core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraProvider.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosProvider.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoProvider.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcProvider.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdmin.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminRepairTableIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminRepairTableIntegrationTestBase.java
Labels: improvement

#864 Reduce IntelliJ warnings
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosOperation.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/MergeQuery.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
Labels: improvement

#865 [Dependabot] Ignore patch versions for Aws sdk
  .github/dependabot.yml
Labels: improvement

#866 Update the Scalar DB dependency version to 3.9.0
  README.md
  docs/getting-started/build.gradle
  docs/index.md
Labels: documentation

#867 Update Scheduled Vulnerability Check workflow
  .github/workflows/scheduled-vuln-check.yaml
Labels: improvement

#863 Set empty value by default in properties file
  server/Dockerfile
  server/conf/database.properties
Labels: enhancement (backward-incompatible)
