Repository scalar-labs/scalardb, pull requests merged in 2023-03, with the labels that each got.

#823 Add default namespace config
  conf/database.properties
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageIntegrationTest.java
  core/src/main/java/com/scalar/db/common/AbstractDistributedStorage.java
  core/src/main/java/com/scalar/db/common/AbstractDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/AbstractTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorage.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcStorage.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java
  core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageTest.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcStorageTest.java
  docs/api-guide.md
  docs/storage-abstraction.md
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
Labels: enhancement

#826 Make overridden methods throw Exception in integration tests
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminRepairTableIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageColumnValueIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageConditionalMutationIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageSecondaryIndexIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageSingleClusteringKeyScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageSinglePartitionKeyIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageWithReservedKeywordIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminRepairTableIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithDistributedTransactionAdminService.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithDistributedTransactionService.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceColumnValueIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceConditionalMutationIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSecondaryIndexIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSingleClusteringKeyScanIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageServiceSinglePartitionKeyIntegrationTest.java
  server/src/integration-test/java/com/scalar/db/server/SchemaLoaderIntegrationTestWithScalarDbServer.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithTwoPhaseCommitTransactionService.java
Labels: improvement

#825 Add repair section for cosmosdb restore
  docs/backup-restore.md
Labels: documentation

#827 Rename integration test classes for Server
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminRepairTableIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminRepairTableIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageColumnValueIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageConditionalMutationIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageMultipleClusteringKeyScanIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageMultiplePartitionKeyIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageSecondaryIndexIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageSingleClusteringKeyScanIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageSinglePartitionKeyIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/SchemaLoaderIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithServer.java
Labels: improvement

#828 Fix typo
  .github/workflows/release-snapshot.yaml
Labels: bugfix

#830 Add transaction ID to exceptions
  core/src/main/java/com/scalar/db/api/DistributedTransaction.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/exception/transaction/AbortException.java
  core/src/main/java/com/scalar/db/exception/transaction/CommitConflictException.java
  core/src/main/java/com/scalar/db/exception/transaction/CommitException.java
  core/src/main/java/com/scalar/db/exception/transaction/CrudConflictException.java
  core/src/main/java/com/scalar/db/exception/transaction/CrudException.java
  core/src/main/java/com/scalar/db/exception/transaction/PreparationConflictException.java
  core/src/main/java/com/scalar/db/exception/transaction/PreparationException.java
  core/src/main/java/com/scalar/db/exception/transaction/RollbackException.java
  core/src/main/java/com/scalar/db/exception/transaction/TransactionException.java
  core/src/main/java/com/scalar/db/exception/transaction/TransactionNotFoundException.java
  core/src/main/java/com/scalar/db/exception/transaction/UnknownTransactionStatusException.java
  core/src/main/java/com/scalar/db/exception/transaction/ValidationConflictException.java
  core/src/main/java/com/scalar/db/exception/transaction/ValidationException.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/UncommittedRecordException.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStream.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionOnBidirectionalStream.java
  server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
  server/src/main/java/com/scalar/db/server/TwoPhaseCommitTransactionService.java
Labels: improvement

#834 Fix CVE-2023-0361 and CVE-2022-41723
  schema-loader/Dockerfile
  server/Dockerfile
Labels: bugfix

#832 Explicitly specify driver class in JDBC adapter
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTestUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcUtilsTest.java
  server/src/integration-test/java/com/scalar/db/server/ServerAdminTestUtils.java
Labels: improvement
