Repository scalar-labs/scalardb, pull requests merged in 2023-01, with the labels that each got.

#761 docs: Clearer description on when to use online backups
  docs/backup-restore.md
Labels: documentation

#765 docs: add SQLite data type mapping in schema-loader doc
  docs/schema-loader.md
Labels: documentation

#781 Add transaction decorator
  core/src/main/java/com/scalar/db/common/AbstractDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/AbstractTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/common/DecoratedDistributedTransaction.java
  core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/common/DistributedTransactionDecorator.java
  core/src/main/java/com/scalar/db/common/TwoPhaseCommitTransactionDecorator.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
Labels: improvement

#779 Add description how to build docker image of ScalarDB Server
  docs/scalardb-server.md
Labels: documentation

#780 Remove dockerize command from container image
  docs/scalardb-server.md
  server/Dockerfile
  server/build.gradle
  server/conf/database.properties
  server/conf/log4j2.properties
Labels: enhancement (backward-incompatible)

#783 Revisit commit and abort state logic
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CoordinatorConflictException.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
Labels: improvement

#782 fix: DynamoAdmin.namespaceExists to check full namespace (not prefix)
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
Labels: bugfix

#785 Should synchronize in active transaction management
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
Labels: improvement

#786 Allow commit() and rollback() to be called in parallel in all coordinator/participant processes in 2PC transactions
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
  docs/two-phase-commit-transactions.md
Labels: improvement

#792 Load admins lazily in Schema Loader
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
Labels: improvement

#793 Should care about ScanWithIndex in ScalarDbUtils.copyAndSetTargetToIfNot()
  core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
  core/src/test/java/com/scalar/db/util/ScalarDbUtilsTest.java
Labels: bugfix

#794 Fix CVE-2022-42898
  schema-loader/Dockerfile
  server/Dockerfile
Labels: bugfix

#795 Rename Scalar DB to ScalarDB
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/ci.yaml
  .github/workflows/vuln-check.yaml
  README.md
  core/archive.gradle
  core/build.gradle
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosTableMetadata.java
  core/src/main/java/com/scalar/db/storage/cosmos/Record.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcConfig.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcConfigTest.java
  docs/api-guide.md
  docs/backup-restore.md
  docs/configurations-for-consensus-commit.md
  docs/design.md
  docs/getting-started-with-scalardb-on-cassandra.md
  docs/getting-started-with-scalardb-on-cosmosdb.md
  docs/getting-started-with-scalardb-on-dynamodb.md
  docs/getting-started-with-scalardb-on-jdbc.md
  docs/getting-started-with-scalardb.md
  docs/getting-started.md
  docs/index.md
  docs/multi-storage-transactions.md
  docs/requirements.md
  docs/scalardb-server.md
  docs/scalardb-supported-databases.md
  docs/schema-loader.md
  docs/storage-abstraction.md
  docs/two-phase-commit-transactions.md
  integration-test/archive.gradle
  integration-test/build.gradle
  rpc/archive.gradle
  rpc/build.gradle
  schema-loader/archive.gradle
  schema-loader/build.gradle
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  server/archive.gradle
  server/build.gradle
  server/src/main/java/com/scalar/db/server/ScalarDbServer.java
  tla+/consensus-commit/README.md
Labels: improvement

#796 DynamoDB supports up to 100 actions per transaction
  build.gradle
  core/src/main/java/com/scalar/db/storage/dynamo/BatchHandler.java
  core/src/test/java/com/scalar/db/storage/dynamo/BatchHandlerTestBase.java
Labels: improvement

#797 Revert async commit default value
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
  docs/configurations-for-consensus-commit.md
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminRepairTableIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithDistributedTransactionAdminService.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminRepairTableIntegrationTestWithDistributedTransactionAdminService.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithDistributedTransactionService.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithTwoPhaseCommitTransactionService.java
Labels: improvement

#787 refactor: use strategy pattern to avoid branching by `RdbEngine` in `JdbcAdmin`
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseColumnValueIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseConditionalMutationIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSecondaryIndexIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSinglePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTestUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  server/src/integration-test/java/com/scalar/db/server/ServerAdminTestUtils.java
Labels: improvement

#799 Update the Scalar DB dependency version to 3.8.0
  README.md
  docs/getting-started/build.gradle
  docs/index.md
Labels: documentation

#800 Update Scheduled Vulnerability Check workflow
  .github/workflows/scheduled-vuln-check.yaml
Labels: improvement

#802 Increase Trivy timeout
  .github/workflows/vuln-check.yaml
Labels: improvement

#801 Update dependency and plugin versions
  .github/workflows/ci.yaml
  build.gradle
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageAdminGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionAdminGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/TwoPhaseCommitTransactionGrpc.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/CassandraCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/CosmosCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/DynamoCommandTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/JdbcCommandTest.java
  server/src/main/java/com/scalar/db/server/AdminService.java
Labels: improvement

#788 refactor: avoid branching by SQLSTATE or error codes
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseColumnValueIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseConditionalMutationIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSecondaryIndexIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSinglePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTestUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/ConditionalMutator.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/alteration/TableMetadataAlterationProcessorTest.java
  server/src/integration-test/java/com/scalar/db/server/ServerAdminTestUtils.java
Labels: improvement

#804 Update transaction documents
  core/src/main/java/com/scalar/db/api/DistributedTransaction.java
  core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java
  core/src/main/java/com/scalar/db/api/TransactionCrudOperable.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/exception/transaction/AbortException.java
  core/src/main/java/com/scalar/db/exception/transaction/CommitConflictException.java
  core/src/main/java/com/scalar/db/exception/transaction/CommitException.java
  core/src/main/java/com/scalar/db/exception/transaction/CrudConflictException.java
  core/src/main/java/com/scalar/db/exception/transaction/CrudException.java
  core/src/main/java/com/scalar/db/exception/transaction/PreparationConflictException.java
  core/src/main/java/com/scalar/db/exception/transaction/PreparationException.java
  core/src/main/java/com/scalar/db/exception/transaction/RollbackException.java
  core/src/main/java/com/scalar/db/exception/transaction/TransactionException.java
  core/src/main/java/com/scalar/db/exception/transaction/TransactionNotFoundException.java
  core/src/main/java/com/scalar/db/exception/transaction/UnknownTransactionStatusException.java
  core/src/main/java/com/scalar/db/exception/transaction/ValidationConflictException.java
  core/src/main/java/com/scalar/db/exception/transaction/ValidationException.java
  docs/api-guide.md
  docs/two-phase-commit-transactions.md
Labels: improvement

#790 refactor: remove `RdbEngine rdbEngineType` field from `JdbcAdmin`
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
Labels: improvement

#807 Remove the log "mutation seems applied already"
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
Labels: improvement

#791 refactor: change `RdbEngineStrategy` from `abstract class` to `interface`
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseColumnValueIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseConditionalMutationIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSecondaryIndexIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSinglePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTestUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/ConditionalMutator.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineFactory.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/DeleteQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/InsertOnConflictDoUpdateQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/InsertOnDuplicateKeyUpdateQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/InsertQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/MergeIntoQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/MergeQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/QueryUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/UpdateQuery.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
  server/src/integration-test/java/com/scalar/db/server/ServerAdminTestUtils.java
Labels: improvement

#810 Update links of ScalarDB Server and Schema Loader
  docs/backup-restore.md
Labels: documentation

#798 refactor: make `enum RdbEngine` test-only
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseColumnValueIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseConditionalMutationIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSecondaryIndexIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSinglePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTestUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngine.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineFactory.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/DeleteQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/InsertOnConflictDoUpdateQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/InsertOnDuplicateKeyUpdateQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/InsertQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/MergeIntoQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/MergeQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/PreparedStatementBinder.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/QueryBuilder.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/UpdateQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/UpsertQuery.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/RdbEngine.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
  server/src/integration-test/java/com/scalar/db/server/ServerAdminTestUtils.java
Labels: improvement

#809 Remove unnecessary string building
  core/src/main/java/com/scalar/db/io/BigIntColumn.java
Labels: improvement

#811 Fix product name of Amazon Aurora
  docs/scalardb-supported-databases.md
Labels: documentation

#812 Automatically format source code with pre-commit
  .pre-commit-config.yaml
  README.md
  docs/index.md
Labels: improvement
