Repository scalar-labs/scalardb, pull requests merged in 2023-11, with the labels that each got.

#1231 Split release.yaml to two sub workflows
  .github/workflows/create-release.yaml
  .github/workflows/release.yaml
  .github/workflows/upload-artifacts.yaml
Labels: improvement

#1237 Should not create PR for base branch in Auto-PR
  .github/workflows/auto-pr.yaml
  ci/auto-pr/conv_proj_version_to_branch
Labels: improvement

#1208 Add `--upgrade` command to Schema Loader
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSchemaLoaderIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageSchemaLoaderIntegrationTest.java
  integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaLoaderTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/SchemaLoaderCommandTest.java
  server/src/integration-test/java/com/scalar/db/server/SchemaLoaderIntegrationTestWithServer.java
Labels: enhancement

#1268 Added merging the release notes workflow
  .github/workflows/merge-release-notes.yaml
Labels: enhancement, github_actions

#1196 Revise Schema Loader documentation
  docs/schema-loader.md
Labels: documentation

#1222 Support implicit pre-read in Consensus Commit
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionIntegrationTest.java
  core/src/main/java/com/scalar/db/api/OperationBuilder.java
  core/src/main/java/com/scalar/db/api/Put.java
  core/src/main/java/com/scalar/db/api/PutBuilder.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/MutationConditionsValidator.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/util/ProtoUtils.java
  core/src/test/java/com/scalar/db/api/PutBuilderTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/MutationConditionsValidatorTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ParallelExecutorTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
  core/src/test/java/com/scalar/db/util/ProtoUtilsTest.java
  docs/api-guide.md
  docs/configurations.md
  docs/storage-abstraction.md
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/util/AdminTestUtils.java
  rpc/src/main/java/com/scalar/db/rpc/Mutation.java
  rpc/src/main/java/com/scalar/db/rpc/MutationOrBuilder.java
  rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java
  rpc/src/main/proto/scalardb.proto
Labels: improvement

#1260 Create namespace metadata when importing tables
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTableIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderImportIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminImportTableIntegrationTest.java
  core/src/main/java/com/scalar/db/api/Admin.java
  core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/service/AdminService.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdmin.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionAdmin.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcAdminTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionAdminTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminImportTableIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminImportTableIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderImportIntegrationTestBase.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/ImportSchemaParser.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/ImportTableSchema.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/ImportSchemaParserTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/ImportTableSchemaTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaLoaderTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/SchemaLoaderCommandTest.java
Labels: improvement

#1297 Fix CVE-2023-39325 and GHSA-m425-mq94-257g
  server/Dockerfile
Labels: bugfix

#1296 Fix to prevent importing existing storage table
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
Labels: bugfix

#1309 Backport to branch(3) : Fix to prevent importing existing storage table
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
Labels: bugfix

#1294 Add cross-partition scan options
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraEnv.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosEnv.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoEnv.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageEnv.java
  core/src/main/java/com/scalar/db/common/checker/OperationChecker.java
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraConfig.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraProvider.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosOperationChecker.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosProvider.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoOperationChecker.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoProvider.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcProvider.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageProvider.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
  core/src/test/java/com/scalar/db/common/checker/OperationCheckerTest.java
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosOperationCheckerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoOperationCheckerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  server/src/integration-test/java/com/scalar/db/server/ServerEnv.java
Labels: improvement

#1324 Backport to branch(3) : Add cross-partition scan options
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraEnv.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosEnv.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoEnv.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageEnv.java
  core/src/main/java/com/scalar/db/common/checker/OperationChecker.java
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraConfig.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraProvider.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosOperationChecker.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosProvider.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoConfig.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoOperationChecker.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoProvider.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcProvider.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageProvider.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
  core/src/test/java/com/scalar/db/common/checker/OperationCheckerTest.java
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosOperationCheckerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoOperationCheckerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  server/src/integration-test/java/com/scalar/db/server/ServerEnv.java
Labels: improvement

#1310 Add API doc for `admin.repairTable` method for v3.X
  docs/api-guide.md
  docs/storage-abstraction.md
Labels: improvement, documentation

#1300 Update documentation for the repair feature
  core/src/main/java/com/scalar/db/api/Admin.java
  docs/api-guide.md
  docs/schema-loader.md
  docs/storage-abstraction.md
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
Labels: documentation

#1337 Add options to Admin.importTable()
  core/src/main/java/com/scalar/db/api/Admin.java
  core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/service/AdminService.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdmin.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionAdmin.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcAdminTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionAdminTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminImportTableIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminImportTableIntegrationTestBase.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/ImportSchemaParser.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/ImportTableSchema.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/ImportSchemaParserTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/ImportTableSchemaTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaLoaderTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/SchemaLoaderCommandTest.java
Labels: improvement
