Repository scalar-labs/scalardb, pull requests merged in 2023-10, with the labels that each got.

#1084 Revise the contents of the Java API guide
  core/src/main/java/com/scalar/db/api/Admin.java
  docs/api-guide.md
Labels: documentation

#1127 Update busybox version in dockerfile
  server/Dockerfile
Labels: bugfix

#1126 Free up storage space in CI for Oracle 23 job
  .github/workflows/ci.yaml
Labels: bugfix

#1140 Fix Oracle 23 CI
  .github/workflows/ci.yaml
Labels: bugfix

#1124 Fix warnings displayed by IntelliJ
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosEnv.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoEnv.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageEnv.java
  core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/CosmosCommand.java
  server/src/integration-test/java/com/scalar/db/server/ServerEnv.java
Labels: improvement

#1117 Revise configuration-related docs (3.8 and earlier)
  docs/configurations-for-consensus-commit.md
  docs/configurations.md
  docs/multi-storage-transactions.md
  docs/two-phase-commit-transactions.md
Labels: documentation

#1125 Revise Admin's repair table behavior
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminRepairTableIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSchemaLoaderIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminRepairTableIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageSchemaLoaderIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminRepairTableIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminRepairTableIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/util/AdminTestUtils.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminRepairTableIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/SchemaLoaderIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/ServerAdminTestUtils.java
Labels: improvement

#1187 Update the trigger of the GitHub Action to work only on master branch push
  .github/workflows/release-snapshot.yaml
Labels: improvement

#1119 Revise the contents of the storage abstraction doc
  docs/storage-abstraction.md
Labels: documentation

#1209 Port auto-pr workflow to branch `3`
  .github/workflows/auto-pr.yaml
Labels: improvement

#1210 Port (Add) the auto-pr workflow to old release branches
  .github/workflows/auto-pr.yaml
Labels: improvement

#1212 Add missing scripts for Auto-PR
  ci/auto-pr/conv_proj_version_to_branch
  ci/auto-pr/create_pull_requests
  ci/auto-pr/fetch_gh_proj_versions
  ci/auto-pr/fetch_gh_user_info
Labels: improvement, github_actions

#1217 Add missing Auto-PR workflow file
  .github/workflows/auto-pr.yaml
Labels: improvement, github_actions

#1203 Schema Loader `--repair-all` command will also repair namespaces
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSchemaLoaderIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageSchemaLoaderIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java
  integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaLoaderTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/SchemaLoaderCommandTest.java
  server/src/integration-test/java/com/scalar/db/server/SchemaLoaderIntegrationTestWithServer.java
Labels: enhancement

#1204 Add `upgrade()` to Admin API
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminIntegrationTest.java
  core/src/main/java/com/scalar/db/api/Admin.java
  core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/service/AdminService.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/Namespace.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdmin.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionAdmin.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminIntegrationTestWithServer.java
Labels: enhancement

#1122 Revise the backup and restore guide
  docs/backup-restore.md
Labels: documentation

#1236 Revert "Update the trigger of the GitHub Action to work only on master branch push (#1187)"
  .github/workflows/release-snapshot.yaml
Labels: improvement
