Repository scalar-labs/scalardb, pull requests merged in 2023-12, with the labels that each got.

#1336 Disable implicit pre-read by default for Put operations
  core/src/main/java/com/scalar/db/api/OperationBuilder.java
  core/src/main/java/com/scalar/db/api/Put.java
  core/src/main/java/com/scalar/db/api/PutBuilder.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/test/java/com/scalar/db/api/PutBuilderTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/util/ProtoUtilsTest.java
  docs/api-guide.md
  docs/storage-abstraction.md
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
Labels: improvement

#1318 Add AuthAdmin
  core/src/main/java/com/scalar/db/api/AuthAdmin.java
  core/src/main/java/com/scalar/db/api/DistributedTransactionAdmin.java
  core/src/main/java/com/scalar/db/exception/storage/ExecutionException.java
  core/src/main/java/com/scalar/db/exception/transaction/AbortException.java
  core/src/main/java/com/scalar/db/exception/transaction/CommitException.java
  core/src/main/java/com/scalar/db/exception/transaction/CrudException.java
  core/src/main/java/com/scalar/db/exception/transaction/PreparationException.java
  core/src/main/java/com/scalar/db/exception/transaction/RollbackException.java
  core/src/main/java/com/scalar/db/exception/transaction/TransactionException.java
  core/src/main/java/com/scalar/db/exception/transaction/ValidationException.java
Labels: enhancement

#1311 Add documentation for the upgrade feature
  core/src/main/java/com/scalar/db/api/Admin.java
  docs/api-guide.md
  docs/schema-loader.md
  docs/storage-abstraction.md
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
Labels: improvement, documentation

#1347 Make auto-pr robust to avoid timing issue or etc
  .github/workflows/auto-pr.yaml
Labels: improvement, github_actions

#1362 Add TRANSACTION_MANAGER_NAME to XXXConfig
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitProvider.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionProvider.java
Labels: improvement

#1361 Fix broken links in supported databases doc
  docs/scalardb-supported-databases.md
Labels: documentation

#1335 Revise ScalarDB design doc
  docs/design.md
Labels: documentation

#1363 Modify integration tests for creations and deletions of coordinator tables
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminRepairIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionCrossPartitionScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionCrossPartitionScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithIncludeMetadataEnabledIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitWithIncludeMetadataEnabledIntegrationTestBase.java
Labels: improvement

#1373 Add ThrowableConsumer
  core/src/main/java/com/scalar/db/common/TableMetadataManager.java
  core/src/main/java/com/scalar/db/util/ThrowableConsumer.java
  core/src/main/java/com/scalar/db/util/ThrowableFunction.java
  core/src/test/java/com/scalar/db/common/TableMetadataManagerTest.java
Labels: improvement

#1380 Add getUser() to AuthAdmin
  core/src/main/java/com/scalar/db/api/AuthAdmin.java
Labels: enhancement

#1395 Enable setting of transaction expiration handler in active transaction management
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
Labels: improvement

#1411 Add "permissions" in release workflow to use configure-aws-credentials
  .github/workflows/upload-artifacts.yaml
Labels: bugfix

#1416 Revert PR #1411
  .github/workflows/upload-artifacts.yaml
Labels: bugfix

#1417 Update ScalarDB dependency version to 3.11.0
  README.md
  docs/getting-started-kotlin/build.gradle.kts
  docs/getting-started/build.gradle
  docs/index.md
Labels: documentation

#1418 Update Scheduled Vulnerability Check
  .github/workflows/scheduled-vuln-check.yaml
Labels: improvement

#1419 Update supported databases
  docs/scalardb-supported-databases.md
Labels: documentation

#1409 Add a requirement for privileges of underlying databases
  docs/requirements.md
Labels: documentation
