Repository scalar-labs/scalardb, pull requests merged in 2023-06, with the labels that each got.

#893 Change version in `add-scalardb-to-your-build.md` from `3.8.0` to `3.9.0`
  README.md
  docs/add-scalardb-to-your-build.md
  docs/getting-started/build.gradle
  docs/index.md
Labels: documentation

#894 Change version in `add-scalardb-to-your-build.md` from `3.8.0` to `3.9.0`
  docs/add-scalardb-to-your-build.md
Labels: documentation

#889 Add an interface to add conditions in ScanAll
  core/src/main/java/com/scalar/db/api/OperationBuilder.java
  core/src/main/java/com/scalar/db/api/Scan.java
  core/src/main/java/com/scalar/db/api/ScanAll.java
  core/src/main/java/com/scalar/db/api/ScanBuilder.java
  core/src/test/java/com/scalar/db/api/ScanBuilderTest.java
  core/src/test/java/com/scalar/db/api/ScanTest.java
Labels: enhancement

#898 Handle PRs created by dependabot in auto-pr GHA workflow
  .github/workflows/auto-pr.yaml
  ci/auto-pr/fetch_gh_user_info
Labels: improvement

#897 Improve documents for Handle Exceptions
  core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java
  docs/api-guide.md
  docs/two-phase-commit-transactions.md
Labels: documentation

#901 Add a redirect from the docs site hosted in this repository to the new docs site
  _config.yml
  _includes/analytics.html
  _layouts/default.html
Labels: documentation

#906 Fix the wrong argument validations in Auto PR workflow
  ci/auto-pr/create_pull_requests
  ci/auto-pr/fetch_gh_proj_versions
  ci/auto-pr/fetch_gh_user_info
Labels: bugfix

#907 Move Jekyll files for redirecting from the docs site hosted in this repository to the new docs site
  docs/_config.yml
  docs/_includes/analytics.html
  docs/_layouts/default.html
Labels: documentation

#900 Add relational scan for JDBC storage and consensus commit transaction
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseRelationalScanIntegrationTest.java
  core/src/main/java/com/scalar/db/api/Scan.java
  core/src/main/java/com/scalar/db/common/checker/OperationChecker.java
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageRelationalScanIntegrationTestBase.java
Labels: enhancement

#905 Revise configuration related documents
  README.md
  conf/database.properties
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
  docs/api-guide.md
  docs/configurations-for-consensus-commit.md
  docs/configurations.md
  docs/getting-started-with-scalardb-on-cassandra.md
  docs/getting-started-with-scalardb-on-cosmosdb.md
  docs/getting-started-with-scalardb-on-dynamodb.md
  docs/getting-started-with-scalardb-on-jdbc.md
  docs/getting-started/scalardb.properties
  docs/index.md
  docs/multi-storage-transactions.md
  docs/requirements.md
  docs/scalardb-server.md
  docs/storage-abstraction.md
  docs/two-phase-commit-transactions.md
  server/conf/database.properties
Labels: documentation

#908 Fix relational scan builder to keep ordering information and so on
  core/src/main/java/com/scalar/db/api/ScanBuilder.java
  core/src/test/java/com/scalar/db/api/ScanBuilderTest.java
Labels: bugfix

#909 Records should not be rolled back in rollback() when the transaction state is marked as COMMITTED in 2PC
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
Labels: bugfix

#899 Support condition for transactional operations
  core/src/main/java/com/scalar/db/api/TransactionCrudOperable.java
  core/src/main/java/com/scalar/db/common/checker/ConditionChecker.java
  core/src/main/java/com/scalar/db/exception/transaction/UnsatisfiedConditionException.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitMutationOperationChecker.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/MutationConditionsValidator.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransaction.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStream.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionOnBidirectionalStream.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitMutationOperationCheckerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/MutationConditionsValidatorTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionOnBidirectionalStreamTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionOnBidirectionalStreamTest.java
  docs/api-guide.md
  docs/two-phase-commit-transactions.md
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  rpc/src/main/java/com/scalar/db/rpc/ScalarDbProto.java
  rpc/src/main/java/com/scalar/db/rpc/TransactionResponse.java
  rpc/src/main/java/com/scalar/db/rpc/TwoPhaseCommitTransactionResponse.java
  rpc/src/main/proto/scalardb.proto
  server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
  server/src/main/java/com/scalar/db/server/TwoPhaseCommitTransactionService.java
  server/src/test/java/com/scalar/db/server/DistributedTransactionServiceTest.java
  server/src/test/java/com/scalar/db/server/TwoPhaseCommitTransactionServiceTest.java
Labels: enhancement

#916 Add integration tests for MariaDB to CI
  .github/workflows/ci.yaml
Labels: enhancement

#917 Add a constructor to UnsatisfiedConditionException
  core/src/main/java/com/scalar/db/api/TransactionCrudOperable.java
  core/src/main/java/com/scalar/db/exception/transaction/UnsatisfiedConditionException.java
Labels: improvement

#913 Add integration tests for transaction with relational scan
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitRelationalScanIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/TwoPhaseConsensusCommitRelationalScanIntegrationTestWithJdbcDatabase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionRelationalScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionRelationalScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitRelationalScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitRelationalScanIntegrationTestBase.java
Labels: improvement

#919 Should call abort() when aborting transaction in transaction wrapper classes
  core/src/main/java/com/scalar/db/common/AbstractDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/AbstractTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTwoPhaseCommitTransactionOnBidirectionalStream.java
Labels: bugfix

#920 Improve some `toString` expressions of Selection Operators
  core/src/main/java/com/scalar/db/api/GetWithIndex.java
  core/src/main/java/com/scalar/db/api/Scan.java
  core/src/main/java/com/scalar/db/api/ScanAll.java
  core/src/main/java/com/scalar/db/api/ScanWithIndex.java
  core/src/main/java/com/scalar/db/api/Selection.java
Labels: improvement
