Repository scalar-labs/scalardb, pull requests merged in 2023-09, with the labels that each got.

#1045 Fix ScanBuilder bug
  core/src/main/java/com/scalar/db/api/ScanBuilder.java
  core/src/test/java/com/scalar/db/api/ScanBuilderTest.java
Labels: bugfix

#1055 Fix to handle supported data types properly when importing tables in MySQL and SQL Server
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTestUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
Labels: bugfix

#1020 Revise supported databases and requirements/recommendations docs
  README.md
  docs/index.md
  docs/requirements.md
  docs/scalardb-supported-databases.md
Labels: documentation

#1064 Backport to branch (3.8): Revise supported databases and requirements/recommendations docs
  README.md
  docs/index.md
  docs/requirements.md
  docs/scalardb-supported-databases.md
Labels: documentation

#1065 Backport to branch (3.7): Revise supported databases and requirements/recommendations docs
  README.md
  docs/index.md
  docs/requirements.md
  docs/scalardb-supported-databases.md
Labels: documentation

#1066 Backport to branch (3.6): Revise supported databases and requirements/recommendations docs
  README.md
  docs/index.md
  docs/requirements.md
  docs/scalardb-supported-databases.md
Labels: documentation

#1067 Backport to branch (3.5): Revise supported databases and requirements/recommendations docs
  README.md
  docs/index.md
  docs/requirements.md
  docs/scalardb-supported-databases.md
Labels: documentation

#1068 Backport to branch(3.10) : Fix to handle supported data types properly when importing tables in MySQL and SQL Server (#1055)
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTestUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
Labels: bugfix

#1069 Fix flaky relational scan integration tests
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionRelationalScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionRelationalScanIntegrationTestBase.java
Labels: bugfix

#1056 Add Getting Started by Using Kotlin document and sample project
  docs/getting-started-kotlin/build.gradle.kts
  docs/getting-started-kotlin/gradle.properties
  docs/getting-started-kotlin/gradle/wrapper/gradle-wrapper.jar
  docs/getting-started-kotlin/gradle/wrapper/gradle-wrapper.properties
  docs/getting-started-kotlin/gradlew
  docs/getting-started-kotlin/gradlew.bat
  docs/getting-started-kotlin/scalardb.properties
  docs/getting-started-kotlin/settings.gradle.kts
  docs/getting-started-kotlin/src/main/kotlin/Main.kt
  docs/getting-started-kotlin/src/main/kotlin/sample/ElectronicMoney.kt
  docs/getting-started-with-scalardb-by-using-kotlin.md
Labels: documentation

#1054 Add "Exception and log message guideline" section to README
  README.md
Labels: documentation

#1046 Add like operator
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosConditionalMutationIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoConditionalMutationIntegrationTest.java
  core/src/main/java/com/scalar/db/api/ConditionBuilder.java
  core/src/main/java/com/scalar/db/api/ConditionalExpression.java
  core/src/main/java/com/scalar/db/api/LikeExpression.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/PreparedStatementBinder.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/api/ConditionBuilderTest.java
  core/src/test/java/com/scalar/db/api/LikeExpressionTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageConditionalMutationIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageRelationalScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionRelationalScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionRelationalScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitRelationalScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitRelationalScanIntegrationTestBase.java
Labels: enhancement

#1080 Set Cassandra default replication factor to 3
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminRepairTableIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraColumnValueIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraConditionalMutationIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSecondaryIndexIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSinglePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraWithReservedKeywordIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminRepairTableIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitNullMetadataIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitSpecificIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/TwoPhaseConsensusCommitIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/TwoPhaseConsensusCommitSpecificIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/ConsensusCommitNullMetadataIntegrationTestWithMultiStorage.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/ConsensusCommitSpecificIntegrationTestWithMultiStorage.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTestBase.java
  docs/getting-started-with-scalardb-by-using-kotlin.md
  docs/getting-started-with-scalardb.md
Labels: improvement, documentation

#1005 Update CI to run integration tests towards all ScalarDB supported storage versions
  .github/workflows/ci.yaml
  .github/workflows/supported_storages_compatibility_check.yaml
Labels: improvement

#1085 Clarify the supported Oracle JDK and OpenJDK versions; add a note about other JDKs and versions
  docs/getting-started-with-scalardb-by-using-kotlin.md
  docs/getting-started-with-scalardb.md
Labels: documentation

#1083 Unify styles of the exception messages of Storage Admin implementations
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
Labels: improvement

#1106 Revise supported databases
  docs/scalardb-supported-databases.md
Labels: documentation

#1115 Fix tla+/consensus-commit
  tla+/consensus-commit/CC.tla
  tla+/consensus-commit/CCSpec.tla
  tla+/consensus-commit/README.md
Labels: improvement

#1118 Support release/support branches in auto-pr
  .github/workflows/auto-pr.yaml
Labels: improvement

#1114 Add pull request (PR) template
  .github/pull_request_template.md
Labels: documentation
