Repository scalar-labs/scalardb, pull requests merged in 2023-08, with the labels that each got.

#986 Find the latest release version in `vuln-check` GHA workflow
  .github/workflows/scheduled-vuln-check.yaml
  .github/workflows/vuln-check.yaml
  ci/vuln-check/fetch_gh_releases
  ci/vuln-check/find_latest_release
Labels: improvement

#991 Update the ScalarDB dependency version to 3.10.1
  README.md
  docs/add-scalardb-to-your-build.md
  docs/getting-started/build.gradle
  docs/index.md
Labels: documentation

#984 Enable to specify set of conditional expression set in ScanAll
  core/src/main/java/com/scalar/db/api/OperationBuilder.java
  core/src/main/java/com/scalar/db/api/ScanBuilder.java
  core/src/test/java/com/scalar/db/api/ScanBuilderTest.java
Labels: improvement

#990 Reorganize and revise "Getting Started" docs
  docs/getting-started-with-scalardb-on-cassandra.md
  docs/getting-started-with-scalardb-on-cosmosdb.md
  docs/getting-started-with-scalardb-on-dynamodb.md
  docs/getting-started-with-scalardb-on-jdbc.md
  docs/getting-started-with-scalardb.md
  docs/getting-started.md
Labels: documentation

#994 Escape PR title in `auto-pr` workflow
  .github/workflows/auto-pr.yaml
Labels: improvement, github_actions

#1004 Fix broken links to the "Getting Started" doc
  README.md
  docs/api-guide.md
  docs/index.md
  docs/storage-abstraction.md
Labels: documentation

#1006 Fix to ignore empty condition set when building Scan object
  core/src/main/java/com/scalar/db/api/ScanBuilder.java
  core/src/test/java/com/scalar/db/api/ScanBuilderTest.java
Labels: bugfix

#1013 Make Cosmos DTO objects immutable
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminTestUtils.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosMutation.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosTableMetadata.java
  core/src/main/java/com/scalar/db/storage/cosmos/Record.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/cosmos/ResultInterpreterTest.java
Labels: improvement

#1018 Add more context to the "Getting Started with ScalarDB" doc to help users run the sample application
  docs/getting-started-with-scalardb.md
Labels: documentation

#1019 Add out-of-support banner to docs to show that ScalarDB 3.4 is no longer supported on the docs site
  docs/backup-restore.md
  docs/getting-started-with-scalardb-on-cassandra.md
  docs/getting-started-with-scalardb-on-cosmosdb.md
  docs/getting-started-with-scalardb-on-dynamodb.md
  docs/getting-started-with-scalardb-on-jdbc.md
  docs/getting-started-with-scalardb.md
  docs/getting-started.md
  docs/index.md
  docs/requirements.md
  docs/scalardb-server.md
  docs/schema.md
  docs/two-phase-commit-transactions.md
Labels: documentation

#1012 Create supported storages compatibility check workflow
  .github/workflows/supported_storages_compatibility_check.yaml
Labels: improvement

#1028 Revise the "Add ScalarDB to Your Build" doc
  docs/add-scalardb-to-your-build.md
Labels: documentation

#1037 Fix to handle version-specific integration tests
  .github/workflows/ci.yaml
  .github/workflows/supported_storages_compatibility_check.yaml
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java
Labels: bugfix
