Repository scalar-labs/scalardb, pull requests merged in 2023-07, with the labels that each got.

#925 Add relational scan for JDBC transactions
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionRelationalScanIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
Labels: enhancement

#924 Run `git cherry-pick --abort` after it fails
  ci/auto-pr/create_pull_requests
Labels: bugfix

#927 Update the ScalarDB dependency version to 3.9.1
  README.md
  docs/add-scalardb-to-your-build.md
  docs/getting-started/build.gradle
  docs/index.md
Labels: documentation

#928 Update Scheduled Vulnerability Check workflow
  .github/workflows/scheduled-vuln-check.yaml
Labels: improvement

#930 Revise Javadoc for exceptions
  core/src/main/java/com/scalar/db/api/DistributedTransaction.java
  core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java
  core/src/main/java/com/scalar/db/api/TransactionCrudOperable.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/exception/transaction/AbortException.java
  core/src/main/java/com/scalar/db/exception/transaction/CommitConflictException.java
  core/src/main/java/com/scalar/db/exception/transaction/CommitException.java
  core/src/main/java/com/scalar/db/exception/transaction/CrudConflictException.java
  core/src/main/java/com/scalar/db/exception/transaction/CrudException.java
  core/src/main/java/com/scalar/db/exception/transaction/PreparationConflictException.java
  core/src/main/java/com/scalar/db/exception/transaction/PreparationException.java
  core/src/main/java/com/scalar/db/exception/transaction/RollbackException.java
  core/src/main/java/com/scalar/db/exception/transaction/TransactionNotFoundException.java
  core/src/main/java/com/scalar/db/exception/transaction/ValidationConflictException.java
  core/src/main/java/com/scalar/db/exception/transaction/ValidationException.java
Labels: improvement

#932 Revise document for handling exceptions
  docs/api-guide.md
Labels: documentation

#935 Avoid decrementing outstanding requests counter duplicately
  server/src/main/java/com/scalar/db/server/DistributedTransactionService.java
Labels: bugfix

#943 Fix CVE-2023-1428 and CVE-2023-32731
  build.gradle
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageAdminGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedStorageGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionAdminGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/DistributedTransactionGrpc.java
  rpc/src/main/grpc/com/scalar/db/rpc/TwoPhaseCommitTransactionGrpc.java
Labels: bugfix

#954 Fix CVE-2023-2976
  build.gradle
Labels: bugfix

#950 Fix utility method to check transactional table metadata
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtilsTest.java
Labels: bugfix

#944 Add join() to DistributedTransactionManager
  core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionManagerTest.java
  docs/api-guide.md
Labels: enhancement

#931 Add table importing feature
  .github/workflows/ci.yaml
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminImportTableIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTableIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderImportIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminImportTableIntegrationTest.java
  core/src/main/java/com/scalar/db/api/Admin.java
  core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/service/AdminService.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdmin.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionAdmin.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/RdbEngineTest.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcAdminTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminImportTableIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminImportTableIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderImportIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminImportTableIntegrationTestBase.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/ImportSchemaParser.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/ImportTableSchema.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/ImportSchemaParserTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/ImportTableSchemaTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaLoaderTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/SchemaLoaderCommandTest.java
  server/src/main/java/com/scalar/db/server/DistributedStorageAdminService.java
Labels: enhancement

#968 Update the ScalarDB dependency version to 3.10.0
  README.md
  docs/add-scalardb-to-your-build.md
  docs/getting-started/build.gradle
  docs/index.md
Labels: documentation

#969 Update Scheduled Vulnerability Check workflow
  .github/workflows/scheduled-vuln-check.yaml
Labels: improvement

#970 Fix java warnings in MutationConditionsValidatorTest
  core/src/test/java/com/scalar/db/transaction/consensuscommit/MutationConditionsValidatorTest.java
Labels: improvement

#934 Revise document for handling exceptions for Two-phase Commit Transactions
  docs/two-phase-commit-transactions.md
Labels: documentation

#976 Use PAT that has `workflows` permission in auto-pr
  .github/workflows/auto-pr.yaml
Labels: improvement

#975 Revise document for Handle exceptions
  docs/api-guide.md
  docs/two-phase-commit-transactions.md
Labels: documentation
