Repository scalar-labs/scalardb, pull requests merged in 2023-05, with the labels that each got.

#841 Make transaction metadata nullable to support existing databases
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitNullMetadataIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitNullMetadataIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitNullMetadataIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitNullMetadataIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/ConsensusCommitNullMetadataIntegrationTestWithMultiStorage.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionResult.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TransactionResultTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java
Labels: enhancement

#880 Change HTML syntax to Markdown for images (master)
  docs/design.md
  docs/two-phase-commit-transactions.md
Labels: documentation

#879 Change HTML syntax to Markdown for images (3.9)
  docs/design.md
  docs/two-phase-commit-transactions.md
Labels: documentation

#878 Change HTML syntax to Markdown for images (3.8)
  docs/design.md
  docs/two-phase-commit-transactions.md
Labels: documentation

#877 Change HTML syntax to Markdown for images (3.7)
  docs/design.md
  docs/two-phase-commit-transactions.md
Labels: documentation

#876 Change HTML syntax to Markdown for images (3.6)
  docs/design.md
Labels: documentation

#875 Change HTML syntax to Markdown for images (3.5)
  docs/design.md
Labels: documentation

#884 Add GHA workflow to automatically create pull requests to apply a merged PR changes
  .github/workflows/auto-pr.yaml
  ci/auto-pr/conv_proj_version_to_branch
  ci/auto-pr/create_pull_requests
  ci/auto-pr/fetch_gh_proj_versions
  ci/auto-pr/fetch_gh_user_info
Labels: improvement

#885 Use a proper PAT in the GHA workflow for automated PR creation
  .github/workflows/auto-pr.yaml
Labels: bugfix

#873 Add validation for consensus commit mutation operation
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitMutationOperationChecker.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitMutationOperationCheckerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
Labels: enhancement

#891 Use the original Git commit author info not a response from GitHub API for the automated PR creation workflow
  .github/workflows/auto-pr.yaml
  ci/auto-pr/create_pull_requests
  ci/auto-pr/fetch_gh_user_info
Labels: bugfix

#890 Remove untagged container images
  .github/workflows/remove-untagged-images.yaml
Labels: improvement
