Repository scalar-labs/scalardb, pull requests merged in 2023-02, with the labels that each got.

#813 Update Cosmos DB name in supported DB docs
  docs/api-guide.md
  docs/backup-restore.md
  docs/design.md
  docs/getting-started-with-scalardb-on-cosmosdb.md
  docs/getting-started.md
  docs/scalardb-server.md
  docs/scalardb-supported-databases.md
  docs/schema-loader.md
  docs/storage-abstraction.md
Labels: documentation

#815 Update GitHub actions workflows
  .github/workflows/ci.yaml
  .github/workflows/release-snapshot.yaml
  .github/workflows/release.yaml
  .github/workflows/vuln-check.yaml
Labels: improvement

#805 refactor: stop performing `execute()` in `RdbEngineStrategy` implementations
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
Labels: improvement

#820 Modify schema-loader-command-name
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
Labels: improvement

#821 Fix CVE-2023-0286
  schema-loader/Dockerfile
  server/Dockerfile
Labels: bugfix

#822 Replace usage of gradle by gradle wrapper in Github workflows
  .github/workflows/release-snapshot.yaml
  .github/workflows/release.yaml
  .github/workflows/vuln-check.yaml
Labels: bugfix

#824 Make namespace optional on operation builder
  core/src/main/java/com/scalar/db/api/DeleteBuilder.java
  core/src/main/java/com/scalar/db/api/GetBuilder.java
  core/src/main/java/com/scalar/db/api/OperationBuilder.java
  core/src/main/java/com/scalar/db/api/PutBuilder.java
  core/src/main/java/com/scalar/db/api/ScanBuilder.java
  core/src/test/java/com/scalar/db/api/DeleteBuilderTest.java
  core/src/test/java/com/scalar/db/api/GetBuilderTest.java
  core/src/test/java/com/scalar/db/api/PutBuilderTest.java
  core/src/test/java/com/scalar/db/api/ScanBuilderTest.java
Labels: enhancement
