Repository scalar-labs/scalardb, pull requests merged in 2024-06, with the labels that each got.

#1763 Add arbitrary filtering for partition scan and index scan
  core/src/main/java/com/scalar/db/api/ScanBuilder.java
  core/src/main/java/com/scalar/db/common/checker/OperationChecker.java
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/api/ScanBuilderTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageSecondaryIndexIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageSecondaryIndexIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithServer.java
Labels: enhancement

#1803 Fix a flaky test of `integration-test-for-group-commit` test cases
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Labels: improvement

#1826 Use eclipse-temurin base image in Dockerfile
  .github/dependabot.yml
  ci/dockerfile_lint.sh
  schema-loader/Dockerfile
  server/Dockerfile
Labels: improvement

#1837 Revert behavior : the Gradle build does not require to use JDK 8 (temurin)
  buildSrc/src/main/java/com/scalar/db/JdkConfigurationPlugin.java
Labels: improvement

#1851 Increase heap size for Cosmos DB integration test
  core/build.gradle
Labels: improvement

#1805 Split Group Commit Emitter method for normal group emit and delayed group emit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CoordinatorGroupCommitter.java
  core/src/main/java/com/scalar/db/util/groupcommit/DelayedGroup.java
  core/src/main/java/com/scalar/db/util/groupcommit/DelayedSlotMoveWorker.java
  core/src/main/java/com/scalar/db/util/groupcommit/Emittable.java
  core/src/main/java/com/scalar/db/util/groupcommit/Group.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCleanupWorker.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitMetrics.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitter.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupManager.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupSizeFixWorker.java
  core/src/main/java/com/scalar/db/util/groupcommit/KeyManipulator.java
  core/src/main/java/com/scalar/db/util/groupcommit/NormalGroup.java
  core/src/main/java/com/scalar/db/util/groupcommit/Slot.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorGroupCommitterTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/DelayedGroupTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/DelayedSlotMoveWorkerTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupCleanupWorkerTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterConcurrentTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupManagerTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupSizeFixWorkerTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/NormalGroupTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/SlotTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/TestableKeyManipulator.java
Labels: improvement

#1852 Fix a build error of docs/getting-started
  docs/getting-started/build.gradle
  docs/getting-started/gradle/wrapper/gradle-wrapper.properties
Labels: improvement

#1871 Add build tests for `getting started` example projects
  .github/workflows/ci.yaml
Labels: github_actions

#1873 Change relative docs links to docs site links in README
  README.md
Labels: documentation

#1864 Make CoordinatorGroupCommitKeyManipulator public to reuse the logic in other projects
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CoordinatorGroupCommitter.java
Labels: improvement

#1896 Fix typo in link in README
  README.md
Labels: documentation

#1834 Add arbitrary filtering for get operations
  core/src/main/java/com/scalar/db/api/Get.java
  core/src/main/java/com/scalar/db/api/GetBuilder.java
  core/src/main/java/com/scalar/db/api/ScanBuilder.java
  core/src/main/java/com/scalar/db/api/SelectionBuilder.java
  core/src/main/java/com/scalar/db/common/checker/OperationChecker.java
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/api/GetBuilderTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/singlecrudoperation/SingleCrudOperationTransactionIntegrationTestBase.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/TwoPhaseConsensusCommitIntegrationTestWithServer.java
Labels: enhancement

#1903 Delay throwing an exception for the combination of two-phase commit interface and the group commit feature to when `begin()` is called
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
Labels: bugfix

#1909 Use Cosmos DB emulator for the integration tests
  .github/workflows/ci.yaml
  core/build.gradle
Labels: improvement, github_actions

#1920 Reduce the number of concurrent DDLs from 10 to 1 for Cosmos DB in the integration tests
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosCrossPartitionScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java
Labels: improvement, github_actions

#1829 Add a page for data modeling with ScalarDB
  docs/data-modeling.md
  docs/images/scalardb_data_model.png
Labels: documentation

#1919 Fix CosmosDB CI when running integration test with JDK11+
  .github/workflows/ci.yaml
Labels: bugfix

#1918 Remove unnecessary `scalardb.cosmos.database_prefix` property
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminRepairIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitCosmosEnv.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitCrossPartitionScanIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitNullMetadataIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitSpecificIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminRepairIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosColumnValueIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosConditionalMutationIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosCrossPartitionScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosEnv.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosJapaneseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSchemaLoaderIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSecondaryIndexIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSinglePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosWithReservedKeywordIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/SingleCrudOperationTransactionAdminIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/SingleCrudOperationTransactionIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitSpecificIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/TwoPhaseConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithCosmos.java
Labels: github_actions

#1907 Add encrypted column concept
  core/src/main/java/com/scalar/db/api/Admin.java
  core/src/main/java/com/scalar/db/api/TableMetadata.java
  core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  core/src/test/java/com/scalar/db/common/CheckedDistributedStorageAdminTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
Labels: enhancement

#1977 [3.7~3.11] Fix error in integration test with Java 21 as runtime
  build.gradle
Labels: bugfix

#1980 Fix CVE-2024-24790, CVE-2023-45283, and CVE-2023-45288
  server/Dockerfile
Labels: bugfix

#1975 Support encrypted columns in Schema Loader
  core/src/main/java/com/scalar/db/api/TableMetadata.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/TableSchemaTest.java
Labels: enhancement

#1974 Add DecoratedDistributedTransactionAdmin
  core/src/main/java/com/scalar/db/common/DecoratedDistributedTransaction.java
  core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionAdmin.java
  core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransaction.java
  core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransactionManager.java
Labels: improvement

#2001 Fix a bug that the importing table feature accesses tables in other namespace that have the same table name with MySQL storage
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderImportIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
  integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderImportIntegrationTestBase.java
Labels: bugfix
