Repository scalar-labs/scalardb, pull requests merged in 2024-03, with the labels that each got.

#1575 Use username "sa" instead of "SA" in CI of SQL Server
  ci/no-superuser/create-no-superuser-sqlserver.sh
Labels: bugfix, github_actions

#1564 Add error codes to error messages of Schema loader
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/ImportSchemaParser.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/ImportTableSchema.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaParser.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/TableSchema.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/alteration/TableMetadataAlterationProcessor.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/StorageSpecificCommand.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/ImportTableSchemaTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/TableSchemaTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/alteration/TableMetadataAlterationProcessorTest.java
Labels: improvement

#1590 Revise error messages
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
Labels: improvement

#1511 Update requirements and recommendations
  docs/requirements.md
  docs/scalardb-supported-databases.md
Labels: documentation

#1567 Update CI to fix issues of SQL Server integration test
  .github/workflows/ci.yaml
  ci/no-superuser/create-no-superuser-sqlserver.sh
Labels: bugfix, github_actions
