Repository scalar-labs/scalardb, pull requests merged in 2024-02, with the labels that each got.

#1482 [vuln-check-workflow] Fix incomplete skip of unexpected versions
  ci/vuln-check/find_latest_release
Labels: improvement, github_actions

#1485 Handle coordinator namespace correctly in ConsensusCommitAdmin
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminRepairIntegrationTestWithCassandra.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminRepairIntegrationTestBase.java
Labels: improvement

#1486 Allow to specify global properties for all storages in multi-storage
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageConfig.java
  core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageConfigTest.java
Labels: improvement

#1498 Add description about placeholders of database.properties
  docs/configurations.md
Labels: documentation

#1509 Update Scheduled Vulnerability Check
  .github/workflows/scheduled-vuln-check.yaml
Labels: improvement

#1510 Update supported databases
  docs/scalardb-supported-databases.md
Labels: documentation

#1518 Remove hard-coded collation in JDBC adapter
  .github/workflows/ci.yaml
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraJapaneseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosJapaneseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoJapaneseIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseJapaneseIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageJapaneseIntegrationTestBase.java
Labels: improvement

#1542 Update CI to use no superuser for SQL Server test
  .github/workflows/ci.yaml
  ci/no-superuser/create-no-superuser-sqlserver.sh
Labels: improvement, github_actions
