Repository scalar-labs/scalardb, pull requests merged in 2024-05, with the labels that each got.

#1703 Make OperationBuilder public
  core/src/main/java/com/scalar/db/api/OperationBuilder.java
Labels: improvement

#1642 Improve the ScalarDB overview page
  docs/images/scalardb.png
  docs/overview.md
Labels: documentation

#1715 Refactor scan with filtering
  core/src/main/java/com/scalar/db/api/AndConditionSet.java
  core/src/main/java/com/scalar/db/api/ConditionSetBuilder.java
  core/src/main/java/com/scalar/db/api/OperationBuilder.java
  core/src/main/java/com/scalar/db/api/OrConditionSet.java
  core/src/main/java/com/scalar/db/api/Scan.java
  core/src/main/java/com/scalar/db/api/ScanBuilder.java
  core/src/main/java/com/scalar/db/api/Selection.java
  core/src/main/java/com/scalar/db/common/checker/OperationChecker.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/api/ScanBuilderTest.java
  core/src/test/java/com/scalar/db/api/ScanTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageCrossPartitionScanIntegrationTestBase.java
Labels: improvement

#1727 Fix to prevent scan with index after overlapping put
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Labels: bugfix

#1726 Add empty dataloader CLI and core sub projects
  data-loader/build.gradle
  data-loader/cli/build.gradle
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/DataLoaderCli.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommand.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommandOptions.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataimport/ImportCommand.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataimport/ImportCommandOptions.java
  data-loader/core/build.gradle
  settings.gradle
Labels: enhancement

#1710 Add YugabyteDB adapter
  .github/workflows/ci.yaml
  build.gradle
  core/build.gradle
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminRepairIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminRepairIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseCrossPartitionScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSinglePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderImportIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderIntegrationTest.java
  core/src/main/java/com/scalar/db/config/ConfigUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineFactory.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineYugabyte.java
  core/src/test/java/com/scalar/db/config/ConfigUtilsTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/RdbEngine.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
  docs/backup-restore.md
  docs/getting-started-with-scalardb-by-using-kotlin.md
  docs/getting-started-with-scalardb.md
  docs/scalardb-supported-databases.md
  docs/schema-loader-import.md
  docs/schema-loader.md
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminRepairIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageCrossPartitionScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultipleClusteringKeyScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultiplePartitionKeyIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageSinglePartitionKeyIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminRepairIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderImportIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
Labels: enhancement

#1742 Add picocli argument convertor for column key value and file format
  data-loader/build.gradle
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/ColumnKeyValue.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/ColumnKeyValueConverter.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommandOptions.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/ColumnKeyValueConverterTest.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/FileFormat.java
Labels: enhancement

#1754 Add export --output-file flag and validation
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  data-loader/build.gradle
  data-loader/cli/build.gradle
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommand.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommandOptions.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/exception/DirectoryValidationException.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/exception/InvalidFileExtensionException.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/DirectoryUtils.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommandTest.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/DirectoryUtilsTest.java
Labels: enhancement

#1762 Fix integration test failure because of conflicting use of table names
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitCrossPartitionScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitCrossPartitionScanIntegrationTestBase.java
Labels: bugfix

#1767 Should add prefix to namespaces for Cosmos DB integration tests
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitCrossPartitionScanIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosCrossPartitionScanIntegrationTest.java
Labels: bugfix

#1774 Add DecoratedDistributedTransactionManager and DecoratedTwoPhaseCommitTransactionManager
  core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransactionManager.java
Labels: enhancement

#1765 Change hard-coded password for Oracle user in JDBC adapter
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
Labels: improvement

#1728 Integrate `util/groupcommit` package with the coordinator table commit
  .github/workflows/ci.yaml
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitCrossPartitionScanIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitJdbcEnv.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitNullMetadataIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitSpecificIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/TwoPhaseConsensusCommitCrossPartitionScanIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/TwoPhaseConsensusCommitIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/TwoPhaseConsensusCommitSpecificIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/TwoPhaseConsensusCommitWithIncludeMetadataEnabledIntegrationTestWithJdbcDatabase.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Attribute.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CoordinatorGroupCommitter.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/util/groupcommit/DelayedGroup.java
  core/src/main/java/com/scalar/db/util/groupcommit/Group.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitConfig.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitConflictException.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitException.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitter.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupManager.java
  core/src/main/java/com/scalar/db/util/groupcommit/NormalGroup.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommitTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorGroupCommitterTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/DelayedGroupTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitConfigTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterConcurrentTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupManagerTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/NormalGroupTest.java
  docs/api-guide.md
  docs/configurations.md
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
Labels: enhancement

#1769 Add mockito and core project in Gradle files
  data-loader/build.gradle
  data-loader/core/build.gradle
Labels: enhancement

#1770 Move ColumnKeyValue to the data loader core project
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/ColumnKeyValueConverter.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/ColumnKeyValueConverterTest.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/ColumnKeyValue.java
Labels: enhancement

#1753 Fix default value of cross-partition scan in docs
  docs/configurations.md
Labels: bugfix, documentation

#1801 Remove CI status badge
  README.md
Labels: improvement

#1749 Run integration test with a given Java version and vendor
  .github/workflows/ci.yaml
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/com/scalar/db/JdkConfigurationPlugin.java
  core/build.gradle
  docs/getting-started/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  integration-test/build.gradle
  rpc/build.gradle
  schema-loader/build.gradle
  server/build.gradle
Labels: improvement
