Repository scalar-labs/scalardb, pull requests merged in 2024-04, with the labels that each got.

#1617 Update ScalarDB dependency version to 3.12.2
  README.md
  docs/getting-started-kotlin/build.gradle.kts
  docs/getting-started/build.gradle
  docs/index.md
Labels: documentation

#1620 Remove the CI trigger for branch pushes
  .github/workflows/ci.yaml
Labels: improvement

#1607 Add `util/groupcommit` package in `core` subproject
  core/build.gradle
  core/src/main/java/com/scalar/db/util/groupcommit/BackgroundWorker.java
  core/src/main/java/com/scalar/db/util/groupcommit/DelayedGroup.java
  core/src/main/java/com/scalar/db/util/groupcommit/DelayedSlotMoveWorker.java
  core/src/main/java/com/scalar/db/util/groupcommit/Emittable.java
  core/src/main/java/com/scalar/db/util/groupcommit/Group.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCleanupWorker.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitConfig.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitException.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitter.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupManager.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupSizeFixWorker.java
  core/src/main/java/com/scalar/db/util/groupcommit/KeyManipulator.java
  core/src/main/java/com/scalar/db/util/groupcommit/Metrics.java
  core/src/main/java/com/scalar/db/util/groupcommit/NormalGroup.java
  core/src/main/java/com/scalar/db/util/groupcommit/Slot.java
  core/src/test/java/com/scalar/db/util/groupcommit/BackgroundWorkerTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/DelayedGroupTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/DelayedSlotMoveWorkerTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupCleanupWorkerTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitConfigTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterConcurrentTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupManagerTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupSizeFixWorkerTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/NormalGroupTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/SlotTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/TestableKeyManipulator.java
Labels: enhancement

#1608 Fix some operators in `tla+/consensus-commit/CCSpec`
  tla+/consensus-commit/CCSpec.tla
Labels: bugfix

#1622 Merge build.gradle and archive.gradle
  core/archive.gradle
  core/build.gradle
  integration-test/archive.gradle
  integration-test/build.gradle
  rpc/archive.gradle
  rpc/build.gradle
  schema-loader/archive.gradle
  schema-loader/build.gradle
  server/archive.gradle
  server/build.gradle
Labels: improvement

#1621 Add an overview page
  docs/overview.md
Labels: documentation

#1624 Fix NullPointerException in EXTRA_READ validation
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
Labels: bugfix

#1665 Should not publish Schema Loader fat jar to Maven central
  schema-loader/build.gradle
Labels: bugfix

#1641 Use the priority queue for DelayedSlotMoveWorker to easily reduce the latency to be handled in `util/groupcommit`
  core/src/main/java/com/scalar/db/util/groupcommit/BackgroundWorker.java
  core/src/main/java/com/scalar/db/util/groupcommit/DelayedSlotMoveWorker.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCleanupWorker.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupSizeFixWorker.java
  core/src/test/java/com/scalar/db/util/groupcommit/BackgroundWorkerTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/DelayedSlotMoveWorkerTest.java
Labels: improvement

#1650 Wait until all groups get done when GroupCommitter is closed (was "Abort all in-flight groups on close in the group commit")
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitMonitor.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitter.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupManager.java
  core/src/main/java/com/scalar/db/util/groupcommit/Metrics.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterConcurrentTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupManagerTest.java
Labels: improvement

#1679 Introduce insert mode for Consensus Commit Put operations
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionIntegrationTest.java
  core/src/main/java/com/scalar/db/api/OperationBuilder.java
  core/src/main/java/com/scalar/db/api/Put.java
  core/src/main/java/com/scalar/db/api/PutBuilder.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java
  core/src/test/java/com/scalar/db/api/PutBuilderTest.java
  core/src/test/java/com/scalar/db/api/PutTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposerTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
Labels: enhancement

#1681 Should execute lazy recovery for Put and Delete in Consensus Commit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
Labels: bugfix

#1683 Fix flaky test and warnings in group commit
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitter.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupManagerTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/NormalGroupTest.java
Labels: improvement

#1684 Make group commit metrics log configurable
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitConfig.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitMetrics.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitMonitor.java
  core/src/main/java/com/scalar/db/util/groupcommit/GroupCommitter.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitConfigTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterConcurrentTest.java
  core/src/test/java/com/scalar/db/util/groupcommit/GroupCommitterTest.java
Labels: improvement

#1699 Fix resource leaks in `integrationTestJdbc`
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminImportTableIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTableIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderImportIntegrationTest.java
  integration-test/build.gradle
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminImportTableIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminRepairIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageColumnValueIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageConditionalMutationIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageCrossPartitionScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageJapaneseIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultipleClusteringKeyScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultiplePartitionKeyIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageSecondaryIndexIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageSingleClusteringKeyScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageSinglePartitionKeyIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageWithReservedKeywordIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminImportTableIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminRepairIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionCrossPartitionScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionCrossPartitionScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderImportIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
Labels: improvement
