Repository scalar-labs/scalardb, pull requests merged in 2024-01, with the labels that each got.

#1443 Add getStringFromFilePath() to ConfigUtils
  core/src/main/java/com/scalar/db/config/ConfigUtils.java
  core/src/test/java/com/scalar/db/config/ConfigUtilsTest.java
Labels: enhancement

#1442 Avoid NPE when checking SQLState in JDBC storage
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
Labels: bugfix

#1451 Change TwoPhaseConsensusCommitManager.join() behavior
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/util/ActiveExpiringMap.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/util/ActiveExpiringMapTest.java
  docs/two-phase-commit-transactions.md
Labels: improvement

#1464 Add usages and comments about the inclusive param of `ScanBuilder`'s `start()` and `end()`
  docs/api-guide.md
  docs/storage-abstraction.md
Labels: documentation

#1470 Make Cosmos DB consistency level configurable
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosConfig.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosUtils.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosConfigTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosUtilsTest.java
  docs/configurations.md
Labels: enhancement

#1476 Should perform lazy recovery in implicit pre-read
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/UncommittedRecordException.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
Labels: bugfix
