Repository scalar-labs/scalardb, pull requests merged in 2024-11, with the labels that each got.

#2315 [CI] Increase CosmosDB emulator startup timeout to 10min
  .github/workflows/ci.yaml
Labels: improvement

#2292 Add validation for primary key columns in Cosmos DB adapter
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  core/src/main/java/com/scalar/db/storage/cosmos/ConcatenationVisitor.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosOperationChecker.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CoordinatorGroupCommitter.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosOperationCheckerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorGroupCommitterTest.java
Labels: bugfix

#2328 Refactor to partially remove deprecated `Value` classes usage
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoColumnValueIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSecondaryIndexIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSinglePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseColumnValueIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseCrossPartitionScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSecondaryIndexIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSinglePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcTestUtils.java
  core/src/main/java/com/scalar/db/common/checker/OperationChecker.java
  core/src/main/java/com/scalar/db/storage/cassandra/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosOperation.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoMutation.java
  core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java
  core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageColumnValueIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageConditionalMutationIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageCrossPartitionScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultipleClusteringKeyScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageMultiplePartitionKeyIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageSecondaryIndexIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageSingleClusteringKeyScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageSinglePartitionKeyIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithIncludeMetadataEnabledIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitWithIncludeMetadataEnabledIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/util/TestUtils.java
Labels: improvement

#2329 Refactor operations and their builders
  core/src/main/java/com/scalar/db/api/Delete.java
  core/src/main/java/com/scalar/db/api/DeleteBuilder.java
  core/src/main/java/com/scalar/db/api/Get.java
  core/src/main/java/com/scalar/db/api/GetBuilder.java
  core/src/main/java/com/scalar/db/api/GetWithIndex.java
  core/src/main/java/com/scalar/db/api/Insert.java
  core/src/main/java/com/scalar/db/api/InsertBuilder.java
  core/src/main/java/com/scalar/db/api/Mutation.java
  core/src/main/java/com/scalar/db/api/Operation.java
  core/src/main/java/com/scalar/db/api/OperationBuilder.java
  core/src/main/java/com/scalar/db/api/Put.java
  core/src/main/java/com/scalar/db/api/PutBuilder.java
  core/src/main/java/com/scalar/db/api/Scan.java
  core/src/main/java/com/scalar/db/api/ScanAll.java
  core/src/main/java/com/scalar/db/api/ScanBuilder.java
  core/src/main/java/com/scalar/db/api/ScanWithIndex.java
  core/src/main/java/com/scalar/db/api/Selection.java
  core/src/main/java/com/scalar/db/api/SelectionBuilder.java
  core/src/main/java/com/scalar/db/api/Update.java
  core/src/main/java/com/scalar/db/api/UpdateBuilder.java
  core/src/main/java/com/scalar/db/api/Upsert.java
  core/src/main/java/com/scalar/db/api/UpsertBuilder.java
  core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
  core/src/test/java/com/scalar/db/api/GetBuilderTest.java
  core/src/test/java/com/scalar/db/api/ScanBuilderTest.java
  core/src/test/java/com/scalar/db/util/ScalarDbUtilsTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageWithReservedKeywordIntegrationTestBase.java
Labels: improvement

#2334 Revise feature names in error messages
  core/src/main/java/com/scalar/db/api/Admin.java
  core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/common/error/CoreError.java
Labels: improvement

#2331 Optimize `Coordinator#getStateForGroupCommit()` by first looking up the coordinator table with parent transaction ID
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorTest.java
Labels: improvement

#2333 Introduce operation attributes
  core/src/main/java/com/scalar/db/api/Delete.java
  core/src/main/java/com/scalar/db/api/DeleteBuilder.java
  core/src/main/java/com/scalar/db/api/Get.java
  core/src/main/java/com/scalar/db/api/GetBuilder.java
  core/src/main/java/com/scalar/db/api/GetWithIndex.java
  core/src/main/java/com/scalar/db/api/Insert.java
  core/src/main/java/com/scalar/db/api/InsertBuilder.java
  core/src/main/java/com/scalar/db/api/Mutation.java
  core/src/main/java/com/scalar/db/api/Operation.java
  core/src/main/java/com/scalar/db/api/OperationBuilder.java
  core/src/main/java/com/scalar/db/api/Put.java
  core/src/main/java/com/scalar/db/api/PutBuilder.java
  core/src/main/java/com/scalar/db/api/Scan.java
  core/src/main/java/com/scalar/db/api/ScanAll.java
  core/src/main/java/com/scalar/db/api/ScanBuilder.java
  core/src/main/java/com/scalar/db/api/ScanWithIndex.java
  core/src/main/java/com/scalar/db/api/Selection.java
  core/src/main/java/com/scalar/db/api/Update.java
  core/src/main/java/com/scalar/db/api/UpdateBuilder.java
  core/src/main/java/com/scalar/db/api/Upsert.java
  core/src/main/java/com/scalar/db/api/UpsertBuilder.java
  core/src/test/java/com/scalar/db/api/DeleteBuilderTest.java
  core/src/test/java/com/scalar/db/api/DeleteTest.java
  core/src/test/java/com/scalar/db/api/GetBuilderTest.java
  core/src/test/java/com/scalar/db/api/GetTest.java
  core/src/test/java/com/scalar/db/api/InsertBuilderTest.java
  core/src/test/java/com/scalar/db/api/InsertTest.java
  core/src/test/java/com/scalar/db/api/PutBuilderTest.java
  core/src/test/java/com/scalar/db/api/PutTest.java
  core/src/test/java/com/scalar/db/api/ScanBuilderTest.java
  core/src/test/java/com/scalar/db/api/ScanTest.java
  core/src/test/java/com/scalar/db/api/UpdateBuilderTest.java
  core/src/test/java/com/scalar/db/api/UpdateTest.java
  core/src/test/java/com/scalar/db/api/UpsertBuilderTest.java
  core/src/test/java/com/scalar/db/api/UpsertTest.java
Labels: enhancement

#2341 Fix delete behavior in Cosmos adapter
  core/src/main/java/com/scalar/db/storage/cosmos/DeleteStatementHandler.java
  core/src/test/java/com/scalar/db/storage/cosmos/DeleteStatementHandlerTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
Labels: bugfix

#2340 Revisit behavior of multiple mutations for same record in transaction in Consensus Commit
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
Labels: bugfix

#2351 Use operation attributes for implicit pre-read and insert mode of Put
  core/src/main/java/com/scalar/db/api/OperationBuilder.java
  core/src/main/java/com/scalar/db/api/Put.java
  core/src/main/java/com/scalar/db/api/PutBuilder.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitOperationAttributes.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/api/PutBuilderTest.java
  core/src/test/java/com/scalar/db/api/PutTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitOperationAttributesTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
Labels: improvement

#2352 Fix GetBuilder and ScanBuilder
  core/src/main/java/com/scalar/db/api/GetBuilder.java
  core/src/main/java/com/scalar/db/api/ScanBuilder.java
Labels: bugfix

#2033 Add spotbugs exclude filter file for data loader sub projects
  gradle/spotbugs-exclude.xml
Labels: enhancement

#2363 [3.10, 3.11, 3.12] Backport data loader
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  data-loader/build.gradle
  data-loader/cli/build.gradle
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/DataLoaderCli.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/ColumnKeyValueConverter.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommand.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommandOptions.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataimport/ImportCommand.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataimport/ImportCommandOptions.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/exception/DirectoryValidationException.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/exception/InvalidFileExtensionException.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/DirectoryUtils.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/ColumnKeyValueConverterTest.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommandTest.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/DirectoryUtilsTest.java
  data-loader/core/build.gradle
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/ColumnKeyValue.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/FileFormat.java
  settings.gradle
Labels: improvement
