Repository scalar-labs/scalardb, pull requests merged in 2024-09, with the labels that each got.

#2135 Fix a corner case issue that causes inconsistent Coordinator states when lazy recovery happens before group commit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/RecoveryHandlerTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  tla+/consensus-commit/CoordinatorWithGroupCommit.tla
  tla+/consensus-commit/CoordinatorWithGroupCommit.toolbox/CoordinatorWithGroupCommit___Model_1.launch
  tla+/consensus-commit/CoordinatorWithGroupCommit.toolbox/Model_1/CoordinatorWithGroupCommit.tla
  tla+/consensus-commit/CoordinatorWithGroupCommit.toolbox/Model_1/MC.cfg
  tla+/consensus-commit/CoordinatorWithGroupCommit.toolbox/Model_1/MC.tla
Labels: bugfix

#2176 Use reusable `Auto-PR` action
  .github/workflows/auto-pr.yaml
  ci/auto-pr/conv_proj_version_to_branch
  ci/auto-pr/create_pull_requests
  ci/auto-pr/fetch_gh_proj_versions
  ci/auto-pr/fetch_gh_user_info
Labels: improvement, github_actions

#2164 [Github actions] Fix the deprecation of `gradle-build-action`
  .github/workflows/ci.yaml
  .github/workflows/create-release.yaml
  .github/workflows/release-snapshot.yaml
  .github/workflows/upload-artifacts.yaml
  .github/workflows/vuln-check.yaml
Labels: improvement, github_actions

#2220 [Dependabot] Group update PR & update actions on all branches
  .github/dependabot.yml
Labels: improvement

#2227 Fix CVE-2023-22102
  build.gradle
  core/build.gradle
Labels: bugfix

#2238 Fix CVE-2023-22102
  build.gradle
  core/build.gradle
Labels: bugfix

#2250 [CI] Fix SQLServer 2017 job
  .github/workflows/ci.yaml
Labels: bugfix, github_actions

#2228 Add getCurrentUser() to AuthAdmin
  core/src/main/java/com/scalar/db/api/AuthAdmin.java
  core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionAdmin.java
Labels: enhancement

#2248 [Dependabot] Set reviewers for actions group updates
  .github/dependabot.yml
Labels: bugfix

#2245 Change default key column size and make it configurable for MySQL and Oracle
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  core/src/main/java/com/scalar/db/storage/jdbc/ConditionalMutator.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcService.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineFactory.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcServiceTest.java
Labels: improvement
