Repository scalar-labs/scalardb, pull requests merged in 2024-10, with the labels that each got.

#2265 Refactor ConcatenationVisitor to use ColumnVisitor
  core/src/main/java/com/scalar/db/storage/cosmos/ConcatenationVisitor.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosOperation.java
  core/src/test/java/com/scalar/db/storage/cosmos/ConcatenationVisitorTest.java
Labels: improvement

#2270 Refactor KeyBytesEncoder to use ColumnVisitor
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/BigIntBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/BlobBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/BooleanBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/BytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/DoubleBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/FloatBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/IntBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/KeyBytesEncodedLengthCalculator.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/KeyBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/TextBytesEncoder.java
Labels: improvement

#2274 Change default value of metadata cache expiration time
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java
Labels: improvement

#2284 Update Scheduled Vulnerability Check and Dependabot configuration
  .github/dependabot.yml
  .github/workflows/scheduled-vuln-check.yaml
Labels: improvement, github_actions

#2285 Update ScalarDB dependency version to 3.14.0 in README
  README.md
Labels: documentation

#2271 Add an extension point to collect uncommitted read-set and write-set
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/BeforePreparationSnapshotHook.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtils.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitUtilsTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
Labels: improvement

#2288 Use reusable vulnerability check workflow
  .github/workflows/manual-vuln-check.yaml
  .github/workflows/vuln-check.yaml
  ci/vuln-check/fetch_gh_releases
  ci/vuln-check/find_latest_release
Labels: improvement, github_actions

#2291 Fix scan with limit behavior in DynamoDB adapter
  core/src/main/java/com/scalar/db/storage/dynamo/QueryScanner.java
  core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/dynamo/request/PaginatedRequest.java
  core/src/main/java/com/scalar/db/storage/dynamo/request/QueryRequest.java
  core/src/main/java/com/scalar/db/storage/dynamo/request/ScanRequest.java
  core/src/test/java/com/scalar/db/storage/dynamo/QueryScannerTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
Labels: bugfix

#2302 Update MySQL and PostgreSQL versions tested on the CI
  .github/workflows/ci.yaml
Labels: improvement
