Repository scalar-labs/scalardb, pull requests merged in 2024-07, with the labels that each got.

#2002 Support listing namespaces for ScalarDB v3
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/SingleCrudOperationTransactionAdminIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosEnv.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/SingleCrudOperationTransactionAdminIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoEnv.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/SingleCrudOperationTransactionAdminIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/SingleCrudOperationTransactionAdminIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageEnv.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminIntegrationTest.java
  core/src/main/java/com/scalar/db/api/Admin.java
  core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/config/DatabaseConfig.java
  core/src/main/java/com/scalar/db/service/AdminService.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraConfig.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  core/src/main/java/com/scalar/db/storage/rpc/GrpcAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdmin.java
  core/src/main/java/com/scalar/db/transaction/rpc/GrpcTransactionAdmin.java
  core/src/main/java/com/scalar/db/transaction/singlecrudoperation/SingleCrudOperationTransactionAdmin.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTest.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraConfigTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTest.java
  core/src/test/java/com/scalar/db/storage/rpc/GrpcAdminTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminTest.java
  core/src/test/java/com/scalar/db/transaction/rpc/GrpcTransactionAdminTest.java
  core/src/test/java/com/scalar/db/transaction/singlecrudoperation/SingleCrudOperationTransactionAdminTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/CosmosCommand.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/DistributedStorageAdminIntegrationTestWithServer.java
  server/src/integration-test/java/com/scalar/db/server/ServerAdminTestUtils.java
  server/src/integration-test/java/com/scalar/db/server/ServerEnv.java
Labels: enhancement

#1976 Fix snapshot management issues
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TransactionResult.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
Labels: bugfix

#2014 Add check for encrypted columns to repairTable()
  core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java
  core/src/test/java/com/scalar/db/common/CheckedDistributedStorageAdminTest.java
Labels: improvement

#2016 Add caution notice about doc relocation to top of docs
  docs/add-scalardb-to-your-build.md
  docs/api-guide.md
  docs/backup-restore.md
  docs/configurations.md
  docs/data-modeling.md
  docs/design.md
  docs/getting-started-with-scalardb-by-using-kotlin.md
  docs/getting-started-with-scalardb.md
  docs/index.md
  docs/multi-storage-transactions.md
  docs/overview.md
  docs/requirements.md
  docs/scalardb-server.md
  docs/scalardb-supported-databases.md
  docs/schema-loader-import.md
  docs/schema-loader.md
  docs/storage-abstraction.md
  docs/two-phase-commit-transactions.md
Labels: documentation

#2015 Add TransactionExecutor
  core/src/main/java/com/scalar/db/common/TransactionExecutor.java
  core/src/test/java/com/scalar/db/common/TransactionExecutorTest.java
Labels: improvement

#2000 Change some JDBC data types to proper ones
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
  docs/schema-loader.md
Labels: enhancement

#2031 Add warning message for getNamespaceNames()
  core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java
Labels: improvement

#2026 Should return true for system namespace in namespaceExists()
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/test/java/com/scalar/db/storage/cassandra/CassandraAdminTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
Labels: improvement

#2034 Use a proper coordinator table schema based on whether the group commit feature is enabled or not
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitAdminIntegrationTestWithCassandra.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitAdminIntegrationTestWithCosmos.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitAdminIntegrationTestWithDynamo.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminIntegrationTestWithJdbcDatabase.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/util/AdminTestUtils.java
  server/src/integration-test/java/com/scalar/db/server/ConsensusCommitAdminIntegrationTestWithServer.java
Labels: enhancement

#2039 Make DistributedStorage, DistributedTransactionAdmin, and DistributedStorageAdmin extend AutoCloseable
  core/src/main/java/com/scalar/db/api/DistributedStorage.java
  core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/api/DistributedTransactionAdmin.java
Labels: improvement

#2042 Fix DistributedTransactionAdminIntegrationTestBase
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
Labels: bugfix

#2044 Create metadata namespace and table if they does not exist before creating user tables
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTestBase.java
Labels: improvement

#2035 Update Scheduled Vulnerability Check
  .github/workflows/scheduled-vuln-check.yaml
Labels: improvement

#2036 Update ScalarDB dependency version to 3.13.0
  README.md
  docs/getting-started-kotlin/build.gradle.kts
  docs/getting-started/build.gradle
Labels: documentation

#2032 Reduce Cosmos DB log messages in the integration test
  core/build.gradle
Labels: improvement

#1978 [CI] Install Oracle JDK 8 and 11 for integration test runtime
  .github/workflows/ci.yaml
Labels: improvement, github_actions

#2060 Support Coordinator table schema migration for the group commit in `ConsensusCommitAdmin.upgrade()`
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraSchemaLoaderIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitCassandraEnv.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitCosmosEnv.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosSchemaLoaderIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitDynamoEnv.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoSchemaLoaderIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitJdbcEnv.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageSchemaLoaderIntegrationTest.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdmin.java
  integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
  server/src/integration-test/java/com/scalar/db/server/SchemaLoaderIntegrationTestWithServer.java
Labels: enhancement

#2084 Fix CI issue SQL Server 2022 failed
  ci/no-superuser/create-no-superuser-sqlserver.sh
Labels: bugfix, github_actions

#2075 Fix TableMetadata
  core/src/main/java/com/scalar/db/api/TableMetadata.java
  core/src/test/java/com/scalar/db/api/TableMetadataTest.java
Labels: bugfix

#2061 [CI] Add integration test for MariaDB 11.4 and Oracle 19
  .github/workflows/ci.yaml
Labels: enhancement

#2076 Add getPartitionKey() and getClusteringKey() to ScalarDbUtils
  core/src/main/java/com/scalar/db/common/ProjectedResult.java
  core/src/main/java/com/scalar/db/common/ResultImpl.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/AbstractMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/FilteredResult.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RecoveryHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java
  core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposerTest.java
  core/src/test/java/com/scalar/db/util/ScalarDbUtilsTest.java
Labels: improvement

#2080 Make interfaces in OperationBuilder public
  core/src/main/java/com/scalar/db/api/OperationBuilder.java
Labels: improvement

#2082 Introduce DistributedTransactionExpirationHandlerSettable and TwoPhaseCommitTransactionExpirationHandlerSettable
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/common/DistributedTransactionExpirationHandlerSettable.java
  core/src/main/java/com/scalar/db/common/TwoPhaseCommitTransactionExpirationHandlerSettable.java
Labels: improvement

#2103 Update Gradle wrapper script files to 8.7
  docs/getting-started-kotlin/gradle/wrapper/gradle-wrapper.jar
  docs/getting-started-kotlin/gradle/wrapper/gradle-wrapper.properties
  docs/getting-started-kotlin/gradlew
  docs/getting-started-kotlin/gradlew.bat
  docs/getting-started/gradle/wrapper/gradle-wrapper.jar
  docs/getting-started/gradle/wrapper/gradle-wrapper.properties
  docs/getting-started/gradlew
  docs/getting-started/gradlew.bat
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: improvement

#2102 Fix compilation error when using the JDK 21 for Getting Started with Kotlin
  docs/getting-started-kotlin/build.gradle.kts
Labels: bugfix

#2101 Refactor ScalarDbUtils
  core/src/main/java/com/scalar/db/util/ScalarDbUtils.java
Labels: improvement

#2083 Fix NullPointerException when table is not found in Consensus Commit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
Labels: bugfix

#2127 Remove docs directory and update README
  .github/workflows/ci.yaml
  README.md
  docs/_config.yml
  docs/_includes/analytics.html
  docs/_layouts/default.html
  docs/add-scalardb-to-your-build.md
  docs/api-guide.md
  docs/backup-restore.md
  docs/configurations.md
  docs/data-modeling.md
  docs/design.md
  docs/getting-started-kotlin/build.gradle.kts
  docs/getting-started-kotlin/gradle.properties
  docs/getting-started-kotlin/gradle/wrapper/gradle-wrapper.jar
  docs/getting-started-kotlin/gradle/wrapper/gradle-wrapper.properties
  docs/getting-started-kotlin/gradlew
  docs/getting-started-kotlin/gradlew.bat
  docs/getting-started-kotlin/scalardb.properties
  docs/getting-started-kotlin/settings.gradle.kts
  docs/getting-started-kotlin/src/main/kotlin/Main.kt
  docs/getting-started-kotlin/src/main/kotlin/sample/ElectronicMoney.kt
  docs/getting-started-with-scalardb-by-using-kotlin.md
  docs/getting-started-with-scalardb.md
  docs/getting-started/build.gradle
  docs/getting-started/gradle/wrapper/gradle-wrapper.jar
  docs/getting-started/gradle/wrapper/gradle-wrapper.properties
  docs/getting-started/gradlew
  docs/getting-started/gradlew.bat
  docs/getting-started/scalardb.properties
  docs/getting-started/settings.gradle
  docs/getting-started/src/main/java/sample/ElectronicMoney.java
  docs/getting-started/src/main/java/sample/ElectronicMoneyMain.java
  docs/images/data_model.png
  docs/images/scalardb.png
  docs/images/scalardb_data_model.png
  docs/images/software_stack.png
  docs/images/two_phase_commit_load_balancing.png
  docs/images/two_phase_commit_sequence_diagram.png
  docs/index.md
  docs/multi-storage-transactions.md
  docs/overview.md
  docs/requirements.md
  docs/scalardb-server.md
  docs/scalardb-supported-databases.md
  docs/schema-loader-import.md
  docs/schema-loader.md
  docs/slides/TransactionManagementOnCassandra.pdf
  docs/storage-abstraction.md
  docs/two-phase-commit-transactions.md
Labels: documentation
