Repository scalar-labs/scalardb, pull requests merged in 2025-05, with the labels that each got.

#2603 Add the replication related APIs to DistributedAdmin for SSR
  core/src/main/java/com/scalar/db/api/DistributedTransactionAdmin.java
  core/src/main/java/com/scalar/db/api/ReplicationAdmin.java
  core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionAdmin.java
  core/src/main/java/com/scalar/db/common/error/CoreError.java
Labels: enhancement

#2610 Disallow scan operations after delete in Consensus Commit
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
Labels: improvement

#2611 Revise README to include links to docs for better guidance
  README.md
Labels: documentation

#2583 Fix for export projection and null data excluded bugs
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/CsvProducerTask.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/JsonLineProducerTask.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/JsonProducerTask.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/UnitTestUtils.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/producer/CsvProducerTaskTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/producer/JsonLineProducerTaskTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/producer/JsonProducerTaskTest.java
Labels: bugfix

#2591 Add import log classes and utils
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/log/AbstractImportLogger.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/log/ImportLoggerConfig.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/log/SingleFileImportLogger.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/log/SplitByDataChunkImportLogger.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/log/writer/DefaultLogWriterFactory.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/log/writer/LocalFileLogWriter.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/log/writer/LogFileType.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/log/writer/LogWriter.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/log/writer/LogWriterFactory.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/log/SingleFileImportLoggerTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/log/SplitByDataChunkImportLoggerTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/log/writer/DefaultLogWriterFactoryTest.java
Labels: enhancement

#2598 Support IBM Db2
  .github/workflows/ci.yaml
  build.gradle
  core/build.gradle
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitAdminIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminImportTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseColumnValueIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseCrossPartitionScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultipleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMultiplePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSecondaryIndexIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSingleClusteringKeyScanIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseSinglePartitionKeyIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderImportIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcTestUtils.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/SingleCrudOperationTransactionAdminIntegrationTestWithJdbcDatabase.java
  core/src/integration-test/java/com/scalar/db/transaction/jdbc/JdbcTransactionAdminIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcConfig.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineDb2.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineFactory.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineTimeTypeDb2.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/MergeIntoQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SimpleSelectQuery.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcConfigTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/RdbEngine.java
  core/src/test/java/com/scalar/db/storage/jdbc/RdbEngineTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminRepairIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/schemaloader/SchemaLoaderIntegrationTestBase.java
Labels: enhancement

#2612 Relax visibility of Coordinator's methods for use by other ScalarDB components
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Coordinator.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorTest.java
Labels: improvement

#2582 Rename parameters from ScalarDB to ScalarDb
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/ScalarDbMode.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/CsvExportManager.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/ExportManager.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/JsonExportManager.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/JsonLineExportManager.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/ImportManager.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDbDao.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDbDaoException.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/ImportProcessor.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/ImportProcessorParams.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportStorageTask.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportTask.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportTaskParams.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportTransactionalTask.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/CsvExportManagerTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/JsonExportManagerTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/JsonLineExportManagerTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDbDaoTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/CsvImportProcessorTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/JsonImportProcessorTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/JsonLinesImportProcessorTest.java
Labels: improvement

#2642 Improve DecoratedDistributedTransactionManager and DecoratedTwoPhaseCommitTransactionManager
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/DecoratedTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/common/StateManagedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/StateManagedTwoPhaseCommitTransactionManager.java
Labels: improvement

#2616 Add util classes for data loader CLI
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommand.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/DirectoryUtils.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/FileUtils.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/InvalidFilePathException.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/DirectoryUtilsTest.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/FileUtilsTest.java
Labels: enhancement

#2637 Add link to ScalarDB design doc in README
  README.md
Labels: documentation

#2641 Fix for `admin.getNamespaceNames()` when used with DynamoDB with the namespace prefix setting
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoAdminTestBase.java
Labels: bugfix

#2621 Improve validation logic in Consensus Commit to correctly handle scan with limit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Labels: bugfix

#2651 Optimize JDBC storage by using Connection.setReadOnly()
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcDatabaseTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcUtilsTest.java
Labels: improvement

#2662 Add exception handling for DateTimeParseException
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/ColumnUtils.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/ColumnUtilsTest.java
Labels: bugfix

#2674 Remove version from prepare-records condition in Consensus Commit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/PrepareMutationComposerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/SnapshotTest.java
Labels: improvement

#2617 Add export command for data loader CLI
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommand.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommandOptions.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/MultiColumnKeyValueConverter.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ScanOrderingConverter.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/SingleColumnKeyValueConverter.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/CommandLineInputUtils.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommandTest.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/dataexport/MultiColumnKeyValueConverterTest.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/dataexport/ScanOrderingConverterTest.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/dataexport/SingleColumnKeyValueConverterTest.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/CommandLineInputUtilsTest.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/DirectoryUtilsTest.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/KeyUtils.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/KeyUtilsTest.java
Labels: enhancement

#2681 Set up CODEOWNERS to automatically assign reviewers for new PR
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: improvement

#2694 Add GitHub action to assign reviewers on PR created by Dependabot
  .github/CODEOWNERS
  .github/workflows/assign-dependabot-pr-reviewers.yaml
Labels: improvement, github_actions

#2618 Add import command for data loader CLI
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataimport/ImportCommand.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataimport/ImportCommandOptions.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/dataimport/ImportCommandTest.java
Labels: enhancement

#2700 Handle Get with index correctly in CrudHandler
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Labels: bugfix

#2697 Reset data chunk id counter for import process
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/CsvImportProcessor.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/JsonImportProcessor.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/JsonLinesImportProcessor.java
Labels: bugfix
