Repository scalar-labs/scalardb, pull requests merged in 2025-06, with the labels that each got.

#2708 Remove default logging in the Data Loader DAO
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDbDao.java
Labels: improvement

#2709 Refactor import logic and remove redundant status mapping
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/ImportEventListener.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/ImportManager.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/log/SingleFileImportLogger.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/log/SplitByDataChunkImportLogger.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/CsvImportProcessor.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/ImportProcessor.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/JsonImportProcessor.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/JsonLinesImportProcessor.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/CsvImportProcessorTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/JsonImportProcessorTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/JsonLinesImportProcessorTest.java
Labels: improvement

#2733 Merge ConsensusCommitTestUtils and ConsensusCommitIntegrationTestUtils
  core/src/integration-test/java/com/scalar/db/storage/cassandra/ConsensusCommitCassandraEnv.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/ConsensusCommitCosmosEnv.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/ConsensusCommitDynamoEnv.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/ConsensusCommitJdbcEnv.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageSchemaLoaderIntegrationTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminImportTableIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitAdminRepairIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitCrossPartitionScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitIntegrationTestUtils.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTestUtils.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitWithIncludeMetadataEnabledIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitCrossPartitionScanIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitWithIncludeMetadataEnabledIntegrationTestBase.java
Labels: improvement

#2736 Create and publish snapshot version of data loader core
  .github/workflows/release-snapshot.yaml
  .github/workflows/upload-artifacts.yaml
  data-loader/core/build.gradle
Labels: enhancement

#2742 Fix Gradle configurations in data-loader module
  data-loader/build.gradle
  data-loader/cli/build.gradle
  data-loader/core/build.gradle
  settings.gradle
Labels: bugfix

#2728 Move parallelism level for the importing process from the record level to the data chunk level
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/ImportProcessor.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/processor/ImportProcessorTest.java
Labels: improvement

#2727 Add validation for import/export integer params to make sure they are positive
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommand.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/command/dataimport/ImportCommand.java
  data-loader/cli/src/main/java/com/scalar/db/dataloader/cli/util/CommandLineInputUtils.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/dataexport/ExportCommandTest.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/command/dataimport/ImportCommandTest.java
  data-loader/cli/src/test/java/com/scalar/db/dataloader/cli/util/CommandLineInputUtilsTest.java
Labels: improvement

#2747 Add `--replication-tables` option to the Schema Loader
  core/src/main/java/com/scalar/db/api/ReplicationAdmin.java
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  schema-loader/build.gradle
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaLoader.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/SchemaOperator.java
  schema-loader/src/main/java/com/scalar/db/schemaloader/command/SchemaLoaderCommand.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaLoaderTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/SchemaOperatorTest.java
  schema-loader/src/test/java/com/scalar/db/schemaloader/command/SchemaLoaderCommandTest.java
Labels: enhancement

#2749 Add support for beginning transactions in read-only mode
  core/src/main/java/com/scalar/db/api/DistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/ActiveTransactionManagedTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/ReadOnlyDistributedTransaction.java
  core/src/main/java/com/scalar/db/common/StateManagedDistributedTransactionManager.java
  core/src/main/java/com/scalar/db/common/StateManagedTwoPhaseCommitTransactionManager.java
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  core/src/main/java/com/scalar/db/service/TransactionService.java
  core/src/main/java/com/scalar/db/storage/dynamo/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/main/java/com/scalar/db/transaction/singlecrudoperation/SingleCrudOperationTransactionManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/jdbc/JdbcTransactionManagerTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/singlecrudoperation/SingleCrudOperationTransactionIntegrationTestBase.java
Labels: enhancement

#2752 Resolve minor bugs in data loader core
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/processor/ImportProcessor.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportTask.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/ColumnUtils.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/ColumnUtilsTest.java
Labels: bugfix

#2756 Introduce StorageInfo
  core/src/integration-test/java/com/scalar/db/storage/cassandra/CassandraMutationAtomicityUnitIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/cosmos/CosmosMutationAtomicityUnitIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoMutationAtomicityUnitIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcDatabaseMutationAtomicityUnitIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageMutationAtomicityUnitIntegrationTest.java
  core/src/main/java/com/scalar/db/api/DistributedStorage.java
  core/src/main/java/com/scalar/db/api/DistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/api/StorageInfo.java
  core/src/main/java/com/scalar/db/common/CheckedDistributedStorageAdmin.java
  core/src/main/java/com/scalar/db/common/StorageInfoImpl.java
  core/src/main/java/com/scalar/db/common/StorageInfoProvider.java
  core/src/main/java/com/scalar/db/common/checker/OperationChecker.java
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  core/src/main/java/com/scalar/db/service/AdminService.java
  core/src/main/java/com/scalar/db/storage/cassandra/Cassandra.java
  core/src/main/java/com/scalar/db/storage/cassandra/CassandraAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/Cosmos.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosAdmin.java
  core/src/main/java/com/scalar/db/storage/cosmos/CosmosOperationChecker.java
  core/src/main/java/com/scalar/db/storage/dynamo/Dynamo.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoAdmin.java
  core/src/main/java/com/scalar/db/storage/dynamo/DynamoOperationChecker.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcDatabase.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorage.java
  core/src/main/java/com/scalar/db/storage/multistorage/MultiStorageAdmin.java
  core/src/main/java/com/scalar/db/transaction/jdbc/JdbcTransactionManager.java
  core/src/test/java/com/scalar/db/common/checker/OperationCheckerTest.java
  core/src/test/java/com/scalar/db/storage/cosmos/CosmosOperationCheckerTest.java
  core/src/test/java/com/scalar/db/storage/dynamo/DynamoOperationCheckerTest.java
  core/src/test/java/com/scalar/db/storage/multistorage/MultiStorageAdminTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageMutationAtomicityUnitIntegrationTestBase.java
Labels: enhancement

#2758 Add Docker support for ScalarDB Data Loader CLI
  .github/workflows/ci.yaml
  .github/workflows/create-release.yaml
  .github/workflows/release-snapshot.yaml
  .github/workflows/remove-untagged-images.yaml
  .github/workflows/upload-artifacts.yaml
  .github/workflows/vuln-check.yaml
  data-loader/cli/Dockerfile
  data-loader/cli/build.gradle
Labels: enhancement

#2764 Add further optimizations for Consensus Commit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManagerTest.java
  integration-test/src/main/java/com/scalar/db/api/DistributedTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/TwoPhaseCommitTransactionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/singlecrudoperation/SingleCrudOperationTransactionIntegrationTestBase.java
Labels: improvement

#2765 Skip commit-state for read-only transactions in Consensus Commit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommitTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManagerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Labels: improvement

#2761 Add a dedicated CI workflow for data loader CLI
  .github/workflows/data-loader-ci.yaml
Labels: enhancement

#2785 Rename methods of CommitHandler
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommit.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ParallelExecutorTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Labels: improvement

#2787 Remove before images after committing or rolling back records in Consensus Commit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/AbstractMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposer.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitMutationComposerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/RollbackMutationComposerTest.java
Labels: improvement

#2797 Prevent overwriting read set in Consensus Commit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CrudHandler.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CrudHandlerTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Labels: bugfix

#2807 Optimize mutations based on the storage’s mutation atomicity unit in Consensus Commit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/MutationsGrouper.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/PartitionedMutations.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommitTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/MutationsGrouperTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/PartitionedMutationsKeyTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/PartitionedMutationsTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Labels: improvement

#2811 Support one-phase commit optimization in Consensus Commit
  core/src/main/java/com/scalar/db/common/CoreError.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommit.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfig.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitManager.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/MutationsGrouper.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/OnePhaseCommitMutationComposer.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/Snapshot.java
  core/src/main/java/com/scalar/db/transaction/consensuscommit/TwoPhaseConsensusCommitManager.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommitTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitConfigTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/MutationsGrouperTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/OnePhaseCommitMutationComposerTest.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitNullMetadataIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/transaction/consensuscommit/ConsensusCommitSpecificIntegrationTestBase.java
Labels: enhancement

#2814 Update Scheduled Vulnerability Check and Dependabot configuration
  .github/dependabot.yml
  .github/workflows/scheduled-vuln-check.yaml
Labels: improvement, github_actions

#2815 Update ScalarDB dependency version to 3.16.0 in README
  README.md
Labels: documentation
