Repository scalar-labs/scalardb, pull requests merged in 2025-02, with the labels that each got.

#2484 Fix Javadoc warning in integration test
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminImportTableIntegrationTestBase.java
Labels: improvement

#2515 Update ScalarDB dependency version to 3.15.1 in README
  README.md
Labels: documentation

#2521 update README
  README.md
  docs/images/scalardb-video-preview.png
  docs/images/scalardb.png
Labels: documentation

#2445 Add Control file module files and validation
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFile.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFileValidationException.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFileValidator.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFileValidatorTest.java
Labels: enhancement

#2446 Add dtos and other classes for task
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/ImportOptions.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/log/LogMode.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/mapping/ImportDataMapping.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/validation/ImportSourceRecordValidationResult.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/validation/ImportSourceRecordValidator.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/task/mapping/ImportDataMappingTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/task/validation/ImportSourceRecordValidatorTest.java
Labels: enhancement

#2537 Add workflow_dispatch to release workflows
  .github/workflows/release-snapshot.yaml
  .github/workflows/release.yaml
Labels: improvement, github_actions

#2450 Add export tasks
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/DataLoaderObjectMapper.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/CsvExportManager.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/ExportManager.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/ExportReport.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/JsonExportManager.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/JsonLineExportManager.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/CsvProducerTask.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/JsonLineProducerTask.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/JsonProducerTask.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/ProducerResult.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/ProducerTask.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/ProducerTaskFactory.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/CsvExportManagerTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/ExportReportTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/JsonExportManagerTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/JsonLineExportManagerTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/producer/CsvProducerTaskTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/producer/JsonLineProducerTaskTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/producer/JsonProducerTaskTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/producer/ProducerTaskFactoryTest.java
Labels: enhancement

#2550 Add support for new date, time data types
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/CsvProducerTask.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/JsonLineProducerTask.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/producer/JsonProducerTask.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/ColumnUtils.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/UnitTestUtils.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/producer/CsvProducerTaskTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/ColumnUtilsTest.java
Labels: enhancement
