Repository scalar-labs/scalardb, pull requests merged in 2025-07, with the labels that each got.

#2820 Refactor ParallelExecutor
  core/src/main/java/com/scalar/db/transaction/consensuscommit/ParallelExecutor.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ParallelExecutorTest.java
Labels: improvement

#2825 Minor fixes to unit tests
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CoordinatorGroupCommitterTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/ParallelExecutorTest.java
Labels: bugfix

#2826 Fix error handling for one-phase commit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandler.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommitTest.java
Labels: bugfix

#2832 Fix behavior of group commit with one-phase commit
  core/src/main/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommit.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerTest.java
  core/src/test/java/com/scalar/db/transaction/consensuscommit/CommitHandlerWithGroupCommitTest.java
Labels: bugfix

#2847 Add DynamoDB permission test
  .github/workflows/permission-check.yaml
  core/build.gradle
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoAdminPermissionIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoEnv.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoPermissionIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/dynamo/DynamoPermissionTestUtils.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStorageAdminPermissionIntegrationTestBase.java
  integration-test/src/main/java/com/scalar/db/api/DistributedStoragePermissionIntegrationTestBase.java
Labels: improvement

#2863 [addendum] Use JReleaser to release artifacts in Maven Central
  .github/workflows/release.yaml
  .github/workflows/upload-artifacts.yaml
Labels: improvement, github_actions

#2870 Pass necessary secrets to release workflow
  .github/workflows/release.yaml
  .github/workflows/upload-artifacts.yaml
Labels: bugfix

#2877 Increase heap size for jreleaserDeploy task
  .github/workflows/release-snapshot.yaml
  .github/workflows/upload-artifacts.yaml
Labels: improvement, github_actions

#2888 Fix Oracle engine to support multiple Oracle users for index operations
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcAdmin.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
Labels: bugfix

#2894 Use PostgreSQL in integration tests by default
  .github/workflows/ci.yaml
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java
  core/src/integration-test/java/com/scalar/db/storage/multistorage/MultiStorageEnv.java
Labels: improvement

#2896 Add JDBC database permission test
  .github/workflows/permission-check.yaml
  core/build.gradle
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcAdminPermissionIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcPermissionIntegrationTest.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcPermissionTestUtils.java
Labels: improvement

#2914 Refactor JDBC adapter related code
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcEnv.java
  core/src/integration-test/java/com/scalar/db/storage/jdbc/JdbcSchemaLoaderImportIntegrationTest.java
  core/src/main/java/com/scalar/db/storage/jdbc/JdbcUtils.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineDb2.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineMysql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineOracle.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEnginePostgresql.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlServer.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineStrategy.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/MergeIntoQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/MergeQuery.java
  core/src/main/java/com/scalar/db/storage/jdbc/query/SelectQuery.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
Labels: improvement
