Repository scalar-labs/scalardb, pull requests merged in 2025-01, with the labels that each got.

#2444 Add prefix to error code
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  core/src/test/java/com/scalar/db/common/error/CoreErrorTest.java
Labels: improvement

#2420 Fix Slf4j providers not found error
  core/build.gradle
Labels: improvement

#2435 Add export options validator
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidationException.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidator.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataexport/validation/ExportOptionsValidatorTest.java
Labels: enhancement

#2448 Add utility setter methods for ImmutableMap to AbacOperationAttributes
  core/src/main/java/com/scalar/db/api/AbacOperationAttributes.java
  core/src/test/java/com/scalar/db/api/AbacOperationAttributesTest.java
Labels: improvement

#2465 Fix missing unit tests for MariaDB RdbEngine
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/RdbEngine.java
  core/src/test/java/com/scalar/db/storage/jdbc/query/QueryBuilderTest.java
Labels: improvement

#2469 Remove unnecessary loggings in statement handlers
  core/src/main/java/com/scalar/db/storage/cassandra/BatchHandler.java
  core/src/main/java/com/scalar/db/storage/cassandra/MutateStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cassandra/SelectStatementHandler.java
  core/src/main/java/com/scalar/db/storage/cassandra/StatementHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/BatchHandler.java
  core/src/main/java/com/scalar/db/storage/cosmos/MutateStatementHandler.java
Labels: improvement

#2476 Add importTable without overrideColumnsType to DecoratedDistributedTransactionAdmin
  core/src/main/java/com/scalar/db/common/DecoratedDistributedTransactionAdmin.java
Labels: improvement

#2479 Update Scheduled Vulnerability Check and Dependabot configuration
  .github/dependabot.yml
  .github/workflows/scheduled-vuln-check.yaml
Labels: improvement, github_actions

#2480 Update ScalarDB dependency version to 3.15.0 in README
  README.md
Labels: documentation

#2485 Remove unnecessary error code
  core/src/main/java/com/scalar/db/common/error/CoreError.java
Labels: bugfix

#2491 Change DATE type encoding to integer
  core/src/main/java/com/scalar/db/storage/cosmos/ResultInterpreter.java
  core/src/main/java/com/scalar/db/storage/dynamo/ResultInterpreter.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/BytesUtils.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/DateBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/dynamo/bytes/IntBytesEncoder.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineSqlite.java
  core/src/main/java/com/scalar/db/storage/jdbc/RdbEngineTimeTypeSqlite.java
  core/src/main/java/com/scalar/db/util/TimeRelatedColumnEncodingUtils.java
  core/src/test/java/com/scalar/db/storage/TimeRelatedColumnEncodingUtilsTest.java
  core/src/test/java/com/scalar/db/storage/jdbc/JdbcAdminTest.java
Labels: improvement

#2442 Add data chunk and task result enums and dtos
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/datachunk/ImportDataChunk.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/datachunk/ImportDataChunkStatus.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/datachunk/ImportDataChunkStatusState.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/datachunk/ImportRow.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/ImportTaskAction.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/result/ImportResultStatus.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/result/ImportTargetResult.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/result/ImportTargetResultStatus.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/task/result/ImportTaskResult.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/transactionbatch/ImportTransactionBatch.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/transactionbatch/ImportTransactionBatchResult.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/transactionbatch/ImportTransactionBatchStatus.java
Labels: enhancement

#2434 Add table metadata service
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFileTable.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/controlfile/ControlFileTableFieldMapping.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataException.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataRequest.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataService.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/util/TableMetadataUtil.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/tablemetadata/TableMetadataServiceTest.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/util/TableMetadataUtilTest.java
Labels: enhancement

#2417 Add ScalarDB Dao and related files
  core/src/main/java/com/scalar/db/common/error/CoreError.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDBDao.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDBDaoException.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDbStorageManager.java
  data-loader/core/src/main/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDbTransactionManager.java
  data-loader/core/src/test/java/com/scalar/db/dataloader/core/dataimport/dao/ScalarDBDaoTest.java
  gradle/spotbugs-exclude.xml
Labels: enhancement
